### ISSUE TITLE
Zombie Containers in ECS

### ISSUE THREAD

**Issue by RogerParkinson** [aws/amazon-ecs-agent#1044]
Sometimes we find our ECS cluster is running some containers we thought were removed. We notice them because they registered with Eureka but we don't see them in ECS. For example I have a cluster running one instance of Zuul ie ECS tells me the Zuul service is running one instance.

But Zuul registers with Eureka. When I look at Eureka's dashboard it tells me there are two instances of Zuul running. Huh? I ssh'd into the EC2 where Eureka said the strange Zuul was running and, sure enough, there's a Zuul container ECS doesn't know about. So I have two Zuuls, one I want and one zombie. I'll call it a zombie but it is running, it must be pinging Eureka regularly or it would have been deregistered there.

This is a problem, but I do have a clue how it happened. When Eureka comes up it binds that machine to an EIP, so its IP address changes. I think this might be causing ECS to lose touch with the agent running on that EC2. I am guessing that this prevents ECS from seeing the existing Zuul and it then starts another one on a different EC2. Meanwhile the zombie Zuul continues to send heartbeats to Eureka, and presumably the heartbeat code updated its address, or it uses the internal IP which didn't change. There is a new instance of Eureka on the machine with the zombies that was just deployed, and the EIP was changed there etc.

Slightly puzzling is that ECS is still in contact with the ecs-agent on that machine because it did deploy the new Eureka there and it is running quite happily.

But the core of my theory is that the EIP change confused ecs-agent enough to lose touch with the existing containers on that machine. Does this theory make sense to anyone else?

**Comment by samuelkarp** [comment]
@RogerParkinson I'd be happy to take a look, but I'll need a bit more information from you in order to investigate (logs, affected task/container, etc).  Can you run the [ECS logs collector](https://github.com/awslabs/ecs-logs-collector) and email the resulting file to me at skarp at amazon.com?  If you can let me know which of the containers is the expected one and which is the "zombie" that would help too.

I wouldn't expect an EIP assignment to affect ECS's ability to track containers (though there certainly could be a bug if you're running your Zuul instance in an ECS service behind a load balancer).  However, the logs should shed a bit more light on what's going on and I can certainly look to see if EIP assignment is affecting anything.

**Comment by RogerParkinson** [comment]
I've cleaned it all up now, so there isn't anything I can send. Zuul is behind a load balancer but that was just an example. There were three other zombie services on that EC2 that weren't on the load balancer. I can try and reproduce it in the next few days and collect logs. Thanks for the reply.

**Comment by adnxn** [comment]
I'm closing this issue since we haven't heard back. Feel free to open a new issue if you run into similar problems in the future. Thanks!
