### ISSUE TITLE
Clarification on AWS/ECS/CPUUtilization Cloudwatch Metric for t2 instances that have partial baseline core performance

### ISSUE THREAD

**Issue by knizami** [aws/amazon-ecs-agent#1046]
We are designing scale in policies for ECS and want to scale in when the instances are utilizing half of their baseline utilization.  For t2.large instances, the baseline from CloudWatch is typically reported as 30% utilized when operating at max base performance without using CPU credits.

How does this relate to the CPU utilization reported by the ECS metric for the cluster?  For example, if I have a cluster with an autoscaling group whose launch configuration has (3) t2.large instances, is the CPU utilization at its max baseline 100% or 30%?  If it is the former, we would set our scalin to 50%, if it is the latter, we would set our scale in to 15%.  

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html

**Comment by adnxn** [comment]
Hi @knizami, the [ECS cluster cpu utilization](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#cluster_utilization) metric will report 100% when operating at max base performance. However since the scheduler makes task placement decisions based on resource availability in the cluster, we suggest using [reservation metrics](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#cluster_reservation) since dynamically reducing the number of instances in your cluster may prevent the scheduler from placing tasks. Also refer to this blog post covering [autoscaling with ECS](https://aws.amazon.com/blogs/compute/automatic-scaling-with-amazon-ecs) for more information.
