### ISSUE TITLE
Upgrading the ECS agent doesn't reliably update the instance's attributes

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-ecs-agent#1087]
### Summary
When updating the agent through the ECS console, only 1 of the 6 instances updated their instance attributes. 

### Description
ECS failed to update the instance attributes with the following attributes: 
ecs.capability.task-eni
ecs.capability.cni-plugin-version
ecs.vpc-id
ecs.subnet-id

### Expected Behavior
Expect ECS to always update an instances attributes when the agent is upgraded. 

### Observed Behavior
Instance attributes were unchanged after upgrading the agent to 1.15.1

**Comment by adnxn** [comment]
@jicowan So I understand, you've manually updated the agents on all six instances using the ECS console, but you're only seeing one of the six instances with the updated attributes you've listed. Is this correct?

**Comment by jicowan** [comment]
Yes, that's correct.

**Comment by adnxn** [comment]
You'll need to [update your ecs-init](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/agent-update-ecs-ami.html) to at least 1.15.0 to enable the task networking related agent capabilities.

**Comment by jicowan** [comment]
That's odd.  I didn't update ecs-init on the instance that worked.  The agent on all of the instances was upgraded to the latest version, but the container instance attributes were not updated with the new VPC networking attributes.

**Comment by adnxn** [comment]
I was able to reproduce your issue going from 1.14.0 to latest. Since ecs-init 1.14.0 didn't have the task networking changes, updating the agent to latest on those instances didn't register the capabilities that you listed. However on an instance with ecs-init 1.15.0 and updating the agent to latest did register the capabilities listed above. 

Can you verify the init/agent versions you're upgrading from on each of the instances? And which versions you are upgrading to?

Are you able to reproduce the issue?

**Comment by adnxn** [comment]
Closing issue since we haven't heard back. Feel free to update if you have more information regarding your update steps. Thanks.

**Comment by jicowan** [comment]
I don't recall what init/agent versions were on the container instances when I upgraded them.  I haven't had time to reproduce the issue, but your explanation makes sense.  Can you update the documentation explaining that you may need to replace the instance if the instance attributes don't update after updating the agent through the console.
