### ISSUE TITLE
Support for docker-compose like YAML file for task definitions

### ISSUE THREAD

**Issue by eldos-dl** [aws/amazon-ecs-agent#109]
The current JSON style task definition format is making the definitions unnecessarily lengthy and difficult to maintain. Can we get support for docker-compose like task definitions?

**Comment by samuelkarp** [comment]
Thanks for the feedback!  Task Definitions can currently be expressed as JSON in the CLI or as [objects in our SDKs](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/model/TaskDefinition.html).  We're also aware of an open-source [container-transform](https://github.com/ambitioninc/container-transform) project which converts between Task Definition and docker-compose representations.

Since this isn't really a question about the Agent I'm going to close the issue here, but I have taken your feature request into our internal tracking system.

**Comment by harishkashyap** [comment]
+1 to @eldos-dl request. task definitions are just lengthy, cumbersome. I would suggest that AWS team expands on container-transform and runs it internally so we only have to submit the docker-compose.yml file and everything is done at your end.

**Comment by wyaeld** [comment]
@samuelkarp Now that cloudformation supports YAML, can you offer feedback on whether ECS is getting any closer to it?

I know its not agent specific, but there isn't another ecs project with an issue tracker...
