### ISSUE TITLE
ECS Agent starting from local cache when tag no longer exists upstream

### ISSUE THREAD

**Issue by zbintliff** [aws/amazon-ecs-agent#1136]
### Summary
ECS node had an image of tag `x` locally. The tag `x` was deleted from the ECR repository.  When we launch a _new_ task, we get a ContainerPullError but the agent still runs the container from the local cache. This results in a task that has state `RUNNING (ContainerPullError)`. Is this expected behavior?

### Description
Docker Pull exits with status 1 if image tag doesn't exist upstream, even if local. Should the ECS agent fail fast here or run the container using the image from the local cache?

### Environment Details
ECS Agent 1.16.0

As an aside, we stress to dev teams not to mutate docker tags to avoid scenarios like these.

**Comment by jhaynes** [comment]
Hi @zbintliff This is expected behavior.

In the case where a registry or image in not accessible, but the correct image is cached on the host, agent will still run the cached image. 

There is more discussion about this behavior and possible changes to it in https://github.com/aws/amazon-ecs-agent/issues/413#issuecomment-222028159. However, the behavior you're suggesting (to fail the task if a pull fails) is not discussed.

**Comment by zbintliff** [comment]
Great thanks, we will pass along to our users this is expected behavior.
