### ISSUE TITLE
Docker Bench Security Recommendations

### ISSUE THREAD

**Issue by mikealbert** [aws/amazon-ecs-agent#114]
Hi,

We ran the [docker bench security] (https://github.com/docker/docker-bench-security) container against our ECS cluster, and it is recommending a few changes for the ecs-agent container.  We are using the ECS optimized AMI for our environment.  Here are a few items that were flagged:

* ecs-agent is running as root within its container
* no memory usage limitations exist on the ecs-agent container
* no cpu prioritization is set for the ecs-agent container

Can the above items be addressed in future releases of the ecs-agent?

Thanks.

**Comment by euank** [comment]
Hi @mikealbert.
We'll need to consider these suggestions a bit more before we decide if we want to enable them by default in the ECS Optimized AMI, but if you want to enforce cpu and memory limits on the Agent, you can launch it with those configurations today via `docker run`.
What you're asking for here is changing the configuration specified in our [ecs-init](https://github.com/aws/amazon-ecs-init/blob/8f21c8bf071dc625e08470d59931e286c9b3bac9/ecs-init/docker/docker.go#L162) package, correct?
Would allowing those values to be user-configurable be a good solution for you?

The first point, that the process is running as root, is not as easy to solve as you'd also have to rebuild the Agent into a container with multiple users since the existing image is scratch-based &mdash; it does not have any of the usual user tooling (like `/etc/passwd`, etc).
What's more, the Agent at a high level is meant to manage other processes so it makes some (symbolic at least) sense for it to run as root.

I'd be happy to hear any further clarification on what use-case you have for these changes.

**Comment by mikealbert** [comment]
@euank Thanks for the response.

Allowing cpu and memory limits to be user configurable options sounds like a good solution to me.  We'll look into doing this manually in the interim.

As far as running the ecs-agent process as root, I definitely understand there are some challenges with that architecture.  I hadn't seen any discussion about this topic on the ECS forum or here, so figured I'd bring it up since it is outside of Docker's recommended config.  Sounds like it won't be worth the effort, but thanks for providing an explanation of the architecture.

**Comment by euank** [comment]
I created the above-referenced issue in the init script's repository to track cpu/memory limit configuration.

To do those configurations yourself, a good starting point would be the 5th step [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).


I'd like to clarify a little more about my comment with regards to user/root above though. It's not just architecture in-so-much as adding the fiddly linuxy bits into the container to allow running as a user, there's also another problem.

The Agent's main purpose is to interact with the Docker daemon, including starting new containers. To that end, it mounts in the `docker.sock` file with write permissions so that it may start new containers on behalf of ECS.
Currently, Docker does not allow a way to limit a process interacting with it to only have access to a subset of the API it provides, and thus the Agent is technically capable of running a container with any configuration (including privileged). This means that the Agent, by its nature, is already quite privileged and I personally feel that changing the user (but still allowing it to write to the `docker.sock` by some means) is just a false sense of security &mdash; just checking off a box that doesn't mean anything.
I could see the argument that the blast radius of poorly behaving code within the agent (accidental, not malicious) can be reduced by changing the run-as user, but I feel the containerization + scratch filesystem means the actual difference there is quite minimal. The intent of Docker Bench here, I believe, is to reduce the blast radius of malicious code, but because of the `docker.sock` being writable, that blast radius is equivalently large whatever user it runs as.

I'm happy to hear other arguments and reconsider. Hopefully what I wrote does make sense though.

Thanks for raising the concern. I'm closing this issue because I don't think there's an actionable change on the Agent's end currently (just the init change above), but if you'd like to discuss or comment further, please do reopen it.
Thanks again,
Euan
