### ISSUE TITLE
CannotPullContainerError

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-agent#1185]
Status reason | CannotPullContainerError: API error (404)

The image is available in the repository but I am getting CannotPullContainerError while running the task.
-- | --

**Comment by aaithal** [comment]
Hi @dulimitta, 

We're sorry that you're running into this issue. Could you please share the ECS agent logs with us so that we can better investigate what's going wrong here? The logs are present in the `/var/log/ecs` directory if you're using ECS optimized/Amazon Linux AMI. You can also use https://github.com/awslabs/ecs-logs-collector for collection logs. More details are available [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/logs.html) and [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html). You can send them to aithal at amazon dot com if you do not want to post them publicly.

Thanks,
Anirudh

**Comment by dulimitta** [comment]
Hi @aaithal , thanks for your quick reply. After looking into the /var/log/ecs, I learned the service is failing because of the memory issue. I would get it fixed. Thanks once again.
