### ISSUE TITLE
Use ENI with Docker container

### ISSUE THREAD

**Issue by tiwarivikash** [aws/amazon-ecs-agent#1190]
### Summary

How to use ENI with docker container

### Description

I have an ENI and its IP is configured in a downstream system. I attach this ENI to an EC2 which hosts my docker containers managed by ECS. I want to use ENI for outbound calls from docker container on a specific port. Is there a way to make container use ENI (eth1) for an outbound call via a specific port?

**Comment by tiwarivikash** [comment]
@aaithal Can I use existing ENI with containers running in awsvpc mode? I would like to keep ENIs in case EC2 or tasks are terminated for some reason because IPs of ENIs are configured in downstream system.

**Comment by aaithal** [comment]
> Can I use existing ENI with containers running in awsvpc mode?

We did consider that use-case and have heard about it from other customers too. However, with the way this feature works today, we don't support 'bringing your own ENI' use-case. Is it possible for you to instead rely on an ip address range/CIDR in the downstream system? Because, then you can map that to your CIDR and offload all of your ENI management logic to ECS by using [Task networking for ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html).

**Comment by tiwarivikash** [comment]
@aaithal Is it possible to provide a CIDR(a.b.c.d / 30) block in ECS? I can have all possible IPs of CIDR configured in downstream system. I could not find any documentation related to this. Is this something I will have to configure in NetworkConfig in task-def.

**Comment by aaithal** [comment]
Hi @tiwarivikash, 

> Is it possible to provide a CIDR(a.b.c.d / 30) block in ECS? I can have all possible IPs of CIDR configured in downstream system.

You can provide the subnet that corresponds to the CIDR block via the `subnets` config param in `awsvpcConfiguration` blob while running the task or the service. In the following example, the subnet `subnet-c070009b` will be used to create a new task with an ENI:

```bash
$ aws ecs run-task --cluster awsvpc-ecs-demo --network-configuration "awsvpcConfiguration={subnets=["subnet-c070009b"],securityGroups=["sg-9effe8e4"]}" nginx-awsvpc 
```

**Comment by tiwarivikash** [comment]
I can have a small subnet and run tasks in any networking mode(bridge/awsvpc/host) because outbound calls would seem to originate from private IP of EC2. It was first approach I came up with but we have to rely on a different team for managing subnets in my organization that is why I was trying to figure out a way to make ECS works with ENIs. Thank you @aaithal for looking into it.

**Comment by tiwarivikash** [comment]
@aaithal Solved the problem by adding IP route in host machine to use ENI for outbound traffic to downstream system.

**Comment by aaithal** [comment]
Nice! the disadvantages of doing that is that there's avenues where all of the traffic on your instance could potentially be routed through that. Since 'bring your own ENI' use-case is already being tracked as part of #437, I'm going to close this for now. Please feel free to reach out to us if you have further questions/comments.

**Comment by tiwarivikash** [comment]
I have added IP route very specific to downstream system. Traffic going to downstream system only would be using ENI. Rest traffic would still use primary interface.
