### ISSUE TITLE
Logging driver options

### ISSUE THREAD

**Issue by cultureulterior** [aws/amazon-ecs-agent#123]
I'd like the ability to set the syslog tag, facility, etc... for the new docker logging options:

https://github.com/docker/docker/blob/609e7b0a55d4082fce40eabae3a06ca57c188ba5/docs/reference/run.md#logging-drivers---log-driver

**Comment by nletourneau** [comment]
:+1:

**Comment by edevil** [comment]
+1

**Comment by mmontagna** [comment]
+1

**Comment by cancan101** [comment]
+1

**Comment by radenui** [comment]
+1

**Comment by johnbona** [comment]
:+1:

**Comment by darend** [comment]
:+1:

**Comment by bcwp** [comment]
+1

**Comment by stormcat24** [comment]
:+1:

**Comment by editnuki** [comment]
+1

**Comment by oli-g** [comment]
:+1: Yes please!

**Comment by oli-g** [comment]
I the meanwhile you can enable the syslog logging on the Docker daemon itself (that means globally).
If you're using the ECS optimized Amazon AMI, you can enable it at launch time with some userdata script like this one:

```
#!/bin/bash
cat <<EOF > /etc/sysconfig/docker
OPTIONS="--log-driver=syslog"
EOF
stop ecs
start ecs
```

Enabling it on a service basis would be convenient though, so I'm looking forward to it!

**Comment by edevil** [comment]
@oli-g That's good news. I thought you had to pass that option every time you ran a container.

**Comment by austin881** [comment]
+1 please!

The [logging drivers](https://docs.docker.com/reference/logging/overview/) added in Docker 1.6 and the logging driver options added in Docker 1.8 which will rotate your on-disk logs **are awesome**, I would love to see them in ECS.

Specifically I'd love to be able to use the option to have rollling/rollover logs with `--log-opt max-size=50m` in my ECS task definitions.

**Comment by ChrisRut** [comment]
+1

**Comment by ChrisRut** [comment]
Unfortunately @oli-g 's solution (of setting the global `--log-driver`) won't work for me because I want to use a [sumologic collector container](https://www.sumologic.com/2015/09/09/update-on-logging-with-docker/)  to collect my docker logs and this requires setting: `--log-driver syslog --log-opt syslog-address=tcp://localhost:514`, except when I do that (by modifying */etc/sysconfig/docker*) the ECS agent fails to start:
```
2015-09-17T01:17:46Z [INFO] Starting Amazon EC2 Container Service Agent
2015-09-17T01:17:47Z [ERROR] could not start Agent: API error (500): Cannot start container f6862f2477d897b7a37824f45cb338b5f8060d3965b35e34f6d5bbe46fbb21c0: Failed to initialize logging driver: dial tcp 127.0.0.1:514: connection refused
```
:chicken: :egg:

**Comment by tomstockton** [comment]
+1 :+1:

**Comment by dnorth98** [comment]
+1.  We're using logspout on all of our ECS instances now to grab the logs and send to papertrail but I'd LOVE to be able to use the new docker logging system and eliminate the extra container needed.

**Comment by pjcliche** [comment]
+1

**Comment by mdedetrich** [comment]
+1

**Comment by jessecollier** [comment]
+1

**Comment by carlyle** [comment]
+1

**Comment by jessecollier** [comment]
Hi All,

I decided to make the change myself with Environment variable configuration since Amazon has no way to do so via task definition now.

To change log driver add environment variable like:
```
LOG_DRIVER=syslog
```

If you want to add 1 or more log options (see docker docs for more details on options) just create an environment variable that is prefixed by `LOG_CONFIG` ie `LOG_CONFIG_1`. Here is an example:

```
LOG_CONFIG_1="syslog-address=udp://127.0.0.1:514"
LOG_CONFIG_2="syslog-address=unix:///var/log/file.log"
```

In order to use this, you will need to follow the readme and build the image yourself. I'm currently hosting this already built on `jessecollier/amazon-ecs-agent:add-log-config` however don't trust me, you might want to build your own :)

Here's the diff:
https://github.com/aws/amazon-ecs-agent/compare/master...jessecollier:add-log-config

Here's the docker hub repo:
https://hub.docker.com/r/jessecollier/amazon-ecs-agent/

**Comment by samuelkarp** [comment]
Logging driver options are now available in ECS using the 1.5.0 version of the Agent.  You should now be able to specify a logging driver and logging options in your task definitions in the ECS console.  With the 1.5.0 Agent, you can use the `json-file`, `syslog`, `fluentd`, `journald`, and `gelf` logging drivers.

**Comment by chenliu0831** [comment]
@samuelkarp Is there an easy way to setup TLS with the syslog log options in ECS? Thanks.

**Comment by hridyeshpant** [comment]
@samuelkarp 
is there any was we pass --log-opt and  --log-driver parameter in ecs task definition. 
currently i am using below command as part of docker run and wondering is there is any way to pass these parameter from task definition?
docker run --log-driver=fluentd --log-opt fluentd-address=myhost.local:24224

**Comment by hridyeshpant** [comment]
i could see the logConfiguration option for specify the log-driver option in Task Definition Parameters 
,but is there way we can pass --log-opt fluentd-address from task definition?

**Comment by hridyeshpant** [comment]
got the solution, please ignore my previous query.
 logConfiguration: {
                    logDriver: "fluentd",
                    options: { :"fluentd-address"=> "<host_address>:24224",:"fluentd-tag"=> "docker.{{.ID}}" }

                },

**Comment by Seraf** [comment]
Hello,

Is there a support of `awslog` driver ? I mean, sending all logs directly to AWS Cloudwatch logs without using syslog ?

**Comment by dannymcpherson** [comment]
I agree, @Seraf.

@samuelkarp - 
When will there by support for the [awslogs](https://docs.docker.com/engine/admin/logging/awslogs/) driver ?
