### ISSUE TITLE
Provide access to ECS agent logs in Fargate

### ISSUE THREAD

**Issue by kastork** [aws/amazon-ecs-agent#1233]
### Summary

Can't tell why ECS is deregistering container

### Description

Containers silently get deregistered

### Request

Please provide a way to get access to the ECS agent logs in the Fargate launch type.

**Comment by adnxn** [comment]
Hi @kastork, I would suggest using the [describe tasks api](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-tasks.html) to get more detailed information about tasks. Additionally, thanks for bringing up this feature request and we will relay this to the service team as a request for Fargate.



Otherwise, this repo is mainly for issues directly related the ECS agent. We suggest reaching out to [AWS Support via forums](https://forums.aws.amazon.com/index.jspa) or getting in touch with [AWS support](https://console.aws.amazon.com/support/home) for best practices when working with Fargate. I am closing this issue for now. If you run into any ECS agent problems, feel free to create issues in this repository.
