### ISSUE TITLE
Support container health check from cloudformation

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1297]
### Summary

ECS has added support for Docker Health Check, but it's not available in CludFormation yet.

**Comment by thijsdev** [comment]
+1

**Comment by dsouzajude** [comment]
+1

**Comment by blontic** [comment]
+1 This is a must have feature please

**Comment by coltaa** [comment]
+1

**Comment by coltaa** [comment]
+1

**Comment by thewire247** [comment]
+1

**Comment by achidlow** [comment]
Just +1 the report instead of the comments. Otherwise all you’re doing is generating spurious notifications for people watching this issue. Thanks.

**Comment by liam-lai** [comment]
+100000

**Comment by dsouzajude** [comment]
Can we expect a time frame when we can expect to have this support in CloudFormation? Since it's already supported by the APIs and in the AWS Console, i'm guessing it's just a matter of updating the YAML/JSON schema and adding some constraints to allow the HealthCheck feature.

The issue is that since we can't really update an existing TaskDefinition to add the healthcheck ourselves via CustomLambda resource, this becomes an issue and we're left with no other choice but to either drop this amazing health check feature or write the Custom Lambda to implement all the logic to create the TaskDefinition ourselves via the API and this is too much of a hassle to do compared to doing it in CloudFormation.

Anxiously waiting for this feature soon! Thanks!

**Comment by richardpen** [comment]
Thanks for the patience, the cloudformation support for HealthCheck has been released as documented [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html). Closing this issue.
