### ISSUE TITLE
Feature request: provide task metadata endpoint to tasks using `bridge` network mode

### ISSUE THREAD

**Issue by aidansteele** [aws/amazon-ecs-agent#1389]
The [task metadata endpoint docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint.html) state the following:

> This feature is enabled by default for tasks that use the `awsvpc` network mode and are launched on Amazon EC2 infrastructure running at least version 1.17.0 of the Amazon ECS container agent.

What's not immediately clear is that this functionality appears to *only* be supported for tasks using the `awsvpc` mode. It would be good if this functionality was also supported for tasks running in the default `bridge` mode. 

The metadata endpoint exposes a lot of information not available in the [container metadata file](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) - of interest to me specifically is being able to introspect the labels applied to the currently running task.

It's my understanding that the endpoint functionality currently works by identifying the source IP address of the request to determine what task is invoking it. I assume this can also work for bridge mode tasks, given the error message returned currently: 

> "Unable to get task arn from request: v2 handler: unable to associate '172.17.0.5' with task"

Even if this is not technically possible, maybe it could employ the same mechanism as task credentials uses - passing in a unique token as an environment variable and appending it to the query string.

Thoughts?

**Comment by haikuoliu** [comment]
Hi @aidansteele, the task metadata endpoint is only designed for `awsvpc` mode because the container metadata feature isn't available to the `awsvpc` mode containers. And there is also security reasons we don't want to enable this for the container in `bridge` mode. But for your use case, I think it can be resolved by adding the missing information into the metadata file. I will mark this as a feature request and keep you updated.

Thanks,
Haikuo

**Comment by fenxiong** [comment]
Hi @aidansteele ,
Agent 1.21.0 has been released, in which we release v3 metadata endpoint that provides the same endpoints as the existing metadata endpoints, but available for host, bridge and awsvpc network mode. You can see the documentation [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html). Resolving the issue since i think this address your use case.

Thanks,
Feng

**Comment by aidansteele** [comment]
@fenxiong This is fantastic news, thank you very much for adding this functionality!
