### ISSUE TITLE
ECS-Docker consumption of anomalous RAM

### ISSUE THREAD

**Issue by davispalomino** [aws/amazon-ecs-agent#1399]
Currently we use ECS and we have the problem in the containers because they consume too much "cache page" which is not released quickly and efficiently, the "docker stats" command is the sum of "cache page" + "processes", entering the container we see few processes then we assume that all the rest is the "cache page", that is reflected in all the regions causing an anomalous autoscaling.

I'll look forward for your answer.

**Comment by haikuoliu** [comment]
Hi @bitvulnerado,

Agent has no control on how container uses/releases memory, you may need to find out a way to release those "cache page". However, please let us know if you believe the autoscaling is because Agent reports the wrong memory, like you find the memory usage of container is very small and an autoscaling is happening in your cluster.

Thanks,
Haikuo

**Comment by yunhee-l** [comment]
I'm closing this issue as we haven't heard back from you in a while. Please feel free to reopen this issue/add additional comments
