### ISSUE TITLE
ECS agent does not restart failed daemon task until container removed

### ISSUE THREAD

**Issue by arminc** [aws/amazon-ecs-agent#1460]
### Summary
We use ECS daemon service to start a docker container on all the EC2 machines. The daemon detects all the EC2 machines and starts running the docker containers on them. While all the docker containers are starting one or two fail (not importent but because many of them start we hit an api limit so the container can't fetch needed resources). Now ECS is showing these tasks as RUNNING while the logs shows that the docker container has crashed and looking on the EC2 instance the docker container is not running. ECS keeps telling the task is RUNNING until you remove the container from the EC2 instance, as soon as the container is removed ECS removes the task and starts a new one which then works fine.

The problem wil solve it self as long as your ECS agent is cleaning up containers ever X time, but it means your daemon container will not be available until X time has passed.

### Expected Behavior
Retry the docker as soon as it fails, maybe with a delay.

Is this expected or?

**Comment by fenxiong** [comment]
Hi @arminc ,
If a container crashes, the agent should know about that, and if it's an essential container, the agent will stop the task and send the stopping event to backend. So the fact that 'ECS keeps telling the task is RUNNING' is probably not the expected behavior. To let us dig into this issue, can you capture the logs through our [log collection tool](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and email me the logs at fenxiong at amazon dot com . Thanks.

**Comment by arminc** [comment]
I tried to reproduce the failure but I can not reproduce it since we updated to agent 1.18.0.
