### ISSUE TITLE
More feedback and information when a task was STOPPED

### ISSUE THREAD

**Issue by nexus49** [aws/amazon-ecs-agent#168]
I find it very hard to find out why a certain task was stopped. Even when looking at the ECS and docker logs it is still difficult to determine the reason. Since there can be a variety of reasons it would be great to see this either in the Task, or preferably in the events list. Possible reasons i'd love to see, but i'm sure there are a lot more candidates. Specifically the first two are sometimes very hard to distinguish.

- Container terminated by itself
- Load balancer health checks determined a task should be stopped
- Stopped because of ecs-deployment
- Stopped from UI/CLI
- Stopped because instance got terminated
- Used too much memory (I know this is already displayed in a stopped task)

Any advice on how i can see these things already would also be appreciated.

Cheers,
Bastian

**Comment by euank** [comment]
Right now there is indeed not an easy way to distinguish between most of the above.

To me, it sounds like the resolution to this would be to add a `stoppedReason` or `stoppedBy` field to the `stop-task` API so that any scheduler/caller can add a note, similar to the `startedBy` in `start-task`, about why a stop occurred. Does that sound correct to you?

Thanks,
Euan

**Comment by nexus49** [comment]
Thanks Euan, this sounds like it could accomplish what i was talking about above.

**Comment by samuelkarp** [comment]
We've added a [`stoppedReason`](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Task.html#ECS-Type-Task-stoppedReason) to the DescribeTasks API.  Please let us know if you need more information than this is providing.
