### ISSUE TITLE
Clean up dead containers after ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION

### ISSUE THREAD

**Issue by yumex93** [aws/amazon-ecs-agent#1684]
### Summary
Based on what I got from customers, so far after ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION, agent cleans up only the stopped tasks and docker images that are not being used by any tasks on your container instances. They also want agent to clean up containers in 'dead' status. 

Currently, customers' workaround is to run this command "#docker rm $(docker ps --all -q -f status=dead)" to manually remove the dead containers.

**Comment by sparrc** [comment]
While working on the solution to this I also noticed that we had a problem with cleaning up "dangling" docker images (`docker images -f dangling=true`). This was due to us trying to inspect images based on the name rather than the ID (which in the case of dangling images is `<none>`).

I have included a fix for this as well as part of #2015

**Comment by sparrc** [comment]
closed by #2015
