### ISSUE TITLE
Instances are not always properly removed from loadbalancers

### ISSUE THREAD

**Issue by nexus49** [aws/amazon-ecs-agent#173]
I observed a number of times that instances have not been removed from the respective load balancer. 

Usually when i was observing this issue, there was a startup problem in the container to be started that made the container terminate quickly after startup. 

Even though I had only one task running for a certain service, the loadbalancer had 3+ instances registered.

**Comment by euank** [comment]
We found a bug on our end that caused tasks that exited, rather than were stopped by the service scheduler, to sometimes not have their respective instances detached from the ELB.

A fix for this bug should be in all regions.

In the future, this sort of issue would also probably fit better and get more attention on the [forum](https://forums.aws.amazon.com/forum.jspa?forumID=187) since it's not an Agent issue.

Thanks for reporting the issue,
Euan
