### ISSUE TITLE
CpuShares is always enforced to a minimum of 2

### ISSUE THREAD

**Issue by xose** [aws/amazon-ecs-agent#1735]
### Summary

The ECS agent forces the Docker's CpuShares setting to always be set for every container it runs, even if it's empty on the task definition. This negatively affects performance of containers that use this information to configure their threading.

### Description

Programming languages may be "container-aware" and use cgroup information available inside a container, like memory limits or CPU shares, to make configuration decisions at runtime.

Java 10, 11 and recent builds of Java 8 (including Amazon Corretto) use Docker memory limits to configure the heap and CPU shares to set the amount of available CPUs for threading and garbage collection. See: https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/

When leaving the CPU shares unset on a task definition, the ECS agent will always set "2" as the value passed to Docker to create the container. This makes Java services running in the container think it has only 1 CPU available (shares <1024) and will configure its threading to use a maximum of 1 CPU, greatly affecting performance.

### Expected Behavior

When leaving CPU shares unset on a task definition, CpuShares is 0 and Java's `Runtime.getRuntime().availableProcessors()` returns the amount of CPUs of the host.

### Observed Behavior

When leaving CPU shares unset, CpuShares is 2 and `Runtime.getRuntime().availableProcessors()` is always 1.

### Example

A one-liner to quickly test with the `openjdk:8` or `openjdk:11` images:

```
sh -c 'echo "class Main { public static void main(String[] args) { System.out.println(Runtime.getRuntime().availableProcessors()); } }" > Main.java; javac Main.java; java Main'
```

**Comment by danielfariati** [comment]
We're having the exact same problem, but our tests seems to indicated that the cluster also have some influence in the behavior.

We realized that some of our tasks were returning only 1 CPU, when running the `Runtime.getRuntime().availableProcessors()`, but some were returning the correct amount, with the only difference being the name of the cluster they were running on (same task definition, vpc, subnet, security group...).
Funny enough, in our case, every cluster that had the word "cpu" in it, worked fine.

For instance, the cluster named _ecs-cluster-aws-webx_ returned the wrong amount of CPUs, but the cluster named _ecs-cluster-aws-webx-cpu_ returned the correct amount.
This behavior is consistent across other clusters in our account.

As a workaround, you can use the `-XX:ActiveProcessorCount` flag (or try to play with the cluster name, to see if that affects anything in your case).

**Comment by xose** [comment]
I've been digging, here is the algorithm Java uses for calculating the CPU count: [JDK sources](https://hg.openjdk.java.net/jdk-updates/jdk11u/file/4d390169521e/src/hotspot/os/linux/osContainer_linux.cpp#l499)

See [JDK-8146115](https://bugs.openjdk.java.net/browse/JDK-8146115) for discussion. The same algorithm was backported to Java 8 for release 191+.

There is a special case for 1024 shares on line 622. In fact setting CPU shares to 1024 will use all available CPUs.

**Comment by samuelkarp** [comment]
Hi @xose!

ECS uses the "cpu" parameter in the task definition for two purposes: 1) to control the CPU shares allocated to each container on your container instance in order to influence the relative priority of each container when there is CPU contention, and 2) to avoid over-subscribing or over-filling each container instance in your cluster.  It's the second use-case here that is relevant; the "cpu" parameter is used to control placement logic.  From the [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment): "You can determine the number of CPU units that are available per Amazon EC2 instance type by multiplying the number of vCPUs listed for that instance type on the Amazon EC2 Instances detail page by 1,024."

When you leave the "cpu" parameter blank or empty in your task definition, we interpret that to bet the same as zero, or roughly "burst-only" (no guaranteed CPU share during contention).  As @petderek mentioned, 2 is the minimum number of CPU shares that the Linux kernel supports, so we convert zero or one to two (see the [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment): "The minimum valid CPU share value that the Linux kernel allows is 2. [...] Null, zero, and CPU values of 1 are passed to Docker as two CPU shares."

ECS treats 1024 CPU shares as the value meaning "one whole vCPU".  Giving 1024 CPU shares to a container that specifies zero would mean that the container would have more priority than a container with an allocated amount less than 1024 (like 512), and would also mean that containers you've intended to have a guaranteed amount would have less when there is CPU contention.

The behavior that you're seeing with respect to CPU shares is intentional and we do not intend to change it at this time.  Our recommendation is to either allocate enough CPU shares in your task definition for your application, or to tune the JVM to ignore the settings that it reads from the cgroup.

Thanks,
Sam

**Comment by didibus** [comment]
If I understand correctly, ECS thinks that when I don't specify cpu limits, I'm doing the same as setting it to 0 (which really means minimum and will be set to 2)?

As opposed to assume that what I want is the default of 1024 used by Linux?
