### ISSUE TITLE
Containerdefinition container's name docs don't match with actual behavior

### ISSUE THREAD

**Issue by simonvanderveldt** [aws/amazon-ecs-agent#1863]
### Summary
The `name` as defined for a container in a containerdefinition isn't used directly.

### Description
The Containerdefinition docs describe the following (from https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-name):

> name
>The name of a container. If you are linking multiple containers together in a task definition, the name of one container can be entered in the links of another container to connect the containers. Up to 255 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed. This parameter maps to name in the Create a container section of the Docker Remote API and the --name option to docker run.
>
>Type: String
>
>Required: No

The important part here is:
> This parameter maps to name in the Create a container section of the Docker Remote API and the --name option to docker run

It doesn't map to these things though, since if I set `name: test` I won't get a container with name `test` but I'll get a container named `ecs-<service-name (or group name?>-<taskdef revision>-<container name (or task name?>-<somehash>`. Very far from `test` ;)

Why is this a problem: We want to run some containers that aren't managed by ECS and use volumes-from. For this it's significantly nicer if we can use a predictable container name. Right now we can't do that. We're aware that only a single container can exist with a specific name :)

### Expected Behavior
The container gets the name as defined in the container definition or the docs are updated.

### Observed Behavior
The container gets a derived/randomized name and the docs don't match

**Comment by samuelkarp** [comment]
Hi @simonvanderveldt, thanks for opening this.  Unfortunately, I don't think you're going to like my answer.  The `name` parameter in the Docker Remote API is used as a generated identifier and is one of the primary ways that the ECS agent gets a handle to control containers.  For that reason, it would be very challenging to switch to using only a user-defined name instead of the generated identifier that we use today.  The documentation is incorrect, and I'll follow up with our documentation team to get that corrected.

> We want to run some containers that aren't managed by ECS and use volumes-from.

For this kind of use-case, our recommendation would be to employ either [host-based volumes](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html) (where you specify a concrete path on the host) or to use a [Docker volume driver](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html).

**Comment by simonvanderveldt** [comment]
Hi @samuelkarp Thanks for the quick answer!

> Hi @simonvanderveldt, thanks for opening this. Unfortunately, I don't think you're going to like my answer. The `name` parameter in the Docker Remote API is used as a generated identifier and is one of the primary ways that the ECS agent gets a handle to control containers. For that reason, it would be very challenging to switch to using only a user-defined name instead of the generated identifier that we use today. The documentation is incorrect, and I'll follow up with our documentation team to get that corrected.

I'm totally OK with this answer :) Just wanted to make sure there wasn't an option somewhere that we overlooked that would make this work. If the docs can be updated to reflect reality that would be great.

We'll have a look at using volumes for this. Thanks again!
