### ISSUE TITLE
We should validate CNI plugin during agent initialization. Refactor agent_capability related tests.

### ISSUE THREAD

**Issue by suneyz** [aws/amazon-ecs-agent#1893]
### Summary

1. Lots of tests in [here](https://github.com/aws/amazon-ecs-agent/blob/master/agent/app/agent_capability_test.go) are linux specific, we should refactor them into agent_capability_unix_test file. Only keep common test for both linux and windows in agent_capability_test
2. Currently we don't verify CNI plugins binary on agent start up. Currently only when in AWSVPC mode, agent will invoke capabilities command in verifyCNIPluginsCapabilities [here](https://github.com/aws/amazon-ecs-agent/blob/master/agent/app/agent_unix.go#L151) We should always validate all the plugin binaries during agent start up (by invoking version command). Including
````
// a. ecs-eni
// b. ecs-bridge
// c. ecs-ipam
// d. aws-appmesh
````

**Comment by jy19** [comment]
part 1 has been done by meghna here: https://github.com/aws/amazon-ecs-agent/pull/2070

**Comment by jy19** [comment]
Discussed with Derek and Eric, part 2 is not needed at this time because plugin binaries are only required for AWSVPC mode and the presence of binaries are tested implicitly with our functional tests when agent starts up. 
See:
[eni](https://github.com/aws/amazon-ecs-agent/blob/master/agent/functional_tests/tests/functionaltests_unix_test.go#L465)
[app-mesh](https://github.com/aws/amazon-ecs-agent/blob/master/agent/functional_tests/tests/functionaltests_unix_test.go#L1478)
[ecs-bridge, ecs-ipam](https://github.com/aws/amazon-ecs-agent/blob/master/agent/functional_tests/tests/functionaltests_unix_test.go#L469)
