### ISSUE TITLE
How do you set the number of times a ECS task will try to be run by the agent?

### ISSUE THREAD

**Issue by bryantidd** [aws/amazon-ecs-agent#196]
Elasticbeanstalk instance provision failed (maybe a problem with your .ebextension files). The original message: [Instance: i-xxxxxxxx] Command failed on instance. Return code: 1 Output: (TRUNCATED)...ailed to start ECS task after retrying 2 times.' (RuntimeError)

**Comment by euank** [comment]
The ECS Agent does not retry a given task.
ECS does provide a Service Scheduler which will retry tasks that fail to launch and you can write your own using the ECS APIs as well.

It sounds like the actual issue you're running into is based on Elastic Beanstalk's behavior and you could probably get a better answer by asking on their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=86) or contacting support.

Best,
Euan

**Comment by drewbo** [comment]
@euank do you have any more information about using a Service Scheduler to retry a task that fails to launch? I'm seeing the occasional `CannotCreateContainerError` or similar errors which cause tasks not to launch and would like to be able to retry them (or better catch these failures; because the task record disappears after a while, querying for the exit code is unreliable)

**Comment by aaithal** [comment]
@drewbo You can find more details about using the service scheduler in the [ECS Service Scheduler documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html). More on scheduling tasks in general can be found [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduling_tasks.html). Please let us know if you continue running into this or if have more questions by creating a new issue.

Thanks,
Anirudh
