### ISSUE TITLE
Add push notifications for events through SNS.

### ISSUE THREAD

**Issue by bcwp** [aws/amazon-ecs-agent#199]
It seems like SNS would be a great fit to add push notifications for a service (so we could keep track of all state changes without having to query the API constantly).

This would make quite a few things (a simple form of service detection, logging/monitoring taskstate changes) a lot easier.

Is this on the internal roadmap? :)

**Comment by euank** [comment]
As a general rule, we don't talk about our future roadmap, sorry. I've made sure that this feature request is tracked internally though.

Since this isn't Agent-related or immediately actionable, I'm closing the issue, but feel free to open other such issues or comment with any additional information about this feature request.
Best,
Euan

**Comment by simplesteph** [comment]
Definitely needed as it could be a viable alternative to something like Consul.
