### ISSUE TITLE
ECS Container pull from public Docker Hub repo fails

### ISSUE THREAD

**Issue by bparker06** [aws/amazon-ecs-agent#2061]
### Summary

Trying to start a Fargate task using a public dockerhub image fails with:

```
CannotPullContainerError: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Description

Image tested: `bparker06/libretro-makebuild:latest`

I've verified all of the VPC / network / ACL / subnet information and everything appears to be correct. ~~Pulling a private docker image from ECR works fine.~~ Using an ECR image has only worked once for me, but not anymore. I've been trying for days to use either public dockerhub images or public/private ECR ones, without success.

The only time I've been able to get a container pull of any kind to succeed, is when I use the EC2 launch type, and even then, only when "default" network type is used instead of "awsvpc".

### Expected Behavior
There should be no problem to pull public images from Docker Hub.

### Observed Behavior
Image pull fails for unknown reason.

### Environment Details

us-east-1 region ECS task (Fargate type)

Container ID: f261a251-bc38-4ba0-bcad-3222df826df7

### Supporting Log Snippets

No logs (CloudWatch or otherwise) are produced.

There also seems to be a lot of missing / conflicting information on what exactly is required for awsvpc networking to function in Fargate tasks. Is the ECS agent required within every container run by Fargate? Or is it supposed to run on some central server (within the same VPC?)? Is DHCP required or is everything configured automatically like the `default` network type?

**Comment by petderek** [comment]
Hi @bparker06,

In order to communicate with network resources in Fargate (including pulling containers), the task will either need (a) a public IP address assigned or (b) a managed NAT + internet gateway. More info about this specific error  [ is available here.](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_cannot_pull_image.html)

>  Is the ECS agent required within every container run by Fargate? Or is it supposed to run on some central server (within the same VPC?)? 

If you use launch type Fargate, you don't need to configure or run the ECS agent in your containers or elsewhere.

> Is DHCP required or is everything configured automatically like the default network type?

If you aren't changing these options in the VPC, you shouldn't need to worry about this in your container configuration. It'll work automatically.

Please let me know if you have additional questions.
