### ISSUE TITLE
Can two tasks of the same Task Definition run on the same Container Instance?

### ISSUE THREAD

**Issue by jordi-chacon** [aws/amazon-ecs-agent#212]
Hi,

I was under the impression that two tasks of the same Task Definition could not be assigned to the same Container Instance. But this just happened to me. Two tasks of the same task definition got assigned to the same instance.

Is there any way to enforce that this doesn't happen?

**Comment by samuelkarp** [comment]
Yes, two tasks from the same task definition can be started on the same container instance as long as none of the consumed resources conflict.  If you want to prevent this behavior, the easiest way is to assign a host port in the task definition.  Assigning a host port will consume a resource (a port) on the host that is then unavailable when the second task needs to be placed.

**Comment by euank** [comment]
As Sam says, there's a way to do that now by overloading the port resource. I've made sure that the feature request of "task anti-affinity" is being tracked internally as well.

Since there's nothing actionable for the Agent here, I'm closing this issue.
In the future, it might also make sense to post this sort of service issue on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187).

Best,
Euan
