### ISSUE TITLE
Add more tolerance towards container-spawning errors

### ISSUE THREAD

**Issue by 2opremio** [aws/amazon-ecs-agent#222]
I had been hit by several spawning problems today and, although it was perfectly sensible to retry, the agent doesn't.
1. https://github.com/docker/docker/issues/14738 
   
   ```
   2015-10-07T20:12:45Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-west-1:376248598259:task/ebb93117-3fea-4b09-9217-1d25c5f4b356 dataproducer -> STOPPED, Exit 128, , Reason CannotStartContainerError: API error (404): Cannot start container 1fe08e80fd86d3cacdce78f62b00f39fb62aab65e7bfa0bf42004628598dc8c8: adding interface veth088ebac to bridge docker0 failed: could not find bridge docker0: no such network interface
   , Known Sent: NONE" change="ContainerChange: arn:aws:ecs:eu-west-1:376248598259:task/ebb93117-3fea-4b09-9217-1d25c5f4b356 dataproducer -> STOPPED, Exit 128, , Reason CannotStartContainerError: API error (404): Cannot start container 1fe08e80fd86d3cacdce78f62b00f39fb62aab65e7bfa0bf42004628598dc8c8: adding interface veth088ebac to bridge docker0 failed: could not find bridge docker0: no such network interface
   ```
   
   On top of that, the `ebb93117-3fea-4b09-9217-1d25c5f4b356` task didn't figure in the AWS console (stopped or not)
2. Resolution of `index.docker.io`
   
   ```
   2015-10-07T19:48:37Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:eu-west-1:376248598259:task/0adb2296-3edd-4d1c-855a-1050e77839bd httpserver -> STOPPED, Reason CannotPullContainerError: Get https://index.docker.io/v1/repositories/2opremio/weaveecsdemo/images: dial tcp: lookup index.docker.io: no such host, Known Sent: NONE" change="ContainerChange: arn:aws:ecs:eu-west-1:376248598259:task/0adb2296-3edd-4d1c-855a-1050e77839bd httpserver -> STOPPED, Reason CannotPullContainerError: Get https://index.docker.io/v1/repositories/2opremio/weaveecsdemo/images: dial tcp: lookup index.docker.io: no such host, Known Sent: NONE"
   ```

**Comment by hutchic** [comment]
I've started to get around this by setting up my own public docker repositories with more reliable repository hosts than hub.docker (ie quay.io has worked well)

**Comment by euank** [comment]
The Agent used to blindly retry all errors from Docker 3 times because of issues like this. That change didn't last long at all because it ultimately resulted in significant delays and excessive API calls (which Docker is unhappy with in some situations). This was especially true for `pull` related errors which were often not retriable.

If we do retry, it would be best to be able to classify Docker errors as retryable/transient. Traditionally, the `400` vs `500` error codes would help figure this out, but I don't think Docker uses them consistently enough for that to properly determine if an error is retriable. That leaves us with string parsing or working with Docker to allow messaging of 'retriability'.

The "perfectly sensible to retry" bit is obvious to us, but it's less obvious how it'd be obvious to the Agent without maintaining an exhaustive mapping. Obviously :smiley: 

This can be worked around at a higher level by your API client retrying, but it would be good to also add any improvements we can in the Agent.

Hopefully this adds a bit more context. I'm open to any ideas around how to best accomplish this.
Best,
Euan

**Comment by mkleint** [comment]
We manually run single tasks via java ecs client, sometimes in large quantities and keep getting various errors like that:

```
arn:aws:ecs:us-east-1:960714566901:task/097e9c8f-ef0a-4661-bda0-32843fda0f33 failure: Essential container in task exited:CannotCreateContainerError: API error (500): Error running deviceResume dm_task_run failed

arn:aws:ecs:us-east-1:960714566901:task/7622662e-4017-41d7-aedc-35bdb3e94979 failure: Essential container in task exited:CannotPullContainerError: failed to register layer: devicemapper: Error running deviceResume dm_task_run failed

arn:aws:ecs:us-east-1:960714566901:task/4bb4ee27-be99-42b7-bb91-45da063fc6ca failure: Essential container in task exited:CannotStartContainerError: API error (404): open /dev/mapper/docker-202:1-263198-282dc9a60278168022196657c911b192b572794eab218a6a5119c9b701dc9bff: no such file or directory
```

Because they fail randomly in the process of starting up (the initial RunTask call succeeds), we are forced to keep checking with ECS to see if the task actually turned into running state.


using the latest AMI (amzn-ami-2016.03.c-amazon-ecs-optimized)

**Comment by brentp** [comment]
Hi, I am seeing this:
```
Container message CannotCreateContainerError: API error (500): devicemapper: Error running deviceResume dm_task_run failed
```

intermittently (about 1 in 50), from jobs submitted via batch. Is there a way to debug this or to retry?

**Comment by mschroering** [comment]
@brentp I'm seeing the exact same behavior with AWS Batch when submitting a large number of jobs at the same time.   I was wondering if it's related to this:

https://github.com/docker/docker/issues/23418

which made it into Docker 1.13.0

**Comment by cjbottaro** [comment]
I recently got this for container exit reason:
```
CannotPullContainerError: failed to register layer: devicemapper: Error running deviceResume dm_task_run failed
```
I'm using an ECR registry and the amount of tasks I'm scheduling in ECS is tiny (like 20 per day).

This is worrisome when I think about using ECS for a real production workload... :/

**Comment by mkleint** [comment]
we've switched from devicemapper to overlay and the stability improved for us significantly.

**Comment by cjbottaro** [comment]
> we've switched from devicemapper to overlay and the stability improved for us significantly.
Can you elaborate a bit on that?  Or point me to some documentation for how to do it?  Thanks!

**Comment by nmeyerhans** [comment]
@cjbottaro The `devicemapper: Error running deviceResume dm_task_run failed` was fixed in a recent update to docker in Amazon Linux. Assuming you're on that platform, be sure you're running `docker-1.12.6-2.19.amzn1.x86_64` (which is bundled with the 2016.09.g ECS Optimized AMI) and this devicemapper stability issue should be resolved.

**Comment by cjbottaro** [comment]
@nmeyerhans Ahh, thank you.  Indeed, half my cluster was running `f` instead of `g`.

**Comment by mkleint** [comment]
> > we've switched from devicemapper to overlay and the stability improved for us significantly.
> Can you elaborate a bit on that? Or point me to some documentation for how to do it? Thanks!
> 

our cloud-init file (we running via terraform and have extra volume for docker.
```
bootcmd:
 - modprobe overlay
 - [ cloud-init-per, once, enable_overlay, sh, -xc, "echo 'DOCKER_STORAGE_OPTIONS=\"--storage-driver overlay\"' > /etc/sysconfig/docker-storage" ]
 - [ cloud-init-per, once, docker_fs_1, pvcreate, -y, /dev/xvdcz ]
 - [ cloud-init-per, once, docker_fs_2, vgcreate, docker, /dev/xvdcz ]
 - [ cloud-init-per, once, docker_fs_3, lvcreate, -n, docker-pool, -l, 100%FREE, docker]
 - [ cloud-init-per, once, docker_fs_4, mkfs.ext4, /dev/mapper/docker-docker--pool ]
 - [ cloud-init-per, once, docker_fs_5, sh, -xc, "echo '/dev/mapper/docker-docker--pool /var/lib/docker ext4 defaults 0 0' >> /etc/fstab" ]
 - [ cloud-init-per, once, docker_fs_6, mount, /var/lib/docker ]
```

**Comment by cjbottaro** [comment]
@mkleint Cool, thanks.  I ended up doing something similar:  https://github.com/aws/amazon-ecs-agent/issues/746#issuecomment-290881349

**Comment by aaithal** [comment]
Hello everyone,

Does the recent announcement of [Circuit Breaking Logic for the Amazon ECS Service Scheduler](https://aws.amazon.com/about-aws/whats-new/2017/12/circuit-breaking-logic-for-the-amazon-ecs-service-scheduler/) address your use-case to some extent? We are tracking ECS Agent health, which should address the instance side of things in #483. So, I'm closing this for now in favor of that. Feel free to reach out to us by creating new issues or updating existing ones if your use-case has not been captured or in case of additional questions/comments.

Thanks,
Anirudh
