### ISSUE TITLE
Is StartTelemetrySession an API of ECS?

### ISSUE THREAD

**Issue by shinningstar** [aws/amazon-ecs-agent#224]
Hi,

I am studying the source code of ecs agent. I found that there is an API action called "ecs:StartTelemetrySession" in the AmazonEC2ContainerServiceforEC2Role IAM policy but it does not appear in ECS api doc at http://docs.aws.amazon.com/AmazonECS/latest/APIReference/Welcome.html.
There is another API action in the policy file "ecs:Poll" has the similar situation.

Is it an ECS API? If it is an private api just for agent to use, how does the agent call it? I found something like a request definition in https://github.com/aws/amazon-ecs-agent/blob/master/agent/tcs/model/api/api-2.json#L48. Could someone help brief the function of this json file? What is the message mechanism between agent and ECS on publishing metrics?

"StartTelemetrySession":{
      "name":"StartTelemetrySession",
      "http":{
        "method":"POST",
        "requestUri":"/"
      },

Thank you so much!

**Comment by euank** [comment]
This is indeed an ECS API intended only for the Agent's use.
This API uses a different protocol (despite the json file saying `protocol: json`) so including it in the AWS CLI or other SDKs would not be useful because it could not be called by them.

The Agent calls it via the `tcs` package [here](https://github.com/aws/amazon-ecs-agent/blob/v1.5.0/agent/tcs/client/client_types.go#L43) over the client/protocol defined in the `wsclient` package [here](https://github.com/aws/amazon-ecs-agent/blob/v1.5.0/agent/wsclient/client.go#L14).
To make matters slightly more confusing (sorry!) the `StartTelemetrySession` operation is inferred in some cases when not set, and I think the Agent isn't actually explicitly making that request type anywhere and is instead letting it be inferred service-side.

It is not well documented beyond the comments and code in those packages.

If you'd like to explain what specifically you're looking for here I might be able to provide a more clear/concise answer.

Hopefully that covers all your questions, though feel free to ask more or for clarification.
Best,
Euan

**Comment by shinningstar** [comment]
Hi euank,

Thank you so much for your answer! 

Actually I am confused by the json file I mentioned above. Just like you said the json file says it use json as protocol, but it seems not.  What is the usage of this json file? 

Also, I hope to learn the usage of ecs:Poll. If I am right, the agent starts a secure session with the server first, and then the server dispatches payload message to the agent periodically, along with heartbeat message.  So why does the agent poll server? I haven't found the related code yet.

Thanks for your help again.

**Comment by euank** [comment]
The json file you linked is used to generate the [structs](https://github.com/aws/amazon-ecs-agent/blob/v1.5.0/agent/tcs/model/ecstcs/api.go#L260) that are used as part of that websocket client. The generation code is done via the generation code in [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go).
The point of the file is so that if we update the API, we don't have to hand-code the changes in the Go structs as well.

The code used to generate those structs understands the protocol `json` in terms of generation and so we say that's the protocol to get types generated as we want.

The word `Poll` is not really accurate for what's happening. There isn't polling, the `Poll` api is a misnomer for it opening a websocket connection (being called `StartSession` in the `acs` subfolder, which corresponds to the `ecs:Poll` api). The websocket connection is periodically re-established, but it's not what would normally be called polling.

Your understanding overall sounds correct; hopefully it's just that mis-naming that's confusing you.
Again, feel free to ask for further clarification :smiley:,
Euan

**Comment by euank** [comment]
Hopefully I've answered all your questions adequately, but feel free to reopen or create a new issue if you have further questions.
Cheers,
Euan
