### ISSUE TITLE
Cannot get volumesFrom to work

### ISSUE THREAD

**Issue by yoanisgil** [aws/amazon-ecs-agent#226]
I've a Dockerrun.aws.json file whic looks like this:

```json
{
  "AWSEBDockerrunVersion": 2,
  "volumes": [
    {
        "name": "postgresql_data",
        "host": {}
    }
  ],
  "containerDefinitions": [
    {
      "name": "postgresql",
      "image": "mdillon/postgis:9.3",
      "essential": true,
      "memory": 396,
      "mountPoints": [],
      "volumesFrom": [
        {
            "sourceContainer": "postgresql-data"
        }
      ]
    },
    {
      "name": "coride-service",
      "image": "rideeze/coride-service",
      "essential": true,
      "memory": 496,
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 80
        }
      ],
      "links": [
        "postgresql"
      ],
      "mountPoints": []
    },
    {
        "name": "postgresql-data",
        "image": "rideeze/coride-psql-data",
        "essential": false,
        "memory": 16,
        "mountPoints": [
            {
                "sourceVolume": "postgresql_data",
                "containerPath": "/var/lib/postgresql/data"
            }
        ],
        "command": ["tail -f /dev/null"]
    }
  ]
}
```

but I cannot get the postgresql-data container to stay running so volumes it's volumes can be used by the postgresql volume. I would appreciate any advice.

Bests,

Yoanis.

**Comment by euank** [comment]
Because the data container is marked as `essential: false`, it shouldn't matter that it does not stay running. Volumes can be used when a container is created, but not running, just fine. In fact, the above task definition appeared to work for me (I verified it stayed up for a minute and `curl $host:80` gave me some json output).

The reason the `postgresql-data` container isn't running is because the command should be `["tail", "-f", "/dev/null"]`, but again, that shouldn't really matter.

A couple other things to note:
* You probably don't need the data container at all. If you move the `mountPoints` block from it in place of the `volumesFrom` directive, things will be basically the same.
* You're using an "empty volume" which only persists for the lifetime of this task. If you would like your data to persist between instantiations of this task or between multiple tasks, you'll want to specify a path on the host or use some other mechanism. If the "empty volume" isn't mounted by multiple containers in the task, it's effectively the same as not having any volume mounts at all typically. The empty volume is meant for sharing data within a single task, not between tasks.

If the above doesn't help, a bit more information would be useful:
* What error are you seeing if you run `describe-tasks` on a failed instance of it?
* Can you post the Agent logs around the time it fails?

Best,
Euan

**Comment by euank** [comment]
Since I don't think there's anything actionable here without more information, I'm closing this for now.
Please do reopen if you have more information or questions!
