### ISSUE TITLE
Error response from daemon when using windows memory unbounded workaround

### ISSUE THREAD

**Issue by McDoit** [aws/amazon-ecs-agent#2344]
### Summary

Running with `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` returns `CannotCreateContainerError: Error response from daemon: invalid option: Windows does not support MemoryReservation`

### Description

When trying to run `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` on our windows cluster with agent version 1.34.0 (latest?) i get the following error from the ECS console:

`CannotCreateContainerError: Error response from daemon: invalid option: Windows does not support MemoryReservation`

Is this fixed yet, or is this related issue closed anyway?
https://github.com/aws/amazon-ecs-agent/issues/1144

### Expected Behavior

Able to start a task with containers running only memory reserved

### Observed Behavior

Not able to start task

### Environment Details
Windows Server 2019 ECS AMI
Agent version 1.34.0
Docker version 19.03.5

**Comment by fenxiong** [comment]
Hi @McDoit ,
This is supposed to be fixed in the agent version you use. What do you mean by `Running with ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND`? Did you set it to true or false? If you set it to true, and don't specify the `Memory` field in the container definition, you shouldn't be getting this error.

**Comment by McDoit** [comment]
Yeah i did set it to true, but i also set both `MemoryReservation `and `Memory` , isnt that combination supported?

**Comment by fenxiong** [comment]
As per documented in the README for `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` - `To run a memory unbounded task, omit the memory hard limit and set any memory reservation, it will be ignored.` So we only skip setting the MemoryReservation field when running container (which is necessary to avoid the error you have since Docker on Windows doesn't support this field) if you don't specify a value for the `Memory` field. If you have a value for `Memory`, the `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` config doesn't take effect.

**Comment by McDoit** [comment]
Ok, thank you for the clarification
I added the `Memory` field to future proof the config a bit, in the case of working  `Memory`/`MemoryReservation` on Windows in the future
But then i will just remove it, thank you again
