### ISSUE TITLE
Volume driver support

### ISSUE THREAD

**Issue by robhaswell** [aws/amazon-ecs-agent#236]
The VolumeDriver parameter is now part of the [Docker Remote API 1.21](https://github.com/docker/docker/blob/448398c2a8a41b6589dd7deb59fdc889e78db223/docs/reference/api/docker_remote_api_v1.21.md). It would be great to get this included in the ECS task definition. This would allow me to access more storage options for my Docker containers, for example, accessing EBS volumes through Flocker or using the Ceph RDB driver (http://www.sebastien-han.fr/blog/2015/08/17/getting-started-with-the-docker-rbd-volume-plugin/).

**Comment by wallnerryan** [comment]
@euank what is the delta to minimally support these changes? Would assume that the ecs-agent would recognize the the host volume doesnt need a ```sourcePath```, but rather could be just a name. Also the container definition could take a new ```volume driver``` flag. This would match parity with ```docker volume create --volume-driver=driver --name=vol_name``` for 1.9 and ```docker run --volume-driver=driver <name>:/path/```

**Comment by robhaswell** [comment]
Docker also has additional error conditions associated with volume drivers. Search your souls for if this is MVP.

**Comment by kapilt** [comment]
We're also very interested in this support

**Comment by ColinHebert** [comment]
Any news regarding the support of volume drivers?

**Comment by ferrantim** [comment]
+1  would love to see this.  Getting more and more requests.

**Comment by brianantonelli** [comment]
+1 this would be great

**Comment by analogrithems** [comment]
+1 this is holding up a lot of use cases and google compute already makes this available

**Comment by ferrantim** [comment]
@cbbarclay any update on when ECS will support Docker volume drivers?  Thanks!

**Comment by robhaswell** [comment]
I recently evaluated deploying some new infrastructure on ECS but this prevented me from doing so.

**Comment by p7k** [comment]
+100500

**Comment by ryansch** [comment]
It's a new record! 😉

**Comment by sebalas** [comment]
👍

**Comment by gservat** [comment]
+1 !!

**Comment by siimleetberg** [comment]
+1

**Comment by ebuildy** [comment]
Yeah! will be useful to make possible to use EFS shares via the plugin http://netshare.containx.io/

**Comment by ervinb** [comment]
+1

**Comment by joshhiggins22** [comment]
+1

**Comment by eric5102** [comment]
+1

**Comment by egafni** [comment]
+1

**Comment by ainagy** [comment]
+1

**Comment by RJSzynal** [comment]
+1. I want to use netshare.containx.io too

**Comment by ebirukov** [comment]
+1

**Comment by balopat** [comment]
+1

**Comment by JaimeVL** [comment]
+1. This will enable ECS to seamlessly support stateful applications, which is a big gap in my opinion.

**Comment by lrafagnin** [comment]
+1

**Comment by kislyuk** [comment]
+1

**Comment by cyrilchampier** [comment]
+1 for EFS

**Comment by tobowers** [comment]
👍 for stateful service support (it would be great to have EBS hook directly into ECS as well)

**Comment by Yaztromo** [comment]
+1

**Comment by daxroc** [comment]
+1 EFS/NFS

**Comment by daximus522** [comment]
+1

**Comment by bbl232** [comment]
This would definitely be really useful when combined with a plugin like https://github.com/ContainX/docker-volume-netshare to make use of EFS directly. It is so cumbersome to have to mount the EFS volume to the host ec2 instance first.

**Comment by frimik** [comment]
I've sort of coerced the agent into doing this, based on input you do in the ECS task definition...

https://github.com/frimik/amazon-ecs-agent/commit/14f9a2efc8bbf08c44fea0208ab32c2fc788ae4d#diff-e008975819a900a8494cf91881a8304aR450

The sad part is that due to **dockerd** requiring restart to pick up newly mounted filesystems (regardless if its NFS or EBS etc) - it doesn't actually bind mount the *correct* filesystem in the end - you end up with a bind-mounted empty folder from the host root disk instead of the EBS disk...

If you restart docker *after* mounting the file system it works ...

**Comment by Adrian-Sherwood** [comment]
+1

**Comment by gitrc** [comment]
Amazon, are you listening?

**Comment by mounemoi** [comment]
+1

**Comment by marcovzla** [comment]
+1

**Comment by myedibleenso** [comment]
+1

**Comment by kchilder** [comment]
At least wrap the nfs volume driver so we can use it with EFS!

**Comment by galindro** [comment]
@euank @samuelkarp @aaithal @richardpen 

This feature request was opened at Oct 26 2015. Almost 2 years have passed and nothing about it was discussed. IMHO, this is a little feature that could be easily be developed by AWS team.

Please, someone from AWS could give us an ETA or just something about if this feature is in the roadmap for this month, or this year?

**Comment by samuelkarp** [comment]
@galindro While we don't generally comment on our future roadmap (including ETA), I can shed a bit more light onto the concerns here.

We've generally been thinking about volume drivers in terms of application persistent storage.  There are a few different models where persistent storage can be used for applications:

* Shared storage, where each copy of your application sees the same files.  One of the more common technologies for this is NFS, and the Amazon EFS service provides a hosted version of NFS.  In terms of scheduling, it doesn't matter how many copies you would have as long as they could all see the same data.
* Pre-populated, independent storage.  This would encompass a situation where each copy of your application wants to see the same data-set at start, but does not need to share mutations.  Common use-cases for this involve things like read-only views or copy-on-write; Amazon EBS provides a hosted block storage service with volumes created from snapshots.  In terms of scheduling, it doesn't matter how many copies you have as long as they could all start from the same data.
* Persistent, restartable storage.  This would be a use-case akin to upgrading a traditional stateful application in-place, but with a container wrinkle added.  Amazon EBS provides a hosted block storage service where volumes can be attached and detached from instances.  In terms of scheduling, you'd only have one copy here with its own storage.  If you were to have multiple copies of the application, each would see separate data.
* Persistent, sharded storage.  This would be a use-case akin to the previous one, except that multiple replicas might each see different shards.  In terms of scheduling, we'd have to maintain a mapping of shard-to-application-copy to ensure that storage doesn't get lost or unused; complications would occur during deployments or during scale-out/scale-in.

Volume drivers could be paths to enabling all of these use-cases.  However, there are some challenges with volume drivers specifically:

* Many of the clustered volume drivers require all of your instances to be able to talk to each other and be configured together.  We'd need to figure out how to handle error conditions where this isn't the case, so that you have enough information in order to debug it.
* The volume drivers don't indicate to us what their scheduling requirements are: are we free to start as many copies as we want (desired count in a service), are we restricted to only running one, do we need to handle a persistent identity that gets passed in to a given container configuration, etc.

**Comment by frimik** [comment]
I just need "blocker" type of storage in the first place... With a few
extra options maybe. I can get around all of it with "magic" hints in the
definitions / the ECS ui. But for how long do we have to keep doing it that
way... :).

**Comment by robhaswell** [comment]
@samuelkarp I understand your concerns but I don't think they are great enough to prevent this feature from being considered for work.

> * Many of the clustered volume drivers require all of your instances to be able to talk to each other and be configured together.

This is true, however for the simplest (and most obvious?) use-case of using the EBS volume driver, this is not a concern.

> The volume drivers don't indicate to us what their scheduling requirements are

They do, they pass back an error (I think, it's been two years since I looked at this) which then indicates to ECS that the container is unschedulable and requires intervention by an administrator. This is how Kubernetes handles the problem. The solution is probably for the user to not use a storage provider with inflexible scheduling requirements - again, EBS does not have this problem (probably... is the 26 volume-per-instance limit still in place?).

I understand the desire to not expose users to features that might break as a general concept. Mobile phones, cable boxes, Echo-devices... these are all things which should not come with sharp edges. AWS, however, is a smart platform for smart people. Infrastructure is hard. I think AWS should give its users the benefit of the doubt and allow them enough rope to hang themselves. To that I mean, this feature has caveats for sure but the benefits outweigh the negatives, because right now the alternative is to move your workload to a scheduler which does support storage services... like.. GKE :(

**Comment by galindro** [comment]
In the meanwhile, I think that IT admins/Devops could use my workarround considering that almost all storage driver for Docker exposes the volumes in a way that they could be used by `docker run` just referring them by name, like this:

```bash
docker run -v myvolume:/foo -w /foo -i -t ubuntu bash
```

The only problem that this aproach have, IMHO, is that you need to create a volume first with the `docker volume create` command.

I've tested with Docker Couldstor, but I think that it would work with RexRay.

@frimik I think that [blocker](https://github.com/monder/blocker) is a little old solution. Try [Docker Couldstor](https://docs.docker.com/docker-for-aws/persistent-data-volumes/). It is a better solution.

**Comment by rclark** [comment]
@samuelkarp I want to point out another use-case that I'm not sure is covered by your bullets above. In our applications, data is persisted elsewhere (S3) and updated regularly by separate systems. Our ECS containers need to start from the current state of that data, perform their processing, and write the output elsewhere.

- the data's starting state varies from container to container
- the data on disk that the container generates is ephemeral

In this case the most important missing features are accounting for disk space during scheduling, and limiting disk usage to some reserved amount.

**Comment by Stavanger75** [comment]
+1

**Comment by dsnopek** [comment]
Volume drivers are a pretty critical feature of Docker - it seems weird not to allow us to use them?

**Comment by CameronGo** [comment]
@samuelkarp while I understand there is some appetite for broader and more complex volume driver support, does it seem likely that ECS would allow the mounting of an EBS volume and/or an EFS data store as part of the Task Definition at some point in the near future?  My guess is that addresses the vast majority of the use cases right?

**Comment by gitrc** [comment]
@samuelkarp I know Amazon position is to not disclose the roadmap and whatnot but can you please give us an update on this much needed functionality?  I saw the announcement for ENI to container (awsvpc) which solves the networking equivalent of the volume driver ask in this issue.  The ability to associate an EBS volume would go a long way.  Glad to see ECS feature development is active.

**Comment by csumpter** [comment]
+1

**Comment by kislyuk** [comment]
:+1: this really puts a damper on our use of AWS Batch (which uses ECS).

**Comment by wdalmut** [comment]
:+1:

**Comment by DaveWK** [comment]
This really makes working with efs and ecs difficult. The fact that overlay2 is not supported with nfs4 (due to d_type) in docker means you can't simply change your docker graph location for docker daemon. I had hoped the alternative would be using a log driver, but this is a mess if I can't make unique volumes per task.

Alternatively if I could even specify a dynamic value in my volume bind (so each task had it's own "writer" volume) it would make efs and ecs much more usable.

**Comment by yunhee-l** [comment]
We have launched support for Docker volume driver: https://aws.amazon.com/about-aws/whats-new/2018/08/amazon-ecs-now-supports-docker-volume-and-volume-plugins/

This feature is available through amzn-ami-2018.03.d-amazon-ecs-optimized AMI, or from agent [v1.20.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.20.1)

You can find the developer guide here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html

Please let us know if you have any questions.

**Comment by wmitsuda** [comment]
Does this not work with Cloudformation yet?

**Comment by yunhee-l** [comment]
CFN support for this feature isn't available yet, but we are working with CFN team to enable it.

**Comment by analogrithems** [comment]
@yunhee-l any chance you could provide a task def example or tutorial for using docker volume driver for efs or ebs?  The links you provided are just marketing links and the developer guide just states it's available but no details on how.

**Comment by CameronGo** [comment]
@analogrithems - i spent some time working with it this evening and was able to get a persistent EBS volume attached to a task launched from ECS.  I'm no expert at this point, but here are the high points:

1. Update your ecs agent to the latest version (ours runs on Ubuntu in a container so just required a docker pull and then stop/remove/start the agent again
2. Install a volume plugin driver.  There maybe others or better out there, but I did this by running
```
docker plugin install rexray/ebs
```
3. Make sure the EC2 instance's role has sufficient access to create/list/update EBS volumes.  (In my test env I gave it temp full EC2 access)
4. At this point, manually running a container from docker CLI should let you run and connect to a newly provisioned EBS vol:
```
docker run -ti --volume-driver=rexray/ebs -v test:/test busybox
```
5. At this point a Task Definition with a volume configured should work.  An excerpt from my Task Def volumes section looks like this:
```
  "volumes": [
    {
      "name": "test",
      "host": null,
      "dockerVolumeConfiguration": {
        "autoprovision": false,
        "labels": null,
        "scope": "shared",
        "driver": "rexray/ebs",
        "driverOpts": null
      }
    }
  ]
```
