### ISSUE TITLE
EFS Mounting in Fargate gets an CannotStartContainerError: ResourceInitializationError

### ISSUE THREAD

**Issue by Alonreznik** [aws/amazon-ecs-agent#2442]
Hi There.
We're trying to move forwards our workloads in ECS to Fargate, using the EFS mounting as some part of our internal process. However, when we're using the mounting access point with the new EFS feature, were getting the next error:

```
CannotStartContainerError: ResourceInitializationError: failed to create new container runtime task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58
```

Our architecture uses NAT gateway as an endpoint out to the internet from our ec2-servers, using some specific subnets. The EFS is connected to these subnets, and when using the EC2 servers, there is full access to the tasks to the EFS. However, when using Fargate, this is the error we're getting.

When I'm going into the ec2 server that run the agent, I cant mount the efs using the next command:
`mount -t efs -o tls,accesspoint=fsap-*********** fs-21****** /mnt/exriverback2`

Please help.

Thanks!

Alon

**Comment by petderek** [comment]
That seems unpleasant, sorry you’re having trouble here. Could you send your task definition and / or the task id of a failed task to us? ecs-agent-external at amazon dot com. We will chase this down on our end and see what is happening. 

One thing you can check on your end: the security group that you bind to a running fargate task needs to be compatible with the security group bound to your EFS mount target.

**Comment by Alonreznik** [comment]
Hi @petderek,

Thanks!
I've sent the message as expected.
Checked also my security groups and IP addresses in Fargate - both security groups and IP addresses should be bound with EFS connecting through access points.

Alon

**Comment by petderek** [comment]
We're actively fixing this on our end; I'll circle back here when I have more to share.

**Comment by Alonreznik** [comment]
Hi. 
Any update?

**Comment by joeanthonydc** [comment]
Working through this issue as well. Any updates?

**Comment by CharlyF** [comment]
Same issue encountered here - with Fargate 1.3.0 it runs fine, with 1.4.0 I get the error.
I do not mount anything however.
<img width="1197" alt="Image 2020-05-21 at 10 58 18 AM" src="https://user-images.githubusercontent.com/7433560/82572181-03b46900-9b52-11ea-83a4-30dce58afc17.png">

**Comment by petderek** [comment]
You may see this issue when using the 'initProcessEnabled' flag on 1.4.0. We're still working on updates to solve this issue.

**Comment by petderek** [comment]
> CannotStartContainerError: ResourceInitializationError: failed to create new container runtime task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or direct...

@joeanthonydc This seems like a separate issue.  When I get an error that looks like "starting container process caused.." it typically means that I've done something wrong with the entrypoint/cmd. What I'd recommend:

* check the contents of your container. make sure that your run.sh is present
* check the command locally. try running it with `docker run $imageName "./bin/run.sh"`
* try using an absolute path instead of the relative path with the dot `.` character

If you are still seeing issues, feel free to send us information (a failed task id and task definition) to ecs-agent-external@amazon.com and we can help.

**Comment by CharlyF** [comment]
@petderek - Not that I know of.
I rebuilt my container out of curiosity, the code is [here](https://github.com/clamoriniere/dogstatdclienttest) (I just changed the unix socket to `localhost:8125`). As I thought it could be due to the client trying to create a socket or something.
I still get:
```
Status reason | CannotStartContainerError: ResourceInitializationError: container rootfs: unable to initialize /etc/mtab: symlink /proc/mounts /var/lib/two/volumes/c17603f2a59f416889d805448fc0509cstatsd/rootfs/etc/mtab: no such file or directory
-- | --
``` 
I read the doc for `initProcessEnabled` and the container is only running the process built by the main, so no init of some sort.

For the sake of debugging, I build a binary that runs this:
```go
package main
import (
	"log"
	"time"
)
func main() {
	for {
		time.Sleep(200 * time.Millisecond)
		log.Printf("Time is: %v", time.Now())
	}
}
```
And I still get the same error.

**Comment by mssrivas** [comment]
A fix for this issue was pushed out recently in Fargate PV 1.4
Please verify and re-open if you have further questions

**Comment by Inugan** [comment]
Hi Team,
I have been facing the same error. I was hosting the Sonarqube on ECS FARGATE. 

**Status reason | CannotStartContainerError: ResourceInitializationError: failed to create new container runtime task: OCI runtime create failed: container_linux.go:**370**: starting container process caused: exec: "/opt/sonarqube/bin/run.sh": stat /opt/sonarqube/bin/run.sh...no such file or direct...**
While in my dockerfile everything is in place.. And also the absolute path is also correct. 

This error is getting triggered while integrating ECS Fargate with EFS.

Without EFS, the cluster is working like a charm. Please help..
