### ISSUE TITLE
A container exits with zero exit code but with the "OutOfMemoryError: Container killed due to memory usage" status reason

### ISSUE THREAD

**Issue by sedovalx** [aws/amazon-ecs-agent#2467]
### Summary
A container exits with zero exit code but with the "OutOfMemoryError: Container killed due to memory usage" status reason. It does look inconsistent.

### Description
I have a ECS task that runs a bunch of containers. All of the containers run java apps inside
![image](https://user-images.githubusercontent.com/9218022/83401463-7bfe1280-a40d-11ea-8493-eb9cc4cd80aa.png)

The `main` container runs a Gradle build inside, the `init` and `watchdog` are aux containers. Very often I see that whatever exit code the main container has the status reason is "OutOfMemoryError: Container killed due to memory usage", even if it exists with zero exit code with no errors in the container's stdout/stderr. 
![image](https://user-images.githubusercontent.com/9218022/83401905-8076fb00-a40e-11ea-948f-ee88de2e30a4.png)

The container memory and cpu metrics for the whole its life:
![image](https://user-images.githubusercontent.com/9218022/83402110-d2b81c00-a40e-11ea-882f-564562f22752.png)

### Expected Behavior
The exit code and the status reason of the container should be consistent (or am I missing something?). I would expect an empty status reason with zero exit code, or exit code 137 and the OOM message.

### Observed Behavior
The exit code and the status reason are inconsistent.

**Comment by mythri-garaga** [comment]
Could you please provide version of agent and Docker are you running?

OOM event might not always result in exit 137.  OOM killer will select a process to kill when the container runs out of memory but the container can continue to run.

**Comment by sedovalx** [comment]
We use the latest ECS-Optimized AMI for our ECS cluster, I believe the ECS agent version depends on it. I don't really know how to extract the agent and docker versions from this info, the only hope it will answer you somehow. 

Sorry, I was ignorant about the exit codes of "container". Now I see that any process in the container's process tree may be killed by the OOM Killer and still, the main process may succeed. The question that left is what "OutOfMemoryError: Container killed due to memory usage" status reason means when the exit code of the main process is not 137? May I assume that it means that one of the subprocesses were killed during the container execution?

**Comment by mythri-garaga** [comment]
I am sorry I spoke too soon, “OutOfMemoryError: Container killed due to memory usage” error should be returning exit code 137. 
I was unable to repro this issue. It would be helpful if you can provide debug level agent logs around the time the error occurred in order. You can send this to ecs-agent-external at amazon.com

Please find agent logs under /var/log/ecs on your container instance.
For other details, 
Agent version - run  `curl -s http://localhost:51678/v1/metadata` 
Docker version - run `docker info`

**Comment by sedovalx** [comment]
Here is comes
![image](https://user-images.githubusercontent.com/9218022/84143749-c6ac0a00-aa5f-11ea-8edf-4c8d68ebdbdc.png)

![image](https://user-images.githubusercontent.com/9218022/84143876-fbb85c80-aa5f-11ea-85ee-c09e2f583cac.png)

The logs of the agent are attached. 
[ecs-logs-i-0bc8ec76c85becf18.tar.gz](https://github.com/aws/amazon-ecs-agent/files/4751921/ecs-logs-i-0bc8ec76c85becf18.tar.gz)

**Comment by mythri-garaga** [comment]
Thanks for sending logs and other details.  

The logs provided does not have enough information. Could you please enable debug level logs for Docker and Agent, collect logs with [ECS logs collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html)  and send it over to us?

**Comment by sedovalx** [comment]
Will do. Please suggest how to enable the debug logs.

**Comment by yunhee-l** [comment]
Is this still an issue? I haven't seen any logs or task definition sent to ecs-agent-external@, but we may have missed it. Please update here if you are still experiencing this issue, and kindly send the task definition and logs again.

**Comment by sedovalx** [comment]
Hi! Yes, it is still an issue. Sorry, I'm a bit busy right now with other things but will definitely return to this in a few coming weeks.

**Comment by ellenthsu** [comment]
Hey sedovalx - when do you think you'll be able to provide this?

**Comment by sedovalx** [comment]
Let's close this issue for now. I will post an update here when I can.

**Comment by shobull** [comment]
Hi, I'm seeing similar issue - when my ec2 instance is downscaling, container running there receives kill signal, handles it **correctly** and **exits with exit code 0** but ECS page with task detail shows me following:

 `Service {}: container instance is in DRAINING state`

Status reason | OutOfMemoryError: Container killed due to memory usage
-- | --
Exit Code | 1

**Comment by chriswachira** [comment]
Hello all,

I also faced the same issue on ECS where the task stopped with Exit code 0 and the message `OutofMemoryError: Container killed due to memory usage` at the same time.

I was able to reproduce the same conditions locally, which means that a container **can** exit with code 0, 1 or any other and also face the OutOfMemory error. It is not an issue related to ECS.


### Steps to reproduce:

1. Run a simple NGINX container locally. Note that the memory limit is 1GB:

` docker run -d -p 8000:80 --memory 1G  nginx:latest`

2. Exec into the running container:

`docker exec -it 7607c647125c /bin/bash`

3. Install the `stress` package:

`root@:/# apt update && apt install -y stress`

4. Run `stress` with the following arguments:

`stress -c 2 -m 4 —vm-bytes 512M`

- The above command will try to use more memory than is available. You should see the output below. Notice the second line: `worker ID got signal 9`.

```
stress: info: [168] dispatching hogs: 2 cpu, 0 io, 4 vm, 0 hdd
stress: FAIL: [168] (425) <-- worker 172 got signal 9
stress: WARN: [168] (427) now reaping child worker processes
stress: FAIL: [168] (461) failed run completed in 1s 
```

5. From another terminal shell, stop the container with `docker stop` which will gracefully kill the main process in the container:

`docker stop CONTAINER_ID`

6. Check the container details using `docker inspect`:

`docker inspect CONTAINER_ID | jq ".[0].State"`

- You should see the output below:

```
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": true,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2024-09-27T08:18:42.210404427Z",
  "FinishedAt": "2024-09-27T08:27:21.077232458Z"
}
```

Notice that `OOMKilled` is `true` and `ExitCode` is `0`.


### Explanation

Since `stress` was not the main process in the container, the main process can continue forever and exit successfully. Therefore it's highly likely that your application is spawning another process that tries to consume more memory than is available.

I would advise monitoring your container to find the rogue process(es).
