### ISSUE TITLE
ECS-Agent loses control over containers/tasks

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#263]
Hello,

There are several cases I'm finding where ECS is losing management of containers that it has spun up. Because of our dynamic service discovery, this is causing split/experiences when needing to deploy new tasks as the old containers are still up and running. It also prevents us from stopping these tasks/containers through ECS. I am having to manually SSH into the ECS instances and run a `docker stop` on these containers.

I have a support case with AWS open for this and am wondering if these issues go to the same team, or if it will help to open an issue here as well.

We are running Docker 1.9.0 /w ecs-agent 1.6.0.

Thanks.

**Comment by euank** [comment]
It seems possible this might be the same issue as #261, which should be fixed by #262.

You can confirm this is likely the case by seeing if there are "oom" events for containers that exhibit this issue.
To test that, you can check affected container's event streams using the `docker events` API, or you can check dmesg output for references to that container being OOM killed.

It appears this issue affects the combination of Docker 1.9 and all released versions of the Agent, so there's not a great workaround. If downgrading Docker to 1.7 until an Agent update is released is an option for you, that could help.
Allocating more memory to the containers that trigger this behaviour could also reduce the chance of encountering it.

If I'm totally off-base and there's no oom events happening here, more information would be awesome.

Best,
Euan

**Comment by djenriquez** [comment]
Thanks for the very fast response @euank.

After looking through the logs I found this on the affected service:

`2015-12-08T16:23:46.231561498Z 66b156892166c265a73c36d979c141616329b7120fce2a6ce71fb0512bd5dc42: (from <REDACTED>/zoo-quiz) oom`

Looks like we're talking about the same issue?

**Comment by euank** [comment]
Thanks for checking. Since this looks like a dupe, I'm closing it in favor of #261. Feel free to watch/add more information on that issue or reopen this if it turns out to be different.

Best,
Euan
