### ISSUE TITLE
support native cloudwatch logs

### ISSUE THREAD

**Issue by wyaeld** [aws/amazon-ecs-agent#279]
Noticed today that ECS instances support docker updates to 1.9.1, which brings in the native cloudwatch driver

https://docs.docker.com/engine/reference/logging/awslogs/

Is this likely to be available soon, or something similar?  Seems like it should be substantially easier than wiring syslog manually

**Comment by zeisss** [comment]
I guess you can just configure the docker daemon to push there, which would let all logs push there.

**Comment by wyaeld** [comment]
ECS UI and API has options for the drivers, and this isn't supported yet from what I can see.  I might just be able to configure the daemon, but I suspect there would be side affects for doing something that it doesn't want to support yet.  Figure at least to check with the experts

**Comment by samuelkarp** [comment]
Thank you for the feature request!  As the author of the `awslogs` driver, I'm definitely interested in seeing ECS support it as well.  However, there's a bit more to it than just configuring the Agent (specifically, we'll need to make it easy to have a sensible log stream name; some discussion is available at https://github.com/aws/amazon-ecs-agent/pull/251).

I'm going to close this in favor of https://github.com/aws/amazon-ecs-agent/issues/9, since that issue is already tracking this feature request.
