### ISSUE TITLE
submodules broken

### ISSUE THREAD

**Issue by Ichimikichiki** [aws/amazon-ecs-agent#2829]
### Summary
The submodules are broken.
The submodule folders are empty.

### Description
Empty. Missing. Gone. No work.

### Expected Behavior
Submodules exist.

### Observed Behavior
Submodules empty.

### Environment Details
Every environment.

### Supporting Log Snippets
```bash
test_server in ~/.../aws λ wget https://github.com/aws/amazon-ecs-agent/archive/v1.50.2.zip
test_server in ~/.../aws λ unzip -q v1.50.2.zip
test_server in ~/.../aws λ cd amazon-ecs-agent-1.50.2
test_server in ~/.../aws/amazon-ecs-agent/amazon-ecs-agent-1.50.2/amazon-ecs-cni-plugins on master: la
total 0
```

**Comment by petderek** [comment]
[I think this is a limitation of github's archive api. ](https://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download) It doesn't look like github supports it. 

If I browse the [source code of the tag](https://github.com/aws/amazon-ecs-agent/tree/v1.50.2), I can see the submodules there. For your use case, is it possible to do git clone instead of wget?

**Comment by Ichimikichiki** [comment]
Yep git clone --recursive working
