### ISSUE TITLE
Question: how to update ecs-agent to 1.7.0?

### ISSUE THREAD

**Issue by artemave** [aws/amazon-ecs-agent#285]
I can update it from the web console for a particular machine, but I need to some custom configuration to make sure that the next EC2 instance starts with the new ecs agent.

I thought I could specify ecs-init rpm version in the .ebextenstion config file, but there seem to be no rpm for 1.7.0 (e.g. `yum update ecs-init` claims 1.6.0 is the latest version).

What am I missing?

Thanks!

**Comment by samuelkarp** [comment]
Hi @artemave,

I took a look at the Elastic Beanstalk Multi-Container platform and you are right in that the latest version that yum sees is 1.6.0.  This is happening because the Elastic Beanstalk AMIs are locked to a particular snapshot of packages and they do not receive updates automatically.  My understanding of why the Elastic Beanstalk team does this is to ensure that the underlying operating system and supporting packages do not change unexpectedly during your application's lifetime or when a new instance is launched.

If you are comfortable unlocking your instances (which does introduce the risk I described above), you can do so by running the following commands:

```
echo "releasever=latest" | sudo tee -a /etc/yum.conf
sudo sed -i 's/-\$guid//' /etc/yum.repos.d/amzn-updates.repo
sudo yum makecache
```

After I did that I was able to see the 1.7.0 package:

```
$ yum list available ecs-init --showduplicates
Loaded plugins: priorities, update-motd, upgrade-helper
Available Packages
ecs-init.x86_64                                                                              1.4.0-2.amzn1                                                                               amzn-main
ecs-init.x86_64                                                                              1.5.0-1.amzn1                                                                               amzn-updates
ecs-init.x86_64                                                                              1.6.0-1.amzn1                                                                               amzn-updates
ecs-init.x86_64                                                                              1.7.0-1.amzn1                                                                               amzn-updates
```

To complete the process, you'll then want to actually upgrade the package with `sudo yum update -y ecs-init`.

Please let us know if you continue to have questions about ECS.  For Elastic Beanstalk-specific questions, I'd recommend posting on the [Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).

Thanks,
Sam
