### ISSUE TITLE
ECS agent is trying to create cluster

### ISSUE THREAD

**Issue by warrenenb** [aws/amazon-ecs-agent#2928]
### Summary

ECS agent is trying to create cluster 

### Description

While build a SOE image the ECS agent is trying to create cluster, the IAM policy attached to the EC2 in the build process is blocking, this seems to related to the current AMI released in the last 24 hours

eventSource: "ecs.amazonaws.com",
eventName: "CreateCluster",
awsRegion: "ap-southeast-2",
userAgent: "Amazon ECS Agent - v1.53.1 (34ff78ad) (linux) (+http://aws.amazon.com/ecs/)",
errorCode: "AccessDenied",`

### Expected Behavior
Agent does not need to create cluster

### Environment Details

ap-southeast-2: ami-0d770005758827471

**Comment by yinyic** [comment]
Hi @warrenenb , thank you for your question! 

It is possible for ECS Agent to call `CreateCluster`. This behavior is triggered when a default cluster does not exist and customer has not specified another cluster in Agent configuration, as stated in [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) doc, under **Available Parameters** > **ECS_CLUSTER**.

Agent uses the EC2 instance IAM role when callilng ECS APIs such as `CreateCluster`, and the `AccessDenied` error could be caused by lacking permission. Could you provide the policies attached to the instance role you are using for your container instance?

Here is a [guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html) for creating IAM role with the correct set of permissions to be used by ECS Container Instances.

**Comment by warrenenb** [comment]
Hi @yinyic, 

Thanks for the information, from a security perspective I was trying not give my instance profile any permissions beyond creating a new SOE image. As I only build new SOE images when they are release I will ignore the the `AccessDenied`.

Thanks
