### ISSUE TITLE
ECS  agent is not pulling the latest image from ECR repository

### ISSUE THREAD

**Issue by vkannemacher** [aws/amazon-ecs-agent#2934]
### Summary
ECS  agent is not pulling the latest image from ECR repository

### Description
I am currently using ECS to deploy a web application. This Application is pushed on my ECR with the `latest` tag but putting new images doesn't seem to apply the changes made to the code at deployment.
After pushing my images using the push commands from ECR:
```
docker build -t revision_score .
docker tag revision_score:latest <registry_url>:latest
docker push <registry_url>:latest
```
I can see the new images recently published.
In my task definitions, the image is set to `<registry_url>:latest`. 
The deployement is launched with the following command: `aws ecs update-service --cluster <cluster name> --service <service name> --force-new-deployment`.

I also put `ECS_IMAGE_PULL_BEHAVIOR=always` in my ecs-agent config and deployment_minimum_healthy_percent = 0 and deployment_maximum_percent = 200 in my deployment settings.

I notice that the image digest displayed on the AWS console is matching the latest image, but by logging on the container, the code is not different from the previous version.

### Expected Behavior
I expect the ecs agent to pull the latest image at the new deployment

### Observed Behavior
The image running after the deployment contains the same code as the previous versions as if it was pulled from a cached image, even with the `ECS_IMAGE_PULL_BEHAVIOR=always` parameter.

### Environment Details
Amazon ECS Agent - v1.49.0
```
~]$ cat /etc/ecs/ecs.config 
ECS_CLUSTER=ecs-cluster
ECS_CONTAINER_STOP_TIMEOUT=2m
ECS_IMAGE_PULL_BEHAVIOR=always
```

**Comment by fierlion** [comment]
Sorry to hear you're having issues.  I'm working to repro this now.

**Comment by fierlion** [comment]
@vkannemacher, are you using ECS EC2 or ECS Fargate?

**Comment by vkannemacher** [comment]
Hi @fierlion, I am using ECS EC2.

**Comment by sharanyad** [comment]
@vkannemacher We were not able to reproduce this issue on our end. 

> I notice that the image digest displayed on the AWS console is matching the latest image, but by logging on the container, the code is not different from the previous version.

If the image digest is as expected, that would usually mean agent has pulled in the latest image from ECR.

Are you able to reproduce the issue consistently? What happens if you pull the latest image from a different instance and check the container? Does it have the newest changes? 

Could you also please collect logs from the instance for further debugging? In case logs are not at the debug level, if you could reproduce the issue with DEBUG log level enabled for agent (`ECS_LOGLEVEL=debug`) that would be great! Log collection details: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html 

Please send the following details to ecs-agent-external(at)amazon.com:
Task ID where image was not update 
Debug level logs from the instance collected using ECS Logs Collector. 

Thanks,
Sharanya

**Comment by vkannemacher** [comment]
Hello @sharanyad, I sent the logs.

>Are you able to reproduce the issue consistently?

Yes, the only way i found to have the right code working is to terminate the instance and wait for an other one to be started by its autoscaling group.

> What happens if you pull the latest image from a different instance and check the container? Does it have the newest changes?

When I pull the remote image on my local computer, the code running is the right one.

**Comment by sharanyad** [comment]
@vkannemacher Thanks for sending over the logs. I shall take a look.

**Comment by sharanyad** [comment]
@vkannemacher Looking through the agent debug logs, it seems that agent is pulling the newest image (verified through the image digest in the logs) successfully. Do you mind opening a support case via the AWS Developer Support program to better assist you? This would help us debug further in the right direction and obtain more information from you if required.
