### ISSUE TITLE
ECS task failed to start - container init was OOM-killed (memory limit too low?): unknown

### ISSUE THREAD

**Issue by frani** [aws/amazon-ecs-agent#3021]
### Summary

Container Task failed to start responde with next message error:

Status reason | CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: container init was OOM-killed (memory limit too low?): unknown

**Comment by mythri-garaga** [comment]
Hi @frani, Thank you for reporting the issue.

In order to better understand the issue, could you please use [ecs logs collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and send to ecs-agent-external at amazon dot com? or please provide steps if it is easy to reproduce?

**Comment by frani** [comment]
hi! I turn down ecs services as long we are using simple ec2 instance.

**Comment by MustaphaMaher** [comment]
Hey @frani .So i'm having the same error when running the container task  via ECS and i was wondering if you were able to solve it and if so can you  share the steps you followed ? I'd really appreciate it ,Thank you .
