### ISSUE TITLE
Appearant limit to max tasks per instance

### ISSUE THREAD

**Issue by holstvoogd** [aws/amazon-ecs-agent#3083]
### Summary
After updating to 1.57.0 our ECS cluster cannot schedule tasks beyond the third on instances. It seems at least.

### Description
At this point I have 17 active instances, all with exactly 3 tasks running. Several tasks, all with WAY less cpu required then what is available, will not start at all. They are stuck in provisioning until I add more instances. For instance one of the tasks needs 256 cpu shards, I have several instances with 3000+ cpu shares.

Memory is not relevantly constrained.

All tasks have an az-balance & then bin-pack placement config, however the tasks currently stuck in provisioning are singular instances. i.e nothing to spead over AZs. Not that any AZ does not have plenty of free capacity.

### Expected Behavior

Tasks should run on any instance that has sufficient resources, regardless of the number of tasks running, before requesting new instances from the capacity provider.

### Observed Behavior

Task do not run if the total number of tasks already on the on the instance is 3.
The get stuck in provisioning as the sheduler wait for the capacity provider to start more instances.

### Environment Details
- ECS agent vesion: 1.57.0
- AWS linux 2
- ECS cluster capacity is provided by an ASG

**Comment by holstvoogd** [comment]
This was not an issue before updating from 1.56.x, we basically doubled our EC2 usage today.

**Comment by fenxiong** [comment]
Hi,
thanks for creating the issue. a few questions:
* regarding `the tasks currently stuck in provisioning are singular instances`: could you send the following info the ecs-agent-external@amazon.com so we can take a look at why they stuck:
  - account id
  - region
  - task id(s)
* would it be possible for you to try downgrade to 1.56.x and see if that mitigates the issue? this will help verify if the version upgrade is the relevant factor.

**Comment by holstvoogd** [comment]
Mail sent & I will try downgrading tomorrow & report back.

**Comment by fenxiong** [comment]
I took a look at the instances in the cluster. looks like for the instances that have sufficient CPU, they are running into ENI attachment limit: the instance type of the instance can have at most have 4 ENIs to be attached, and there are already three tasks (running with network mode `awsvpc`) each causing one ENI to be attached. These plus the instance primary ENI sum to 4 ENIs. More information about ENI attachment limit and awsvpc network mode can be found at [1] and [2]. and in order to run more tasks in awsvpc network mode on single instance, you can potentially use the [ENI trunking feature](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html).

[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html
[2] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking-awsvpc.html

**Comment by holstvoogd** [comment]
We, or atleast I, have ENI trunking enabled already:
 ```
{
    "settings": [
        {
            "name": "awsvpcTrunking",
            "value": "enabled",
            "principalArn": "arn:aws:iam::762732311162:user/Arthur"
        },
....
```

I suppose it should be enabled for the instance role? However, I cannot see wether it is or not.
But as mentioned, this was not an issue before upgrading yesterday.

I will try to downgrade the ECS agent I guess.

**Comment by holstvoogd** [comment]
Alright, I definitly have trunking enabled for the role and as default for the root user too. On one of the instances:

```
[root@ip-10-0-1-138 ~]# aws ecs list-account-settings  --region eu-central-1
{
    "settings": [
        {
            "principalArn": "arn:aws:iam::762732311162:role/ecsInstanceRole",
            "name": "awsvpcTrunking",
            "value": "enabled"
        }
    ]
}
```

I have also downgraded to 1.56.0. But the 3 task limit still seems to be applied across the board :(

**Comment by holstvoogd** [comment]
Solved. We allowed m4 instances in our ASG spot requests, they do not support eni trunking appearantly.
Yesterday the ASG decided to replace _all_ instances with m4's so that is why everything broke.
