### ISSUE TITLE
ECS_LOGFILE in ecs.config does not appear to have any affect

### ISSUE THREAD

**Issue by gregorskii** [aws/amazon-ecs-agent#311]
Hi there,

Was trying to use ECS_LOGFILE to remove the rolling log filenames with timestamps this does not work when changing the value to a value:

```
ECS_LOGFILE=/var/log/ecs/ecs-agent.log
```

This results in the ecs-agent.log file missing, and the ecs-agent.log.TIMESTAMP to not be created.

Using agent v1.7.0.

Can this be verified?

Was trying to get around the issue listed here: https://github.com/aws/amazon-ecs-agent/issues/287

**Comment by euank** [comment]
The rolling filename is appended to that value regardless, and there's currently no variable to tweak that behavior.

The path that variable specifies is within the container. If you're running the agent via `ecs-init` (the default method on the ECS AMI), the in-container path will be `/log` and `ecs-init` mounts that out to `/var/log/ecs/` on the host. There's no simple way to tweak the mount path while still using `ecs-init`, so changing that variable really doesn't get you anywhere. That's why you're seeing nothing after changing it away from the default `/log/...` path.

Other workarounds here would be to use a different docker logdriver (e.g. `journald` or `syslog`) and go from there, or pipe `docker logs -f ecs-agent` into a file by some mechanism (hacky!).
To accomplish the first, you could launch the Agent via `docker run` instead of the default `ecs-init`, thus letting you specify `--log-driver`, or you could specify the `--log-driver` flag in your daemon options for all containers, letting the Agent pick it up that way.

It would probably make sense for `ecs-init` to let you twiddle a knob for what docker logdriver to use (maybe make an issue [over there](https://github.com/aws/amazon-ecs-init/issues)), which would add another slightly better option into the mix.

As a brief aside, using a docker logdriver vs the logfile is *technically* slightly different, namely that crashes will dump into the former and not the latter, but it shouldn't be noticeably different.

Best,
Euan

**Comment by gregorskii** [comment]
Euan,

Appreciate the detailed explanation. Appears I misunderstood the variable.

This is an aside, but the short term goal I am trying to accomplish is figuring out why a container will not start with some modified nodejs code. Where would I find the logs for both crashes and restarts?

I have errors from within the containers nodejs code pushing to loggly, including process.on('unhandledEception') but nothing makes it to loggly.

My long term goal is to get ecs errors into loggly, which I will continue to track the referenced issue.

Thanks,

Greg

**Comment by euank** [comment]
`docker ps -a` combined with `docker inspect` (see exit code / error message) and `docker logs` (or if you're using a different logdriver, looking at that) is usually where I start; things like being OOMKilled or having network errors might show up there even if they're not getting to loggly.

The Agent leaves around containers after they die for 3 hours by default so you can look at 'em. It doesn't restart them, but spins off more instances of them. The container name and docker labels should have enough information that you can pinpoint the relevant ones.

Hopefully you typoed there and meant `uncaughtException` not `unhandled`, but regardless, removing that and letting the crash hit stdout so you can see it in docker logs could also help.

All of the above, apart from the agent leaving things around, is application specific though and might or might not be relevant.
Good luck,
Euan

**Comment by gregorskii** [comment]
Thank you for the tips. Will begin investigating. Yes it is the correct uncaught error. It eludes my mind at the moment, not in front of the code.

Thanks again!
