### ISSUE TITLE
Setting hard limit for CPU

### ISSUE THREAD

**Issue by bushev** [aws/amazon-ecs-agent#3110]
Hey @petderek, Could you please confirm that this (https://github.com/aws/amazon-ecs-agent/issues/1093#issuecomment-349830171) still working in 2021?

As I understand the top-level task CPU parameters are a hard limit. But when I set it to 256 (0.25 vCPU) I'm still able to load all my 4 vCPU at 100% in the EC2 instance from inside the container.

```typescript
const params: RegisterTaskDefinitionCommandInput = {
  family: `u_${userId}`,
  containerDefinitions: [
    {
      name: 'container',
      image: CONTAINER_IMAGE_NAME + ':' + version,
      memory: limits.memory, // Hard limit, will be reserved for task
      stopTimeout: 5 // Wait 5 second before killing the container
    }
  ],
  cpu: '256' // Hard limit?
};

const { taskDefinition } = await ecsClient.registerTaskDefinition(params);
```

---

![image](https://user-images.githubusercontent.com/7535766/147495610-aec3ef1c-6461-4965-a65a-0b418a44be9b.png)

---

![image](https://user-images.githubusercontent.com/7535766/147495694-17594db5-b31a-4bc6-b6f9-6cc514fe45c7.png)

---

Agent version: 1.56.0
Docker version: 20.10.12

**Comment by petderek** [comment]
Hello! It should be the case! One thing is that this feature depends on the docker api's ability to use a custom cgroup hierarchy. Some stuff that comes to mind is:

* If you are using cgroupsv2, it might not play correctly with ecs since v2 doesn't have the same hierarchy support (per my understanding). 

* I don't know that we've tested with sysbox. That might be the difference here. 

For posterity -- which ami are you using? Which of these features/technologies is important to your use case?

**Comment by bushev** [comment]
Hi, Thanks for a quick reply!

We are on Ubuntu 20.04. I can definitely test it without a symbol integration, we don't need it anymore.

Could you advise, how to check out cgroupsv2 is fine?

**Comment by bushev** [comment]
Here is how we are configuring Ubuntu 20.04 - https://gist.github.com/bushev/11ed0d0c1a0dbcd648a58f6d5b3f5c58 , especially, we are enabling memory and disk quotas.

**Comment by bushev** [comment]
Gotha, that I missed:

1. cgroups v2 should be disabled with `systemd.unified_cgroup_hierarchy=0`
2. Volume should be attached: `--volume=/sys/fs/cgroup:/sys/fs/cgroup` even in I don't use awsvpc mode
