### ISSUE TITLE
Log image pull time in milliseconds instead of multiple different units

### ISSUE THREAD

**Issue by francispereira** [aws/amazon-ecs-agent#3119]
### Summary
Depending on how long an image takes to pull, it is reported in different units making it hard to graph

### Description
Image pull time is logged in milliseconds (if lesser than 1000ms), seconds (if lesser than 60s) and minutes (if lesser than 60m) making it hard to graph

### Expected Behavior
Irrespective of time taken to pull an image, log it in milliseconds

### Observed Behavior
Image pull time is being logged in different units

### Supporting Log Snippets

level=info time=2022-01-19T20:09:45Z msg="Task engine [XXX]: finished pulling image YYY for container ZZZ in 27m58.213326428s" module=docker_task_engine.go

level=info time=2022-01-19T19:42:28Z msg="Task engine [XXX]: finished pulling image YYY for container ZZZ in 15.294304017s" module=docker_task_engine.go

level=info time=2022-01-19T20:34:21Z msg="Task engine [XXX]: finished pulling image YYY for container ZZZ in 702.774813ms" module=docker_task_engine.go

**Comment by prateekchaudhry** [comment]
Thank you for reaching out. Currently, this particular log output is the default Golang string conversion behavior for time Duration. We would like to keep the current format for human readability of logs, though you could try parsing and converting to milliseconds for your purpose.

**Comment by prateekchaudhry** [comment]
Hi @francispereira, an update on this, we want to keep logging in line for debugging and human readability. Also making such changes might be not be good for backwards compatibility if some customers are already using the current format. We will work on a GitHub proposal related to this request and may work towards it depending on response. Thank you!

**Comment by YashdalfTheGray** [comment]
### ECR image pull time unit proposal

Currently, when the ECS Agent pulls container images, we log the time that we took to pull the image out [here](https://github.com/aws/amazon-ecs-agent/blob/fe79b107f3b204ca1a831b1d15424d12d2948bdf/agent/engine/docker_task_engine.go#L933). 

The current log format is `Task Engine [#{taskArn}]: finished pulling image #{imageName} for container #{containerName} in #{timeDuration}`. The logging package we use puts the log message inside the `msg` section of `level=<log level> time=<UTC timestamp> msg="" module=<module name>`. 

We use `time.Since()` from the golang `time` package as the way to convert a point of time to a duration when we compute `#{timeDuration}`. [The `.String()` method on `Duration`](https://pkg.go.dev/time#Duration.String) formats the duration so that it is human readable - 10ms, 10s, 10m0s, etc. This makes it easy to understand the scale of time while engineers are reading the logs but it makes it hard for automated log parsers to understand since the units change depending on the scale of the time it took. 

[Go playground Demo](https://go.dev/play/p/Alb5ryVd7zk)

### Solution proposal

In order to make the time duration more machine readable, we propose adding a logfmt style string to the `#{timeDuration}` section, i.e. changing the format for `#{timeDuration}` to `time.Since(pullStart).String() pullTimeInMs=time.Since(pullStart).Milliseconds()`. This would keep the human readable time in the logs but it would also include an expression of duration in consistent units that can be parsed through. 

The format for the log statement would then become `Task Engine [#{taskArn}]: finished pulling image #{imageName} for container #{containerName} in #{timeDuration} pullTimeInMs#{timeDurationInMillis}ms`. 

### Example

An example log line in the current format

```
level=info time=2022-02-16T02:53:40Z msg="Task Engine [ARN]: finished pulling image nginx for container web in 15s" module=docker_task_engine.go
```

becomes

```
level=info time=2022-02-16T02:53:40Z msg="Task Engine [ARN]: finished pulling image nginx for container web in 15s pullTimeInMs=15000" module=docker_task_engine.go
```
