### ISSUE TITLE
ECS not able to Scale Down Containers when not in use

### ISSUE THREAD

**Issue by akshaypuri08** [aws/amazon-ecs-agent#3129]
### Summary

 when ECS don't have any kind of load or less load the container don't scale down the containers that are scaled up

### Description

if a specific container is getting too much load ECS is able to spin up more container and distribute the load properly but when load on the container stabilize and when it don't have any kind of load or less load the container don't scale down the containers it will run the same number of containers  when it was at max load capacity

### Environment Details

we have configured environment 

**EC2 Instance type**
t3.small 

**Task definition** 
Soft Limit 
100mb

Network mode
Bridge

Task execution role
Execution-role

**ASG** 

Desired capacity
3  
Minimum capacity
1    
 Maximum capacity
5

Services 
46

Running tasks
69

CPUUtilization
25.27%

MemoryUtilization
28.77%

**Termination policies**
Default 

deploying infrastructure with terraform

**Comment by mythri-garaga** [comment]
Hi @akshaypuri08 

Thank you for reporting this. Could you please provide more details on the scaling policy type and configuration?

**Comment by mythri-garaga** [comment]
@akshaypuri08, also could you please check if all the instances have tasks running on them? If so, we won't scale any of them in to avoid interrupting any ongoing tasks when managed termination protection is enabled.

Could you please provide the following information?
- Account ID
- Cluster Name
- Capacity provider name
You could send this details to ecs-agent-external at amazon.com. Thank you!

**Comment by akshaypuri08** [comment]
@mythri-garaga
 Minimum tasks: 1
Maximum tasks: 5

scaling policy type => Target tracking
configuration Tracking ECSServiceAverageMemoryUtilization at 70
Disable Scale In: false

as i checked , AWS cloudwatch alerts are used for this, which will create 2 alerts, 1 for High and 1 for Low, lets say we have 5 tasks running, and all have usage less then 70%, an alert triger will hit for Low and will decrese tasks to 4, now alert is in "In alarm" state but the Action will not trigger again and taks will stay at 4 forever or untill it needs to scale out

**Comment by mythri-garaga** [comment]
@akshaypuri08, thank you! 

Could you also please provide the service info and timeframe of the issue?

**Comment by akshaypuri08** [comment]
@mythri-garaga  we are running basic node  applications as services .The time frame is always  i have noticed the issue on 14 Feb 2022 and its persistence till  date

**Comment by prateekchaudhry** [comment]
Hi @akshaypuri08, from what I have gathered, here could be a few common reasons that could stop the scaling down for this particular scenario -

* Is there a service auto scaling in place other than just ASG as well? Could you verify if 4 is not the minimum or desired number of tasks in there if it is in place.
* Are there more than one target policies in place? If there are multiple target tracking policies, it could be possible they aren't all trying to scale-in at the same time.

Otherwise, it could be happening that the metric is just a bit under the low usage alarm threshold, and AutoScaling is calculating that reducing the desired capacity from 4 -> 3 would cause the average metric to jump up above the high usage threshold, thus causing infinitely oscillating loops. When this happens, AutoScaling will choose not to scale in. In which case, changing the metric and verifying might help, if it is possible for your workflow.

**Comment by mythri-garaga** [comment]
Closing this issue since there were no updates.
