### ISSUE TITLE
ECS Servers become bricked due to ECS Agent not handling crashed containers correctly.

### ISSUE THREAD

**Issue by viion** [aws/amazon-ecs-agent#3135]
### Description
Hello, Recently I am noticing a lot of times I can no longer deploy to an EC2 in my ECS cluster, when I go to investigate all the tasks are stuck either "Pending" or they're in the Stopped tab by status "Running", however they're unreachable. If I try to SSH into the EC2, it's non-responsive. If i try to Reboot the server on the Console, it's unresponsive... 

This basically means the whole server is bricked.

I am kind of at a loss at what could cause this... These are simple t3.medium servers, and it's happening several times a week now. The main pain point is because this is all scalable they don't have static IP's so I have to go re-whitelist all the servers in many places.

Any help would be appreciated, even if it's how I could debug this situation.

### Expected Behavior
Expect the EC2 not to become unresponsive during ECS Agent.

### Observed Behavior
I've noticed when a docker container either crashes or fails to boot, or even if stopped manually, this causes the whole server to become bricked. The server does not run out of CPU, it doesn't run out of Memory. All the graphs are normal and then just flatline.

### Environment Details
Sadly I cannot even get onto the server to supply this info... it's completely bricked. I am on the ECS Agent: 1.51.0 and Docker Version: 20.10.7 

### Supporting Log Snippets
Sadly I cannot provide as once it happens the server is dead and I cannot access it.

**Comment by Realmonia** [comment]
Hi @viion since there is not much info I can get from your description, I want to ask if there is any specific reason you run Agent 1.51.0 instead of the latest? There are couple of enhancements and bug fixes we made. e.g. Agent version <1.55.3 and Docker version 20.10.7 have some issue regarding ipv6 port bindings together which could potentially cause task fail to start and fall into infinite retry and failure. If you look at the [release page](https://github.com/aws/amazon-ecs-agent/releases) there are other bug fixes. I can't tell from the behavior if it's related to any of the known bugs, but use up to date agent would be a good starting point.

**Comment by viion** [comment]
Hi @Realmonia Yeah sadly I can't provide a whole lot :(

thank you for your response, I actually thought I was on the latest because no message comes up to say my agent is out of date and when I spin up new EC2 instances that is the one it installs automatically. I will give that a shot and see if it helps, thank you!

**Comment by Realmonia** [comment]
You can use `aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended --region <REGION>` in aws cli to get info about latest agent version and use latest ECS Optimized AMI.

I am going to close this for now, feel free to reopen if you have new findings!
