### ISSUE TITLE
Python logging messages not shown in cloudwatch log

### ISSUE THREAD

**Issue by yduan-polo** [aws/amazon-ecs-agent#3209]
### Summary
I have a scheduled ecs task which runs a bash script and the bash script calls a python script.  The bash script sets "set -x", and bash debug messages are shown in cloudwatch log, but messages from python script are not. 

### Description

Output shown in cloudwatch from bash script

+ SCRIPT_PATH=bin/run_dbt.sh
++ dirname bin/run_dbt.sh
+ SCRIPT_DIR=bin
+ '[' -z prod ']'
+ python ./bin/../data_warehouse/scripts/check_task_running.py -e prod
+ '[' 0 -eq 2 ']'
+ set -e
+ dbt seed --threads 16 --profiles-dir . --target prod --exclude data/test/

In check_task_running.py,  logging is set this way:

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
stream_handler = logging.StreamHandler(sys.stdout)
logger.addHandler(stream_handler)

and then throughout the script, logging.info is called.  Any idea where should I look?  Thanks.

### Expected Behavior

I expect messages from logger.info show up in cloudwatch log since the logger streamhandler is stdout.

### Observed Behavior

They don't, but strangely bash stdout shows up in the logger.

**Comment by angelcar** [comment]
Hi. Thanks for reaching out. 

For testing purposes, is it possible for you to run your docker image using just docker without specifying any log driver?

Then, execute `docker logs <your_container_id`. If you see your python logs there, then the issue might indeed be related to awslogs driver, otherwise it might be related to how the script is executed. 

In order to further assist on our end, could you provide repro steps? I'd suggest to create a docker image with the minimum steps necessary to repro the issue.

**Comment by yduan-polo** [comment]
After further debugging, It's actually user error. Apologize for wasting your time.
