### ISSUE TITLE
ECS task that stopped reporting Memory/CPU usage not automatically restarted

### ISSUE THREAD

**Issue by abrenaut** [aws/amazon-ecs-agent#3254]
### Summary

A container deployed as a ECS Fargate task and managed by a ECS service crashed and was not automatically restarted by the ECS service.

### Description

A container deployed as a ECS Fargate task crashed.

It was still reporting as running in the ECS service console.

![Screen Shot 2022-06-14 at 8 49 11 pm](https://user-images.githubusercontent.com/1426600/173715789-39b19c70-2234-4d41-a33e-6be4cb426684.png)

But it stopped reporting memory and CPU usage and stopped sending logs to CloudWatch logs.

![Screen Shot 2022-06-14 at 8 46 37 pm](https://user-images.githubusercontent.com/1426600/173715670-5148cfb0-6200-4b1d-acae-886303f88f39.png)

### Expected Behavior

The container is flagged as essential and the number of desired tasks in the corresponding ECS service is set to 1 so I would expect ECS to stop the crashed ECS task and start a new one but this didn't happen.

### Observed Behavior

The ECS service did not start a new ECS task to replace the one where the container crashed.

### Environment Details

ECS Fargate (Platform version = LATEST)

### Supporting Log Snippets

No access to the ECS agent logs in the Fargate launch type.

**Comment by mssrivas** [comment]
Hi @[abrenaut](https://github.com/abrenaut) ,

Since you are using Fargate with platform version 1.4.0, kindly create a support ticket with AWS Fargate for better assistance.

Ref: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case

I will close this ticket. Kindly reopen if you have further questions.
