### ISSUE TITLE
Calling run-task immediately after stop-task causes Docker link error

### ISSUE THREAD

**Issue by kennu** [aws/amazon-ecs-agent#33]
I created a deployment script which
* Pushes a new Docker image to a repository
* Calls "aws ecs stop-task" and immediately
* Calls "aws ecs run-task" to start the same task again

I believe ECS Agent gets confused when it tries to resolve the link dependencies for the "run-task" operation, because some the containers that were just stopped are still alive. When it tries to create a new container, I see this error in "docker inspect":

    "State": {
        "Error": "Cannot link to a non running container: /ecs-xxx-19-mongodb-f6eea4f8a4c0e2b17600 AS /ecs-xxx-19-xxx-a4a59ffef4d1b48bb701/mongodb",
        "ExitCode": 128,

My task definition has 4 containers: A MongoDB server and some applications linked to it.

**Comment by euank** [comment]
Mind giving a few more details about the issue? I'd like to verify that it's linking against the correct container (you can run `curl localhost:51678/v1/tasks` to check which task that DockerName belongs to).

My guess for what's happening here is that the second container is linking against the correct mongodb (the one in the second task), but that mongodb is starting and then very quickly stopping, possibly due to not having memory available.
Inspecting the referenced container (e.g. `docker inspect ecs-xxx-19-mongodb-f6eea4f8a4c0e2b17600`) and checking the state field could corroborate this.

Thanks,
Euan

**Comment by euank** [comment]
The issue that I think this was (as I described it above) should be fixed with the release of the v1.1.0 agent. If you encounter it again, please reopen this issue or create a new one.

**Comment by kennu** [comment]
Thanks, sorry for not getting back to it for a while. I think my deployment procedure will be different nowadays, when using Services instead of Tasks, but I'll report if I see this problem surface again.
