### ISSUE TITLE
Allow local reservation of CPU resources

### ISSUE THREAD

**Issue by seiffert** [aws/amazon-ecs-agent#369]
In order to limit the CPU resources that are offered to ECS tasks, I would like to discuss whether adding a configuration value `ECS_RESERVED_CPU` would make sense. This option would have an effect analogous to `ECS_RESERVED_MEMORY` and limit the CPU resources reported to ECS. 

For memory, the calculation is done here: (https://github.com/aws/amazon-ecs-agent/blob/304495bc6defdcc98f15a97b271c41127dba5e48/agent/api/api_client.go#L209)

```go
	cpu, mem := getCpuAndMemory()
	mem = mem - int64(client.config.ReservedMemory)
    
	[...]

	memResource := ecs.Resource{
		Name:         utils.Strptr("MEMORY"),
		Type:         &integerStr,
		IntegerValue: &mem,
	}
```

We currently face a situation where a complete reservation of an instance doesn't leave much CPU resources for system processes.
If you agree that such a change would make sense, I'm happy to provide a PR.

**Comment by samuelkarp** [comment]
Hi @seiffert,

Thanks for offering to help out!  While we appreciate what you're offering, unfortunately I don't think creating a "reserved CPU" configuration will have the effect you intend.

The `cpu` field in the task definition ultimately maps to the `CpuShares` setting for the container (like the `--cpu-share` flag on `docker run`).  CPU shares are a relative resource share rather than being a fixed resource allocation or limit; this means that while we specify that there are 1024 CPU units per CPU core on the instance, a task that specifies less than 1024 still has access to the full 1024 when it is either the only task running or there is no CPU contention.  From our [documentation](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html):

> For example, if you run a single-container task on a single-core instance type with 512 CPU units specified for that container, and that is the only task running on the container instance, that container could use the full 1,024 CPU unit share at any given time. However, if you launched another copy of the same task on that container instance, each task would be guaranteed a minimum of 512 CPU units when needed, and each container could float to higher CPU usage if the other container was not using it, but if both tasks were 100% active all of the time, they would be limited to 512 CPU units.

The memory situation is a bit different.  Memory constraints expressed through the `memory` field are equivalent to the `--memory` flag on `docker run` and specify an actual resource limit rather than a proportional resource share.  Because this is an actual resource limit, the `ECS_RESERVED_MEMORY` configuration variable lets the ECS scheduler actually prevent placing tasks that would consume too much memory from the host.  However, an important note here is that `ECS_RESERVED_MEMORY` just affects how the ECS scheduler operates, rather than how the existing Docker resource configuration works.  In adding `ECS_RESERVED_CPU`, the scheduler would place tasks consuming fewer CPU units, but ultimately the tasks that are placed on the instance could still end up saturating the CPU due to the proportional resource share.

If you're having CPU contention as you describe where there is very little CPU left for on-host processes, you may have a use-case for setting flags which provide additional CPU constraints such as [CPU quota](https://docs.docker.com/engine/reference/run/#cpu-quota-constraint ), [CPUSet](https://docs.docker.com/engine/reference/run/#cpuset-constraint), or [CPU period](https://docs.docker.com/engine/reference/run/#cpu-period-constraint).  While ECS does not support setting these additional flags in a task definition today, I can definitely record this as a feature request.  If there are any additional details on the use-case and problems you're experiencing, that information definitely helps us prioritize.

Thanks,
Sam

**Comment by samuelkarp** [comment]
@seiffert I'm going to close this for now.  Please feel free to re-open if you have additional questions or details to share.

**Comment by seiffert** [comment]
Hi @samuelkarp,

thank you very much for your detailed response! I was aware of the fact that CPU shares are a relative unit but apparently I didn't think this through to the end. CPU quota sounds like a good starting point, yes. 

Cheers,
  Paul

**Comment by jbergknoff** [comment]
Was a feature request created for exposing the CPU quota option? It seems to be possible for a container to consume so much CPU that the ECS agent and/or Docker daemon can't operate. There should be a way to protect against that possibility.

**Comment by samuelkarp** [comment]
@jbergknoff We have one internally but there isn't one currently open on GitHub.  Feel free to create one if you'd like.
