### ISSUE TITLE
Unable to install in windows server 2022

### ISSUE THREAD

**Issue by raphael5178** [aws/amazon-ecs-agent#3753]
### Summary
When i install agent o windows server 2022 i got this error:
![error windows 2022 docker](https://github.com/aws/amazon-ecs-agent/assets/85692804/c78b717f-b27e-4c3b-9b70-e0694bb87c8a)

### Description
I believe it's because the [OneGet/MicrosoftDockerProvider](https://github.com/OneGet/MicrosoftDockerProvider) provider is deprecated.
![image](https://github.com/aws/amazon-ecs-agent/assets/85692804/7a34b99c-761c-40fd-9149-c7c5a07c9cd1)

however if i install docker manually following [this article](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1).
![image](https://github.com/aws/amazon-ecs-agent/assets/85692804/017fd375-ce3c-4cec-8b05-97edd4542b35)

agent works fine.

**Comment by arun-annamalai** [comment]
Thank you for bringing this to our attention. We will be taking a look at this issue!

**Comment by jterry75** [comment]
What version of agent/bootstrap are you using? This was fixed a while back

**Comment by raphael5178** [comment]
how much time? because issue was open 2 months ago

i'm installing agent using ecs register external instance, 

I believe that the command generated by the AWS panel uses the latest version.

**Comment by rawahars** [comment]
So the ECS Windows init script does not support installing container runtime at the moment. This is because we shifted from using Docker EE to Docker CE. Presently, the Docker CE artifacts are published as part of ECS Windows Anywhere i.e. `https://amazon-ecs-agent.s3.amazonaws.com/ECSAnywhereWindowsArtifacts.zip`.

For future AMI release, we will make the changes in our init script to install docker CE using the above archive.

**Comment by jiuchoe4** [comment]
The fix for this has been merged and will be released with our January AMIs. Thank you for your patience.
