### ISSUE TITLE
Feature Request: Docker LABEL containing ECS Cluster Name

### ISSUE THREAD

**Issue by CpuID** [aws/amazon-ecs-agent#376]
Use Case: We currently use separate ECS Clusters in separate VPCs, for Staging, Production and Operations purposes. We then ingest all logs into an ELK stack using [docker-logstash-forwarder](https://github.com/digital-wonderland/docker-logstash-forwarder) - this will probably change to something like [journalbeat](https://github.com/mheese/journalbeat) + the Docker journald log driver shortly.

Ideally I would like to be able to identify if a log was from a container instance on Staging vs Production vs Operations, or whatever else. Can we get a Docker Label attached to the running containers containing the ECS Cluster Name? Similar to the existing labels, like:

- `com.amazonaws.ecs.container-name`
- `com.amazonaws.ecs.task-arn`
- `com.amazonaws.ecs.task-definition-family`
- `com.amazonaws.ecs.task-definition-version`

**Comment by samuelkarp** [comment]
I think this sounds fairly reasonable.  The one complication here is that the agent does not necessarily know the name, but only knows what you configure as `ECS_CLUSTER` (which could be either the name or the ARN), so my recommendation would be calling the label `com.amazonaws.ecs.cluster` rather than `cluster-name`.  If you're interested in sending us a pull request, the labels are set [here](https://github.com/aws/amazon-ecs-agent/blob/v1.8.2/agent/api/task.go#L235-L241).

**Comment by CpuID** [comment]
https://github.com/aws/amazon-ecs-agent/issues/443 merged, closing. Thanks :)
