### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by tdekoning93** [aws/amazon-ecs-agent#3770]
It has been more than a year now that Ubuntu 22.04 has been released. Ubuntu 18.04 mainstream support has been deprecated already for a while. How come there is no support for Ubuntu 22.04 yet? All other AWS services seem to support it, but its lacking for the AWS ECS Agent.

**Comment by Realmonia** [comment]
Hello @tdekoning93 Please see this previous issue https://github.com/aws/amazon-ecs-agent/issues/3227 on getting ecs anywhere working on your ubuntu 22.04 instance. Due to prioritization reason, we don't have that implemented yet. Please open an issue (or +1 on the issue if it exists) in https://github.com/aws/containers-roadmap/issues. Our product team will prioritize accordingly.

Please feel free to reopen if there are further questions!
