### ISSUE TITLE
DAEMON tasks should wait till REPLICAs are STOPPED instead of simply !RUNNING

### ISSUE THREAD

**Issue by robert-csdisco** [aws/amazon-ecs-agent#3829]
### Summary
Daemon tasks today wait for all the non daemon tasks(REPLICAS) to be transitioned out of the RUNNING state. This is pretty instantaneous. It should wait till all non daemon tasks are STOPPED

### Description
A task goes from running to a few other states prior to being STOPPED. In first state after RUNNING, the task is still alive and has received the SIGTERM. However, it might not be dead yet, and could still possibly be using the daemons on the host. Our example is consul. There is one consul on the host that all the tasks know they can use. We could place consuls in every task, but it functions really well as a solo host-sidecar-daemon task

When the last replica task begins it's shutdown, I've seen the consul agent get immediately terminated, since the replica task is no longer "RUNNING". It would be nice if the daemons were preserved till the replicas were stopped, which means they are 100% dead, and no longer will be making any requests of the daemons

**Comment by robert-csdisco** [comment]
This seems different from https://github.com/aws/containers-roadmap/issues/1700   That one might be fixed.

What I observe is the node goes into draining. ECS finds homes for the replicas on that host. It waits for them to startup and be healthy.
Then, it transitions the replicas on the to be drained host to !RUNNING. At some point REALLY close to there it also removes them from service discovery. My task initiates a grpc shutdown on the service, which should GOAWAY new requests, but allow existing ones to finish. I think

Either way, what I observe is a few requests that are still coming in get angry because consul gave it a connection-reset-by-peer. They get an internal error from our app. The client retries and gets a new host and is happy, but I'd like to make my upgrades SUPER secret so that the clients have no idea what happened.

In this case, the client is an appmesh envoy proxy, so it knows REALLY quick when a host is removed from service-discovery, but not quick enough

An alternative would be a linger setting on a task. Where the task was removed from service discovery and/or target groups for X seconds before it gets the SIGTERM. This would still probably affect streaming requests, but in this particular usecase, the requests are all unary GRPC.

**Comment by robert-csdisco** [comment]
From my testing the task transitions from 
RUNNING
DEACTIVATING
STOPPING
STOPPED

I think the key state here is DEACTIVATING. I believe a task in that state has been give the docker stop, but it hasn't stopped yet.

**Comment by amogh09** [comment]
Hi @robert-csdisco. Thank you for opening this issue and sorry that you are having trouble using Daemon tasks. 

I think the root of your issue is the same as https://github.com/aws/containers-roadmap/issues/1700 in that the Daemon task is stopped prematurely. ECS should not issue a SIGTERM to your Daemon task until all replicas on the container instance (host) have been stopped. 

As far as ECS Agent is concerned, it makes no distinction between Daemon and Replica tasks and relies on the ECS backend to orchestrate the start/stop of dameon and replica tasks in proper order. 

Please let us know if you still think that the issue you are seeing is not caused due to https://github.com/aws/containers-roadmap/issues/1700.

**Comment by singholt** [comment]
closing, please re-open if you need more help.
