### ISSUE TITLE
On error in essential container ecs-agent downloads new versions of container until hard drive becomes full

### ISSUE THREAD

**Issue by gugu** [aws/amazon-ecs-agent#386]
If contaner fails to start, ecs-agent downloads new versions of container until docker hangs.

Running `docker ps -a` shown tens pages of containers.

And after that I receive errors:

    Driver devicemapper failed to create image rootfs 7b2226da2164700818737933b22f48559d251a3d9d5d9988522b6b33dec762a5: Error running deviceCreate (createSnapDevice) dm_task_run failed reate (createSnapDevice) dm_task_run failed

Expected behavior: ecs-agent should restart existing container, not download new

**Comment by samuelkarp** [comment]
Hi @gugu,

It sounds like you're using the service scheduler and running into issues when your containers do not start up correctly.  The service scheduler is designed to keep your application up and running, so it will attempt to place tasks whenever the existing tasks exit or are determined to be unhealthy by the load balancer health check.  Because there might be something wrong with the state inside existing containers (and because tasks are not guaranteed to be placed onto the same host when scheduled), ECS always opts to create new containers rather than restart existing ones.

Containers are by default retained for 3 hours to aid in debugging.  Since it sounds like this retention period is not the option you want, you can adjust `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` to a time shorter than 3 hours.  This should help reduce the amount of disk consumed by exited containers as they will be retained for a shorter amount of time.

Please let us know if you have any additional questions.

Thanks,
Sam

**Comment by gugu** [comment]
Yes, thanks a lot, it will help me to solve this problem
