### ISSUE TITLE
ECS Agent not Releasing EFS Client Connections

### ISSUE THREAD

**Issue by mshober** [aws/amazon-ecs-agent#3874]
### Summary
I have an ECS cluster dedicated to running batch jobs. Today, I noticed one of our tasks failed to start with:
> Error response from daemon: create REDACTED: VolumeDriver.Create: mounting volume failed: Failed to locate an available port in the range [20049, 21049], try specifying a different port range in /etc/amazon/efs/efs-utils.conf

After some troubleshooting, I found that our EFS Filesystem Connection Count was huge:
<img width="1790" alt="Screenshot 2023-08-28 at 16 39 11" src="https://github.com/aws/amazon-ecs-agent/assets/35979100/b964de9a-e6ca-4e5d-a584-3cad2da06215">
After terminating one of our 5 running ECS instances, the connection count dropped from 4,343 to 3,421. 

### Expected Behavior
We typically have less than 100 active tasks running on our cluster; I'd expect our Connection Count to match that amount

### Observed Behavior
It appears that our Filesystem Connections don't get disconnected until our instances are terminated.

### Environment Details
AMI: ami-0ab480cce6dcba4b1 - Amazon Linux 2023 (arm64)
ECS Agent Version: 1.75.0
Docker version: 20.10.23
Instance Type: m7g.2xlarge

Note: This is a relatively new environment, so I can't verify that this issue came from a recent ECS Agent release.

### Relevant Task Definition Parameters
```json
{
    "networkMode": "host",
    "volumes": [
        {
            "name": "storage-folder",
            "efsVolumeConfiguration": {
                "fileSystemId": "fs-0d10a30e01c032375",
                "rootDirectory": "/",
                "transitEncryption": "ENABLED",
                "authorizationConfig": {
                    "iam": "DISABLED"
                }
            }
        }
    ],
    "mountPoints": [
        {
            "sourceVolume": "storage-folder",
            "containerPath": "/opt/REDACTED/storage",
            "readOnly": false
        }
    ],
}

**Comment by amogh09** [comment]
Thanks for opening this issue @mshober and sorry that you are having trouble using EFS on ECS. I tried to reproduce the issue on my end but was not able to do so. The connection count for the EFS volume matches the number of instances in my test setup regardless of the number of EFS tasks running on the instances. I do see Docker Volumes being left on the instances after the tasks have stopped but that is not affecting the connection count. I will update my test setup to match more closely to your environment and post my findings here.

**Comment by amogh09** [comment]
Hi @mshober. I updated my test setup to use the same AMI as your setup, and m7g instance, and a service that creates EFS tasks in host network mode. However, no matter how many tasks I start on the instance there is only one connection count in the metrics. That one connection stays until ECS Agent cleans up all the docker containers of the tasks (after `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` is elapsed). 

Please let me know if you are able to create a reproducible for this issue.

**Comment by shawnh-burst** [comment]
I might have some related info.

I have an ECS task in awsvpc networking mode that is the only client connecting to a particular EFS & I am seeing some poor behavior as of Oct 1st, I am assuming this coincides with AWS maintenance:

`Starting October 1, 2023, EFS will begin a network upgrade to deliver lower-latency access to your EFS file system data.`

The following was the recommended action AWS told impacted customers to perform:
`To minimize the risk of disruption, we recommend you re-mount your EFS file system(s) using the EFS mount helper [2] (or manually apply the 'noresvport' option if you are unable to use the EFS mount helper) by October 1, 2023.`

That's all fine & dandy for anything mounting EFS via DNS, IP, etc, but ECS tasks configured to mount EFS does not have the option to configure these types of mount options from initial research. Please correct me if I am wrong.

The impacted ECS task mounts EFS via `efsVolumeConfiguration` defined in the task definition, as far as I am aware there is no means to pass the `noresvport` option in `efsVolumeConfiguration` config block. I am assuming `noresvport` would solve the problem as I only started experiencing this after the AWS maintenance period. Prior to this maintenance I had no issues with the ECS task mounting EFS and had done so many times.

Now the only way to get the ECS task to start & mount EFS without error during the initial provisioning process is for me to goto the instance and execute `docker system prune` after the previous task has exited. It's possible `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` can also resolve this problem, but I use the default value which if I understand correct is 3 hours. Although, I'd like emphasize that even with the default setting of `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` prior to Oct 1st this had no issue launching a fresh task on the same underlying EC2 host immediately after the previous task had exited.

Attempting to replace the impacted ECS task after getting one healthy via a deployment or via task replacement due to failure will result in the task being unable to launch with errors varying between a generic 'task failed to start' and a rarer but more valuable error that makes mention of EFS which unfortunately I can't share because the task history no longer is displaying the info despite only being a day or two old - however pulling from my memory i believe it is the same error the author saw that being:

 `Error response from daemon: create REDACTED: VolumeDriver.Create: mounting volume failed: Failed to locate an available port in the range [20049, 21049], try specifying a different port range in /etc/amazon/efs/efs-utils.conf`

Anyway, I have other nodes in my cluster but it's not being placed due to resource constraints so it is retrying tasks on the same underlying EC2 node. I imagine it would be fine on another node, but specifically in the scenario where ECS attempts to replace a task on the same underlying EC2 node this becomes a showstopper requiring manual intervention for me.

I haven't tested if `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` would solve this issue, but given the previous behavior of being able to launch & attach to EFS immediately I imagine you would be required to set a very small wait duration to get the old behavior back which doesn't sound ideal to me.

Again, I have my workaround in this scenario being `docker system prune`, but this behavior does seem to relate to the Oct 1st AWS change related to EFS and potentially to the issue mentioned by the author of this issue being ECS Agent not Releasing EFS Client Connections.

Here's a screenshot of EFS metrics showing the gap in connections while ECS is retrying and then the end of the gap is when I manually intervened w/ `docker system prune`:

<img width="1184" alt="Screen Shot 2023-10-04 at 2 19 15 PM" src="https://github.com/aws/amazon-ecs-agent/assets/101602611/26440c2a-2661-4ca8-ad09-9b1c6643491c">

I could be off-base here, but seeing the Author's scale and my scale (literally 1 task only) I would say there's an issue in ECS agent behavior with mounting EFS volumes.

CC: @amogh09 @mshober

**Comment by shawnh-burst** [comment]
Upgrading has not helped & now with the upgraded ECS agent docker system prune is not consistently working to unblock the EFS mounting preventing task start-up.

Additional error besides what's been reported already.

Error response from daemon: create MY_ECS_TASK_NAME: VolumeDriver.Create: mounting volume failed: Failed to resolve "MY_EFS_ID.efs.us-east-1.amazonaws.com" - check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. Attempting to lookup mount target ip address using botocore. Failed to import necessary dependency botocore, please install botocore first.

I have upgraded my ecs-agent to 1.75.3 and the behavior is actually worse due to docker system prune not being a sure fire way to help now. After some period of the error shared above repeating it will work, docker system prune seems to be ineffective now.

The task, EC2 host, and EFS are all in the same subnet. It fails sometimes on the identical host it then succeeds on. Security group is unchanged and allows port 2049 for NFS. Still seems like an issue here...

**Comment by mshober** [comment]
Hi @amogh09. Apologies for the late reply. Thanks for looking into this. 
> The connection count for the EFS volume matches the number of instances in my test setup regardless of the number of EFS tasks running on the instances... no matter how many tasks I start on the instance there is only one connection count in the metrics. That one connection stays until ECS Agent cleans up all the docker containers of the tasks (after ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION is elapsed).

Just to clarify my usage, the tasks that are placed on my EC2 Instances are triggered from the `RunTask` API. These are not ECS services being ran. Not sure if that effects how client connections are used.

But anyways, I haven't had any issues since lowering the `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` value. I'm good to close this issue if you have nothing else to add.

**Comment by mshober** [comment]
@shawnh-burst I don't think our issues are related. These links might be helpful though:
- https://repost.aws/knowledge-center/fargate-unable-to-mount-efs
- https://www.reddit.com/r/aws/comments/13vqgdr/ecs_cannot_mount_efs/

**Comment by exalted** [comment]
> Error response from daemon: create MY_ECS_TASK_NAME: VolumeDriver.Create: mounting volume failed: Failed to resolve "MY_EFS_ID.efs.us-east-1.amazonaws.com" - check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. Attempting to lookup mount target ip address using botocore. Failed to import necessary dependency botocore, please install botocore first.

FWIW; In my case, I fixed the issue underlying above error message by turning on DNS Hostnames on the VPC, which was, for whatever reason, turned off. (Reference: https://repost.aws/knowledge-center/ecs-problems-with-efs-dns-name)

**Comment by exalted** [comment]
> FWIW: In my case, I fixed the issue underlying the above error message by turning on DNS Hostnames on the VPC, which, for whatever reason, was turned off. (Reference: https://repost.aws/knowledge-center/ecs-problems-with-efs-dns-name)

Nope. That wasn't it… In my case, the problem was due to a race condition where the EFS filesystem wasn't fully ready to DNS-resolve quickly enough, so ECS tasks were dying because of it. The solution I opted for now is to create the EFS filesystem + mounts in a CloudFormation stack _before_ creating the ECS task definitions that depend on it.
