### ISSUE TITLE
Bind task to specific IP address

### ISSUE THREAD

**Issue by abatsakis** [aws/amazon-ecs-agent#426]
Hi all,

I was wondering if there are any plans in supporting the binding of a task to a specific IP address on the host that can e.g. provided at RunTask time similar to docker's  -p IP:host_port:container_port

This is very handy for instances with multiple interfaces on different subnets

**Comment by kiranmeduri** [comment]
IIUC you are asking on how can ECS tasks running on EC2 instances support ENIs. We are currently gathering requirements to support this and would love to understand more about your use-case. Is your case to assign one IP per task and have that IP constrained by policies defined in the VPC/Subnet/Security Groups? 

In the current system even if we support passing in IP in RunTask API, you need to know IP beforehand which is not true in RunTask case which doesn't take containerInstance as input. May be you meant StartTask API. Even in that scenario it is interesting to understand more about the end-to-end flow. 

Thanks for bringing this up.

-kiran

**Comment by samuelkarp** [comment]
@abatsakis We're working on attaching ENIs to tasks and allowing IP addresses per task.  Does the proposal in https://github.com/aws/amazon-ecs-agent/pull/701 address your use-case?

**Comment by adnxn** [comment]
@abatsakis We've released [task networking for containers](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-ecs-introduces-awsvpc-networking-mode-for-containers-to-support-full-networking-capabilities/) as proposed in #701. I'm closing this issue since we haven't heard back, but feel free to let us know if this addresses your use case.
