### ISSUE TITLE
Send stdout and stderr to different destinations

### ISSUE THREAD

**Issue by CameronGo** [aws/amazon-ecs-agent#449]
I do not know enough about the inner workings of the ecs-agent as it relates to the docker log capabilities to know what this would involve, but I would like to be able to send stderr and stdout to different destinations.  In particular, in my case to different Cloudwatch Log groups.  I originally assumed the ecs-agent simply made use of the docker run syntax and so submitted this request to the docker project:
https://github.com/docker/docker/issues/24386

After thinking about one of the comments related to the docker remote APIs, I realized it is possible the ecs-agent was already using these and so this might be possible in ECS with no enhancements from the docker project.

I am currently running the v1.10 ecs agent on Ubuntu 14.x and docker 1.11.2.

**Comment by samuelkarp** [comment]
@CameronGo, thanks for opening this! I just responded to you on https://github.com/docker/docker/issues/24386.  ECS just uses the Docker logging drivers through the Docker Remote API, so the right place to add this feature would be in the logging driver itself.  I'm going to close this issue in favor of the issues on the Docker project, since that's where the logging driver lives.
