### ISSUE TITLE
could not start Agent: oci runtime error: rootfs does not exist

### ISSUE THREAD

**Issue by akvadrako** [aws/amazon-ecs-agent#464]
When using the stock AMI 2016.03e with a user-data script that restarts docker, the ecs-agent fails to start. `start ecs` continues to fail until docker is manually restarted sometime later. The behaviour is sporadic and only occurs on first boot, so it's difficult to debug. The error message given is:

```
2016-07-27T12:13:30Z [ERROR] could not start Agent: API error (500): rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker/devicemapper/mnt/4cfe020c0f8658ca94528b36538a0a47098b915059a6d06932b0b166d07bfcf9/rootfs\") does not exist"
```

Here are all the relevant logs, which also shows which commands are run in user-data:

https://gist.github.com/akvadrako/2617a080b267e854feffd5f9d79b9ba1

The same error message shows up in: #419

**Comment by akvadrako** [comment]
One point in favour of this being a bug instead of user error: restarting the docker service inside the user-data script is described on the AWS blog as the proper way to get an NFS mount recognised inside the containers, which is also our use case:

https://aws.amazon.com/blogs/compute/using-amazon-efs-to-persist-data-from-amazon-ecs-containers/

**Comment by richardpen** [comment]
@akvadrako Thanks for letting us know, as per the comments in #419, docker restart in user data script may causes issue because the docker daemon was still initializing and it will left the Docker storage metadata in a broken state. So the docker should be restarted after the docker initialized. In order to use the mounted volume, one solution is to mount the volume before docker started. Then docker won't need to be restarted. You can do this by combine standard user-data and boothooks(or other cloud-init types) using [MIME/Muli-Part](http://cloudinit.readthedocs.io/en/latest/topics/format.html). A tested example of the user data file looks like below. The boothook part will be executed before docker start.
```
Content-Type: multipart/mixed; boundary="===============BOUNDARY=="
MIME-Version: 1.0

--===============BOUNDARY==
MIME-Version: 1.0
Content-Type: text/x-shellscript; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="standard_userdata.txt"

#!/bin/bash
echo "user data script part"


--===============BOUNDARY==
MIME-Version: 1.0
Content-Type: text/cloud-boothook; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="boothook.txt"

#cloud-boothook
echo "cloud boothook part"
mkdir /nfs
yum -y install nfs-utils
mount -t nfs4 -o vers=4.1 172.31.23.82:/ /nfs

--===============BOUNDARY==--
```
An alternative way is to restart the docker after the docker initialized, by adding `docker ps` before the `service docker stop` command instead of just `sleep 5s`, it will wait until the docker is initialized. And then restart the docker should be fine.
We will update the [document](https://aws.amazon.com/blogs/compute/using-amazon-efs-to-persist-data-from-amazon-ecs-containers/) shortly, please let me know if that solve your problem, thanks.

**Comment by akvadrako** [comment]
@richardpen - I have been testing for a few days with the NFS mount in the bootcmd section, though I'm actually using #cloud-config, which seems a bit cleaner. If that continues to work and the documentation is updated, than my problem is solved.
