### ISSUE TITLE
Future of ECS agent

### ISSUE THREAD

**Issue by philtay** [aws/amazon-ecs-agent#466]
Now that Docker 1.12 is released, does it still make sense to use the ECS agent?
The [Docker Built-In Orchestration](https://blog.docker.com/2016/07/docker-built-in-orchestration-ready-for-production-docker-1-12-goes-ga/) looks already quite superior and [Docker for AWS](https://beta.docker.com/docs/aws/) doesn't use ECS at all.

**Comment by djenriquez** [comment]
Hi @philtay, I would say that "superior" is just an opinion. There are things ECS offers that swarm does not. Swarm and ECS handle clusters and container management differently. We found it easier to wrap ECS into a pipeline because of its API and the fact that it has a console UI that doesn't cost anything additional.

Swarm is pretty awesome, however they monetize on their UI management, which we found to be pretty important in order to empower use from developers.

Again its all opinion, but until swarm offers that UI and an easier to use remote API, it lags behind ECS in terms of industrial level readiness.

**Comment by cbbarclay** [comment]
Customers want to find a simple way to run distributed applications within containers and we want to make AWS the best place for customers to run any Docker application. The general way to solve this is to provide a way to manage a cluster of servers/instances and then schedule/orchestrate containers against that cluster. At AWS customers can choose from options such as ECS, Kubernetes, Mesos, and Swarm; we encourage our customers to use the solution that best works for them.
 
This GitHub repo is for the Amazon ECS agent, so I can tell you a bit more about its features and benefits as well as answer any technical questions you may have. Amazon ECS is a fully managed container management service that provides a robust, secure, scalable platform for customers to run containerized applications in production. To that end, ECS has delivered features like IAM roles for tasks and task auto scaling to help customers run their microservices. AWS automatically manages your cluster (there are no “master nodes” for key/value storage that have to do consensus among the nodes) and we provide schedulers that allow you to easily deploy containerized applications across availability zones that can auto scale and load balance themselves. You just have to think about your application and your application’s architecture, not the operations of the cluster management and schedulers.
 
I hope this helps. Please reach out with additional questions.
