### ISSUE TITLE
Log details

### ISSUE THREAD

**Issue by sourcec0de** [aws/amazon-ecs-agent#5]
### Are there any logs that could help debug tasks?

I found the agent logs here `/var/logs/ecs/`
But there isn't anything useful there to help me debug the command I've run below.

```json
[
  {
    "environment": [
      {"name":"SLACK_URL", "value":"URL"}
    ],
    "name": "taskName",
    "image": "imageId",
    "cpu": 512,
    "memory": 1884,
    "command": ["curl","-XPOST", "$SLACK_URL", "-d'{\"text\":\"Something\"}'"],
    "essential": true
  }
]
```

**Comment by sourcec0de** [comment]
Never mind answered my own question. By default `ecs-agent` writes its logs to a mounted volume. On host machine the logs are located under `/var/logs/ecs/`

**Comment by euank** [comment]
Your assumption that that path is within the container is correct. By default, the init script launches it with that directory mounted to `/var/log/ecs` on the host. You should be able to find the agent's full logs at `/var/log/ecs/ecs-agent.log`. You should also consider checking `docker ps -a` to see if it was created at all, and if present, use the normal `docker logs` and `docker inspect` information to get more information about the failure.

When you say `docker attach` caused the agent to crash, can you go into more detail? I wasn't able to reproduce it in my brief attempt. Note that, by default, `docker attach` will proxy throgh ctrl-c as a sigterm, so if it exited when you hit ctrl-c that's expected behavior (you can use `docker attach --sig-proxy=false` to avoid that behavior).

Let me know if you have any other questions about debugging your issue or if you have more information about your `docker attach` issue.

Best,
Euan

**Comment by sourcec0de** [comment]
@euank `docker ps -a` is exactly what I needed. My path was configured correctly. Bash was exiting with status 127 meaning command not found. Another command I was running was `bash -c 'curl'`. When sending the command to the agent using the ECS api I wrapped the last argument with a string.

```json
[
  {
    "command": ["bash","-c", "'curl'"]
  }
]
```

The extra quotes on the last argument ended up being unnecessary and what was causing my issue.


As for the crash issue your explanation makes sense.

# Solution `docker ps -a`
### Notes

I think it would be useful for ecs to implement a central logging system. Is this on the feature road map? This would be useful so people don't have to ssh into the machine and check this manually.

**Comment by sourcec0de** [comment]
### Future Reference

Once you obtain a container id or name you can use it to obtain the command output
`docker logs <containerId | containerName>`
