### ISSUE TITLE
More friendly to CloudWatch Logs 

### ISSUE THREAD

**Issue by hasimo** [aws/amazon-ecs-agent#514]
I would like to watch the `ecs-agent.log` throuth CloudWatch Logs to get alert of
- when Task stopped with non-zero exist status.
- when Task stopped with `Reason` (like `CannotPullECRContainerError`) 

The logs  are like

```
2016-08-29T01:37:44Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-east-1:347956181928:task/3e98beb7-c665-499b-9992-fecff91d2ff4 postfix -> STOPPED, Reason CannotPullContainerError: Error: image hoge not found, Known Sent: NONE"
2016-08-29T04:40:37Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-east-1:347956181928:task/80a977ec-6cd2-4989-963b-403c937f62c9 rake -> STOPPED, Exit 1, , Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:us-east-1:347956181928:task/80a977ec-6cd2-4989-963b-403c937f62c9 rake -> STOPPED, Exit 1, , Known Sent: RUNNING"
```

Amazon CloudWatch Logs support  JSON Log and  Space-Delimited Log .
ecs-agent.log is text format. so I can use  Space-Delimited Log filter syntax.
But currently it is not well-formatted as  Space-Delimited Log.

it will be splitted to 
- 2016-08-29T01:37:44Z
- [INFO]
- Adding
- event
- module="eventhandler"
- change="ContainerChange:
- arn:aws:ecs:us-east-1:347956181928:task/3e98beb7-c665-499b-9992-fecff91d2ff4
- postfix
- ->
- STOPPED,
- Reason
- CannotPullContainerError:
- Error:
- image
- hoge
- not
- found,
- Known
- Sent:
- NONE"

It is heard to extract values.

so would be great ecs-agent.log format to be more friendly to CloudWatch Logs.

**Comment by kiranmeduri** [comment]
Hello @hasimo,

For the use-cases you provided following mechanisms may be better than log-scanning,

- Handle ECS events from AWS CloudTrail, see http://docs.aws.amazon.com/AmazonECS/latest/developerguide/logging-using-cloudtrail.html
- Use ecs-agent's introspection APIs to watch container/task states, see http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html

In our view scanning logs is fragile, esp. ecs-agent.log due to changes which we may make in future. 

Thanks,
-Kiran

**Comment by samuelkarp** [comment]
@hasimo We recently launched an [event stream for ECS clusters](https://aws.amazon.com/blogs/compute/monitor-cluster-state-with-amazon-ecs-event-stream/) delivered through CloudWatch events.  The event stream includes information about tasks, including details about tasks exiting.  You can find documentation on the task events [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html#ecs_task_events).  We recommend consuming the event stream instead of parsing the logs emitted by the ECS agent.  I'm going to close this issue for now, but please feel free to reopen it if you have further questions about monitoring your ECS tasks.

**Comment by acurvers** [comment]
@hasimo did you manage to get alerts on  CannotPullContainerError
i need the same, on ECS fargate i looked into the events solution proposed here, but i dont think a event is published when the containers runs into a CannotPullContainerError
