### ISSUE TITLE
Handle deprecation of HostConfig when Starting Docker container

### ISSUE THREAD

**Issue by kiranmeduri** [aws/amazon-ecs-agent#529]
As per https://docs.docker.com/engine/deprecated/#hostconfig-at-api-container-start and https://github.com/fsouza/go-dockerclient/issues/537, starting container with HostConfig was deprecated since v1.10 and removed in v1.12.

**Comment by aaithal** [comment]
@kiranmeduri we don't use `HostConfig` in [task engine](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_task_engine.go#L574) or when interacting with [docker client](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_container_engine.go#L422) for starting containers. It's only being used in [create](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_task_engine.go#L550). Seems like this is already handled in the agent?

**Comment by aaithal** [comment]
Went through code base again. We switched to using `HostConfig` in `CreateContainer` instead of `StartContainer` back in May 2015 with this [commit](https://github.com/aws/amazon-ecs-agent/commit/707550d415f8731c2194642cdbea2ea6ceeaacf7), which was released with [v1.1.0](https://github.com/aws/amazon-ecs-agent/tree/v1.1.0). Resolving.
