### ISSUE TITLE
New Version of task not running as old version is not getting stopped

### ISSUE THREAD

**Issue by mjoshi89** [aws/amazon-ecs-agent#541]
Hi Team,

We are facing an issue in our ECS cluster that whenever we are trying to deploy a new version of a service `Number of task ==> 5, Minimum percentage ==> 50 , Maximum percentage ==> 200` not all the new versions of the service is getting started. Sometimes only 1 or 2 new versions of the service start as the old versions are not being stopped by the ecs-agent. We can see that the desired state of old version is stopped but it remains in that state until and unless we forcefully stop the old version or spin up a whole new cluster.

`Docker version 1.11.1, build 5604cbe/1.11.1`
`Version":"Amazon ECS Agent - v1.10.0 (9a1b0f6)`

Could you please help us in this issue? 

Thanks

**UPDATE** --> This is the state the old version services are stuck with:

`LAST STATUS`                                                                 `DESIRED STATUS`
`RUNNING (Host EC2 (instance i-e5faf3f2) stopped.)`  `STOPPED`

The instance id in question is the id of old instance that used to be a part of this cluster but was stopped some time back to fix this issue.

**Comment by richardpen** [comment]
@mjoshi89 From what you said, seems agent or docker didn't stop the old version container. But this shouldn't block the new version container to deploy. In order for us to debug the root cause here, could you confirm the following question:
By "forcefully stop the old version" does that mean you login into the instance and run the `docker stop` to stop the container? 

How long did you see this behavior before you forcefully stop the old version container?

Also in order for us to debug the root cause here, could you share me the following information to penyin at amazon.com:
* ecs-agent debug logs(located in /var/log/ecs/)
* the docker logs(/var/log/docker)
* AWS account id
* Cluster and service name that experienced this problem

If there is anything like credentials or auth tokens in the logs (from environment variables or command/entrypoint), please redact them. Thanks.

**Comment by mjoshi89** [comment]
Hi @richardpen ,

Thanks for looking into this.

`By "forcefully stop the old version" does that mean you login into the instance and run the docker stop to stop the container?`

By forcefully, I mean click on the old version of task definition that is running in the console and clicking "stop". When I do that the old service version stops and the required new version of service comes up. Since we have 3 ecs-instances registered in the cluster sometimes we even restart the instances one by one, as we have enough resources in even 2 instances to support our production load.

I don't have the logs at this point of time from the instances as they were restarted last time,  however we have a deployment scheduled in production next week and then this issue might probably reoccur. I will try to gather all the required information then and pass on here.

Thanks

**Comment by joezopenroad** [comment]
Hello @richardpen, I'm also seeing this behavior on one of our clusters.

For example, lets say I have a desired task count of 2. When I push a new image to ECR then create a new task definition 1 container (the old task) will be "deregistered" on my instance and eventually stopped but a total of 3 containers will be running (2 with the new definition and 1 with the old). All of these instances are considered "Healthy" on the ELB so traffic is routed to them.

This is an issue of course because now we have users being routed to two different versions of our  service. The only work around I've found is like @mjoshi89 explained, by stopping the task on the cluster.

Your help is appreciated.

**Comment by markriggins** [comment]
I've seen this happen when the ecs-agent is out of date.  Are your instances running the latest release?

**Comment by mjoshi89** [comment]
As an update, we managed to resolve this issue. In our cluster we had different versions of ecs-agents running in the machine. After we made the ecs-agent version same across all the registered instances this issue stopped.

@joezopenroad could you also check if you have any mismatch in the ecs-agent versions being used in the instances?

**Comment by markriggins** [comment]
you're welcome

**Comment by joezopenroad** [comment]
👍

**Comment by NeelAurea** [comment]
Updating the agent version resolved a similar issue I ran into. Thanks for the suggestion

**Comment by atulmy** [comment]
[Newbee to AWS]

I'm facing similar issue where after " Deploy Amazon ECS task definition" step from GitHub, the new service task is being created but the old task is never terminated. Have to manually stop it for the GitHub action to finish, otherwise the GitHub action it is stuck in pending state.

Does updating agent version solves this? Also, what are the steps to update agent version? Any help would be appreciated.
