### ISSUE TITLE
encountered error "AGENT"

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-agent#553]
I know you have a workaround upon http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#service-event-messages to ssh in and restart the agent. But really, that's not good enough.

We regularly hit this issue at work & it would be nice if the agent could please be more reliable.
https://devops.spuul.com/2016-10-11/encountered_error_AGENT/

If I am missing something, please let me know.

**Comment by kiranmeduri** [comment]
I agree with your observation that ssh'ing and restarting agent is not scalable. It is at best useful for small cluster sizes (of say 10s of instances). However I would like to understand if **Agent connected false** is a transient issue you are observing or if agent is just hung. It will be better to understand the root-cause. If possible can you share the logs of one such instance. You can share them here or send it to meduri at amazon.com

Thanks

**Comment by alvarow** [comment]
I would love to get to the bottom of this as well... the agent needs to be robust, else I will need to look for another solution, ECS agent is basic functionality, that needs to be rock solid.

I will share some of my logs. Apparently around 12:22am EST things went bad until I restarted the whole instance around 11:30am.

[ecs-logs.zip](https://github.com/aws/amazon-ecs-agent/files/537666/ecs-logs.zip)

**Comment by kaihendry** [comment]
It's a pain ssh-ing into the instances to poke around. I've just created https://static.spuul.com/devops/2016-10-21/cluster-inspect.sh to help out with this in future. If you know any other debug tricks, please let me know.

**Comment by kaihendry** [comment]
I noticed that our instance Agents disconnected when they ran out of disk space.

https://devops.spuul.com/2016-10-25/ECS_downtime/

So https://github.com/aws/amazon-ecs-cli/issues/172 is related.

I managed to pull off the logs and there does seem a number of issues:
https://static.spuul.com/devops/2016-10-25/ecs-agent-log.tar.xz

For example the logs effectively filled the disk space. There is 3GB of uncompressed logs featuring **dial unix /var/run/docker.sock: socket: too many open files**

Can I throw in a recommendation to try out systemd's `journalctl` where this log exhaustion case can be mitigated.

**Comment by richardpen** [comment]
@kaihendry This seems the same issue with #517. I have responded there. 

For the original issue here, agent may periodically disconnect and reconnect back to ECS, so you may see the transient error "Agent". If that's not the case which means agent disconnected for too long (more than 5 mins), could you please provide us the logs of agent for us to root cause the problem? You can publish here, or send it directly to me at: penyin (at) amazon.com

Thanks

**Comment by simonbrady** [comment]
We see frequent temporary agent disconnects (even with 1.13.0) correlated with log entries like this:

```
2016-11-15T02:12:03Z [INFO] Error from acs; backing off, err: unexpected EOF
2016-11-15T02:14:18Z [INFO] Creating poll dialer, proxy: proxy.example.com:3128
```

We only observe these when agents are connecting from private subnets via an outbound proxy server, but I haven't been able to track down the root cause yet - tcpdump shows the proxy sending a TCP FIN, but there's nothing of note in the proxy logs and the agent uses the CONNECT method so traffic capture doesn't help. We're running Squid 3.3.8 behind an internal ELB, so there are a few obvious variables for me to tweak when I get time.

Regardless of my site-specific issue, the backoff time in agent/acs/handler/acs_handler.go seems to be chosen between 250ms and two minutes (odd that the above example was 2m15s, but I've only taken a cursory glance at the source). Two minutes is quite a long time for task submission to potentially fail with AGENT status, especially when in my case the agent can successfully reconnect in under a second if it so chooses. I'm sure there was a good reason for choosing that upper bound, but is it worth considering some sort of exponential backoff rather than a uniformly random time so the agent reconnects quickly in the easy cases?

**Comment by simonbrady** [comment]
For anyone else who stumbles across this, the cause of my disconnects was the ELB [idle timeout](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html) killing agent connections after 60 seconds. Increasing the timeout works around the problem, although it would be nice if there was a way to make the agent send keep-alives back to the mothership.

**Comment by samuelkarp** [comment]
@simonbrady Thanks for sharing your findings!

> Regardless of my site-specific issue, the backoff time in agent/acs/handler/acs_handler.go seems to be chosen between 250ms and two minutes [...] is it worth considering some sort of exponential backoff rather than a uniformly random time so the agent reconnects quickly in the easy cases?

It is an exponential backoff, but we could probably tune the parameters better.  Right now it starts at 250ms and maxes at 2m + a bit of jitter (that's where the 2m15s came from) and multiples the previous backoff by 1.5.

> For anyone else who stumbles across this, the cause of my disconnects was the ELB idle timeout killing agent connections after 60 seconds. Increasing the timeout works around the problem, although it would be nice if there was a way to make the agent send keep-alives back to the mothership.

There are heartbeat messages sent by ECS when the connection is idle (the current setting is for 60s), but it sounds like an idle timeout on your load balancer at 60s might be causing a race (or the idle timeout on the load balancer might be always winning).  You'll want to have an idle timeout on your load balancer/proxy longer than 60s.  Please let us know if you continue to run into problems.

**Comment by samuelkarp** [comment]
@kaihendry @alvarow @simonbrady Are any of you still having issues?

**Comment by samuelkarp** [comment]
I'm closing this for now since we haven't heard back from anyone in a while.  Happy to re-open this if anyone responds.

**Comment by alvarow** [comment]
My apologies, Samuel, for the late reply. Yes, things seem improved, I haven't seen the error again since, but I did bump the proxy load balancer timeout up as well. Thank you anyway.

**Comment by samuelkarp** [comment]
@alvarow Glad it's working now!

**Comment by simonbrady** [comment]
Hi Samuel, my apologies also for the slow response. Increasing the ELB timeout solved the problem here as well - I set mine to 300s but a colleague reports success with a 120s setting, which makes sense given what you said about the 60-second keepalive (although perhaps it's worth lowering that slightly to avoid the race at the default ELB setting?). Thanks for your help!

**Comment by samuelkarp** [comment]
@simonbrady Thanks for confirming!

**Comment by geerlingguy** [comment]
I had a 120s timeout, and still hit this a couple of times in the past few months. Simply rolling all the instances, or logging into the ECS instance in question then running `sudo service ecs restart` seemed to fix it.

**Comment by kurtwheeler** [comment]
I was upgrading the size of my instances and when they came back online the tasks wouldn't start up because of "AGENT"... The docs recommended recreating the instances with a different AMI or sshing onto each instance and running the update command here. Is this the only time this can happen or could the ECS agent get an update at any time and go down? The potential of this happening at any time seems like an extremely unacceptable event to regularly happen.

**Comment by samuelkarp** [comment]
> I was upgrading the size of my instances and when they came back online the tasks wouldn't start up because of "AGENT"

ECS does not support resizing instances today; you'll see some errors in the agent's log file indicating this.

> could the ECS agent get an update at any time and go down?

The ECS agent does not itself automatically update.  On Amazon Linux and on the ECS-optimized AMI, security updates are applied at first boot and some of those may cause the agent to receive an update.

**Comment by kurtwheeler** [comment]
Oh good to know. Thanks @samuelkarp
