### ISSUE TITLE
ECS Task stopped with Exit Code 139 

### ISSUE THREAD

**Issue by fshahnaz** [aws/amazon-ecs-agent#625]
ECS cluster lists multiple containers under stopped list that were stopped with following info
- **Stopped reason** Essential container in task exited
- **Details** Exit Code	139

Can someone please offer any insight into what that code means?

**Comment by samuelkarp** [comment]
Exit code 139 typically indicates that your program had a segmentation fault and was killed by the kernel.  Exit codes starting with 128 usually indicate the receipt of a signal, which you can get by subtracting 128 from the exit code: 139 - 128 = 11 (`SIGSEGV`).  See [general information on special exit codes](http://www.tldp.org/LDP/abs/html/exitcodes.html).

I'm going to close this here since this is a general Linux question rather than something ECS specific.

**Comment by opinionmachine** [comment]
I disagree. It'll be because ECS is failing to do something that works elsewhere. I e at the very a bug in the documentation, but most likely in the logging or something, that led somebody to google "ecs Exit Code 139" because that's all the got.  I know a key design goal of ECS is to completely hide any useful information or feedback of what's going wrong so that the customer always is completely blind, but it might be a nice change of pace to get some information occasionally.

**Comment by nayana-mathradan** [comment]
I'm getting the same error Randomly on ECS Fargate. And there are no error logs! I did setup cloud watch logs. But couldn't  find any error log created for that execution. And this simple works fine when triggered some other time. Can someone please help with a proper solution?

**Comment by opinionmachine** [comment]
Hah! I got this error again, and came upon this question five years after I commented on it last.  No idea how i fixed it the last time, but I can say this time it's also working everywhere else than in ECS Fargate, so my comment still stands

**Comment by abhijeetgaonkar** [comment]
Hello @opinionmachine, We’re experiencing the same issue. Our image works perfectly in one AWS account, but fails in another, even though we’re using the exact same image. Were you able to find a solution?

**Comment by opinionmachine** [comment]
Actually no, it can be whatever breaks early enough in the process. 

It can be missing rights in a task role - I had that, after fixing that I got that a docker image was the wrong architecture (I uploaded an arm64 image that I claimed was amd64). Eventually I fixed it, but fundamentally, just try and get logging in the ECS task and hope for the best.

**Comment by kabirimouad** [comment]
@abhijeetgaonkar please refer to this [link](https://github.com/nodejs/node/issues/60882) if you are using node. I had similar issue because I was using the latest image, I downgraded and so far it's working fine.
