### ISSUE TITLE
ecs-agent log level for elastic beanstalk / docker host

### ISSUE THREAD

**Issue by tcco** [aws/amazon-ecs-agent#639]
Very simply put I am trying to change the log level of the ecs agent on elastic beanstalk due to memory issues. 

Setting docker based elastic beanstalk env variables does not propagate to the host because the variables are supplied to docker containers. This link is reference for this issue. 

http://stackoverflow.com/questions/28298101/elastic-beanstalk-environment-variables-for-docker-host

I have tried their solutions but they are either session based. If I ssh in the env vars are not set  but I can run the scripts themselves and they do set variables from eb config. So I have landed on setting env variables by exporting in the bashrc for both ec2 and root. 

This permanently sets env vars however ecs still logs INFO, WARN events even after setting ECS_LOGLEVEL=CRIT

**Comment by samuelkarp** [comment]
@tcco I'm not as familiar with Multicontainer Elastic Beanstalk as I am with ECS, but I think you will want to append `ECS_LOGLEVEL=error` to `/etc/ecs/ecs.config` and restart ecs-init with `sudo stop ecs; sudo start ecs` using [.ebextensions](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands) (I would advise picking `error` instead of `crit` as the log level or you won't actually see error information in the log; almost nothing is logged at `crit` level).  The best place to ask questions like this about Elastic Beanstalk is on the [AWS Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).

**Comment by tcco** [comment]
@samuelkarp Great thanks for the information
