### ISSUE TITLE
How to send ECS container logs to logstash using gelf driver

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#642]
Hello,

I am trying to send my ECS container logs to my logstash container. Please let me know how it is possible using gelf driver.

Regards,
Raja

**Comment by maartenvanderhoef** [comment]
Have you tried the GELF input plugin ?

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-gelf.html

**Comment by rajasekaran07** [comment]
@maartenvanderhoef 

Thanks for your help...

I have configured my task with gelf driver also set option for logstash server.

PFB my json task file. also I run my logstash as a docker container in another ec2 instance by below command. But my task is not running. Kindly let me know what was wrong in my configuration.

sudo docker run -d --publish 2233:2233/udp --name logstash logstash

{
  "requiresAttributes": [
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.gelf",
      "targetId": null,
      "targetType": null
    },
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19",
      "targetId": null,
      "targetType": null
    }
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:855158544446:task-definition/mytestecs:14",
  "networkMode": "bridge",
  "status": "ACTIVE",
  "revision": 14,
  "taskRoleArn": null,
  "containerDefinitions": [
    {
      "volumesFrom": [],
      "memory": 100,
      "extraHosts": null,
      "dnsServers": null,
      "disableNetworking": null,
      "dnsSearchDomains": null,
      "portMappings": [
        {
          "hostPort": 5000,
          "containerPort": 5000,
          "protocol": "tcp"
        }
      ],
      "hostname": null,
      "essential": true,
      "entryPoint": null,
      "mountPoints": [],
      "name": "pythonapp",
      "ulimits": null,
      "dockerSecurityOptions": null,
      "environment": [],
      "links": null,
      "workingDirectory": null,
      "readonlyRootFilesystem": null,
      "image": "training/webapp",
      "command": [],
      "user": null,
      "dockerLabels": null,
      "logConfiguration": {
        **"logDriver": "gelf",
        "options": {
          **"syslog-address": "IPADDRESS:2233"****
        }
      },
      "cpu": 25,
      "privileged": null,
      "memoryReservation": null
    }
  ],
  "placementConstraints": [],
  "volumes": [],
  "family": "mytestecs"
}

Regards,
Raja

**Comment by maartenvanderhoef** [comment]
It's not syslog-address it's gelf-address=udp://host:12201

**Comment by rajasekaran07** [comment]
But I am using logstash as my log management tool. Please let me know how to send my container logs to logstash server.

Regards,
Raja

**Comment by maartenvanderhoef** [comment]
Please read the documentation, it's very straight forward. You can setup logstash to receive GELF, and you would need to send GELF to your logstash server, not syslog. Good luck.

**Comment by rajasekaran07** [comment]
@maartenvanderhoef thanks for your help.. My task is running now, But I dont know where my log files will store. I have checked the below path in my logstash server  but there is no files available.

ls /var/lib/logstash/
ls /var/log/logstash
ls -a /var/log/logstash
ls -a /var/log/logstash
ls /var/lib/logrotate/

Regards,
Raja

**Comment by samuelkarp** [comment]
Documentation for the `gelf` driver is in [the Docker documentation](https://docs.docker.com/engine/admin/logging/overview/#/gelf-options).  Using the `gelf` driver with ECS is the same as using the driver with Docker directly; you can test out the options you intend to use with `docker run --log-driver gelf --log-optgelf-address=udp://host:port` in your development environment.

I'm going to close this for now as it seems like you're having trouble with gelf/Logstash rather than ECS.  If you're having trouble getting Logstash to work, I'd recommend reaching out to the Logstash project directly.  If you're having trouble with ECS specifically we're happy to help.

**Comment by rajasekaran07** [comment]
@samuelkarp, @maartenvanderhoef  Thanks for your commands. I have a query in ECS configuration. Please let me know we need to do any changes to enable gelf log driver. 

To use awslog driver we need to pass the below environment variable while starting ecs agent.

--env=ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"awslogs\"]

Regards,
Raja

**Comment by samuelkarp** [comment]
To enable `gelf`, you'd need to set `ECS_AVAILABLE_LOGGING_DRIVERS` to include `gelf`.  If you're setting this via `docker run`, it would look like `--env='ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs","gelf"]'`.  Note the single quotes, which are important because shells may try to expand things inside square brackets.  This is documented in [the README](https://github.com/aws/amazon-ecs-agent/blob/master/README.md).

**Comment by rajasekaran07** [comment]
Can I use this format ?

--env=ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"awslogs\”,\"gelf\"] \

**Comment by rajasekaran07** [comment]
I was updated /etc/ecs/ecs.config file for gelf driver.

ECS_CLUSTER=mychecklog
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","fluentd","gelf","awslogs"]

I was updated this by passing user data in Cloud formation template.

Regards,
Raja
