### ISSUE TITLE
Question on docker run command for ecs-agent

### ISSUE THREAD

**Issue by imkheong** [aws/amazon-ecs-agent#643]
Quoting from README.md, the suggested command to run ecs-agent is 

> $ docker run --name ecs-agent \
>     --detach=true \
>     --restart=on-failure:10 \
>     --volume=/var/run/docker.sock:/var/run/docker.sock \
>     --volume=/var/log/ecs:/log \
>     --volume=/var/lib/ecs/data:/data \
>     --net=host \
>     --env-file=/etc/ecs/ecs.config \
>     --env=ECS_LOGFILE=/log/ecs-agent.log \
>     --env=ECS_DATADIR=/data/ \
>     --env=ECS_ENABLE_TASK_IAM_ROLE=true \
>     --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
>     amazon/amazon-ecs-agent:latest

It happens occasionally that one of my EC2 instances in an ECS cluster become 'agent disconnected' according to the AWS ECS console web UI. Note: The t2.micro instance was running a 600mb soft/900 mb hard limit container, and a few core containers including an ecs-agent container, a fluentd-agent for logging, a consul agent and a registrator for consul registration as Docker container. These containers are started by means EC2 Launch Configuration and by means of providing userdata.sh to the EC2 Launch Configuration. No other containers created on the failed EC2 instance.

When the EC2 instance become 'agent disconnected', my sys admin would terminate the instance, relaunch a new instance using our userdata.sh to ensure the instance installs Docker and run all the core containers aforementioned.

Noticing from the docker run command quoted above that restarts takes place on-failure up to 10 retries. This seem to suggest that ecs-agent will not get a restart when the EC2 instance restarts.

I would like to know if it is better to run ecs-agent using `restart=unless-stopped` so that ecs-agent would automatically restart in the event that EC2 instance restarts, so that ecs-agent get restarted each time a EC2 instance restarts?

Thank you in advanced.

**Comment by nmeyerhans** [comment]
Hi @imkheong. We don't recommend the "unless-stopped" restart policy because there are scenarios in which the ECS Agent will exit with a "terminal failure" should not be retried. The restart limit associated with the "on-error" policy ensures that the agent doesn't continuously retry an operation that can never succeed.

In the ECS Optimized AMI, we use the [ecs-init](https://github.com/aws/amazon-ecs-init) package to ensure that the agent is started automatically when an instance boots. You may wish to consider that package in your environment. Alternatively, we recommend something like `upstart`, `systemd`, `runit`, or similar process managers.
