### ISSUE TITLE
How to port mapping while using service autoscale policy

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#646]
Hi Team,

While applying service autoscaling policy most of the time port conflict will occur. PFB,...

![image](https://cloud.githubusercontent.com/assets/19193992/21448898/94c4f9ca-c90d-11e6-9d92-32c942c52f74.png)

service mytestautoservice was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 76b7ebea-8ead-4c36-8640-f1844c10ef04 is already using a port required by your task. For more information, see the Troubleshooting section.

Kindly someone suggest what is the best way to avoid this port conflict.

Regards,
Raja

**Comment by nmeyerhans** [comment]
Hello @rajasekaran07. It appears as though you have configured a "static" port mapping for this container definition in your ECS task definition. In this case, the given host port is mapped directly to your container's port. An example might be that you've mapped host port 80 to container port 80. It's impossible to run a second instance of the container on the same host because there would be contention for the mapped port. Only one service can listen on host port 80 at a time. If you wish to run multiple instances of a given container on a single EC2 instance, you should consider "dynamic" port mapping. This would allow your service to run on multiple host ports, e.g. 32768 and 32800.

Please refer to the "portMappings" section of the [ECS container definitions documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions) and [Docker's port mapping documentation](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#/connect-using-network-port-mapping) for more information. You may also find the [service load balancing](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html) documentation useful, as it describes techniques to use the AWS Application Load Balancer to route traffic to your service when dynamic port mapping is in use.

**Comment by rajasekaran07** [comment]
@nmeyerhans Thanks for sharing the details. but we are running 10 different containers in same ec2 instance if we use dynamic port allocation for all it will be a problem for ELB to identify the exact port.

Regards,
Raja

**Comment by agalazis** [comment]
use alb
