### ISSUE TITLE
[feature request]Support nvidia-docker on GPU instance

### ISSUE THREAD

**Issue by chenliu0831** [aws/amazon-ecs-agent#656]
Recently we were manually running containers with `nvidia-docker` on GPU instance. Since `nvidia-docker` should be a thin wrapper of docker it'll be great if it could be support natively by ECS.

**Comment by richardpen** [comment]
@chenliu0831 Thanks for reaching out to us, this seems to be the same as #433, please track there for updates. Also you can find instructions on running GPU workloads on ECS with CloudFormation in this post [Orchestrating GPU-Accelerated Workloads on Amazon ECS](https://aws.amazon.com/blogs/compute/orchestrating-gpu-accelerated-workloads-on-amazon-ecs/).

Thanks,
Richard

**Comment by chenliu0831** [comment]
@richardpen Thanks for responding. If I understand correctly, `nvidia-docker` could make use of GPU driver on the host whereas #433 and Amazon's sample will require driver be built into the container. So IMHO this issue isn't strictly the same with #433, but those are definitely workarounds.

**Comment by milesgranger** [comment]
I second this. There are ways to work around this indeed. However, having the option for the end user to launch an image using `nvidia-docker` (for GPU instances) would alleviate a lot of development time and potential for errors; namely when drivers are inevitably changed. 
Thank you.

**Comment by AKSHAYUBHAT** [comment]
Can we just `alias nvidia-docker docker` in the cloud_init / boot hook using user data?

**Comment by AKSHAYUBHAT** [comment]
Also AWS Batch has instructions for creating an AMI with nvidia-docker and ECS agent. 

http://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html

Though its no clear with AWS batch uses nvidia-docker or just docker.

**Comment by samuelkarp** [comment]
> Can we just alias nvidia-docker docker in the cloud_init / boot hook using user data?

That won't have the effect of making ECS support `nvidia-docker`.  ECS integrates with the Docker Remote API, while `nvidia-docker` is a wrapper around the Docker CLI.

**Comment by AKSHAYUBHAT** [comment]
@samuelkarp  You are right. 
However would just mounting the volume with nvidia drivers as described here work? 

http://docs.aws.amazon.com/batch/latest/userguide/example-job-definitions.html#example-test-gpu
```json
{
    "containerProperties": {
        "mountPoints": [{
            "sourceVolume": "nvidia",
            "readOnly": false,
            "containerPath": "/usr/local/nvidia"
        }],
        "image": "nvidia/cuda",
        "vcpus": 2,
        "command": ["nvidia-smi"],
        "volumes": [{
            "host": {"sourcePath": "/var/lib/nvidia-docker/volumes/nvidia_driver/latest"},
            "name": "nvidia"
        }],
        "memory": 2000,
        "privileged": true,
        "ulimits": []
    },
    "type": "container",
    "jobDefinitionName": "nvidia-smi"
}
```

My assumption was that all nvidia-docker did was adding a volume entry for the drivers. Since ECS and Batch have same architecture the solution for latter would work with former as well.

**Comment by AKSHAYUBHAT** [comment]
I was able to successfully update AWS Deep Learning AMI using instructions provided in AWS Batch documentation except with couple of changes changes and got it to work with ECS agent.
http://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html
Changes [resulting script is here](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/cloud/gpu_ami.sh):

1. Add ec2-user to docker group (this might not be required)
2. Change nvidia/cuda to nvidia/cuda:8.0 since default cuda image uses 9.0 which is not compatible with current drivers for p2 instances.

Additionally you also have to update ECS agent, since I forgot this while creating AMI. I do this during boot using user data script (ignore the EFS mount lines below).

```
Content-Type: multipart/mixed; boundary="==BOUNDARY=="
MIME-Version: 1.0

--==BOUNDARY==
Content-Type: text/cloud-boothook; charset="us-ascii"

# Install nfs-utils
cloud-init-per once yum_update yum update -y
cloud-init-per once install_nfs_utils yum install -y nfs-utils

# Create /efs folder
cloud-init-per once mkdir_efs mkdir /efs

# Mount /efs
cloud-init-per once mount_efs echo -e '{}:/ /efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0' >> /etc/fstab
mount -a

--==BOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
# Set any ECS agent configuration options
echo "ECS_DATADIR=/data" >> /etc/ecs/ecs.config
echo "ECS_ENABLE_TASK_IAM_ROLE=true" >> /etc/ecs/ecs.config
echo "ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true" >> /etc/ecs/ecs.config
echo "ECS_LOGFILE=/log/ecs-agent.log" >> /etc/ecs/ecs.config
echo "ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]" >> /etc/ecs/ecs.config
echo "ECS_LOGLEVEL=info" >> /etc/ecs/ecs.config
echo "ECS_CLUSTER={}" >> /etc/ecs/ecs.config
docker pull amazon/amazon-ecs-agent:latest
--==BOUNDARY==--

```

After this I ensured that nvidia-driver volume and privileged mode were correctly added 
to task

e.g. 
```
{
    "containerProperties": {
        "mountPoints": [{
            "sourceVolume": "nvidia",
            "readOnly": false,
            "containerPath": "/usr/local/nvidia"
        }],
       ...
        "volumes": [{
            "host": {"sourcePath": "/var/lib/nvidia-docker/volumes/nvidia_driver/latest"},
            "name": "nvidia"
        }],
...
        "privileged": true,
    },
    "type": "container",
}
```

After running a job I manually verified that GPU was being used by nvidia-smi.

**Comment by AKSHAYUBHAT** [comment]
Edited above instruction with new AMI that has ECS agent pre-updated.

**Comment by chenliu0831** [comment]
@AKSHAYUBHAT that's great. Btw I'm using those flags to remove the privileged mode  
```
-v /var/lib/nvidia-docker/volumes/nvidia_driver/latest:/usr/local/nvidia \
--device /dev/nvidiactl:/dev/nvidiactl \
--device /dev/nvidia0:/dev/nvidia0 \
--device /dev/nvidia-uvm:/dev/nvidia-uvm
```
