### ISSUE TITLE
No such container errors in our logs

### ISSUE THREAD

**Issue by bshelton229** [aws/amazon-ecs-agent#679]
Our logs contain a lot of errors like the following after firing tasks into our cluster:

```
time="2017-01-20T19:15:56.183453921Z" level=error msg="Handler for GET /v1.17/containers/2e3d6ec52b7bf42ce045950c9dd8973da2aa12d9fedcf94b75b93b97872d932f/json returned error: No such container: 2e3d6ec52b7bf42ce045950c9dd8973da2aa12d9fedcf94b75b93b97872d932f"
```

We're running ecs-agent `1.13.1`. I think I've narrowed these errors down to ecs-agent due to the docker api version being used.

As far as we can tell the tasks are starting and stopping correctly. This cluster is for ETL processes. A lambda function runs and fires off the appropriate tasks on cron schedules.

I generally like to cut down on un-actionable errors in syslog so I wanted to see if this is a known issue.

We're running docker `1.12.6-cs6` on Ubuntu 16.04.

Thanks

**Comment by aaithal** [comment]
Hi @bshelton229, ECS Agent relies on Docker event stream mainly to watch for container state changes on a Container Instances. However, since the event-stream and even processing can be lossy, it explicitly inspects the container in question whenever it receives any container event. This is probably what's leading to such statements in the docker log. We could change the ECS Agent code to not do this on `remove` events, but that would still not guarantee that such lines won't be printed in docker logs as any delay in event processing or reconciliation logic of the ECS Agent could still lead to this. Hope that answers your question. Please let us know if you need any other information. Thanks!

**Comment by bshelton229** [comment]
Thanks! That answers my question.
