### ISSUE TITLE
Draining container instance does not gracefully terminate services

### ISSUE THREAD

**Issue by alexwen** [aws/amazon-ecs-agent#700]
This morning we attempted a drain of a node in our cluster to rebalance tasks. It appears as though from client data that the connections were prematurely severed, and one of our services was not properly drained from the load balancer (as happens during an upgrade).

Were we mistaken in our understanding of the new drain instance functionality? Or is there another issue? Is there a safe way to take an instance out of rotation and migrate its services in an orderly fashion?

**Comment by richardpen** [comment]
@alexwen Sorry for the late reply, you can find the documentation about container instance draining [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-draining.html). Also there is a blog on how to automate it [here](https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/). To help us root cause the issue, could you provide the following information through email to penyin (at) amazon.com:
* Account ID
* Region
* Service Name
* Instance ID that experienced this problem

Thanks,
Richard

**Comment by alexwen** [comment]
Hi Richard,

Thanks for the reply. I had only read the blog post but had yet to see the documentation. One issue we may have run into was that the default minimum healthy percent, 50%, is the setting for most, if not all, of our services. It appears as though changing this to 100% will force ECS to bring up new tasks for services on the affected instance before attempting to tear down the old one.

We still saw the issue where it appeared as though the services which were downsized did not properly have their connections drained despite being seen as healthy in the ALB.

I will close this issue and follow-up over email regarding the draining problem.

Thanks again,
Alex
