### ISSUE TITLE
ECS Agent cant not be retrieved

### ISSUE THREAD

**Issue by YerisAntonio** [aws/amazon-ecs-agent#714]
Getting these erros lately using the amzn-ami-2016.03.h-amazon-ecs-optimized (ami-6bb2d67c)

```
> 2017-02-17T12:17:39Z [INFO] pre-start
> 2017-02-17T12:17:39Z [INFO] Downloading Amazon EC2 Container Service Agent
> 2017-02-17T12:17:39Z [DEBUG] Downloading published md5sum from https://s3.amazonaws.com/amazon-ecs-agent/ecs-agent-v
> 1.14.0.tar.md5
> 2017-02-17T12:17:44Z [ERROR] could not download Amazon EC2 Container Serivce Agent: Get https://s3.amazonaws.com/ama
> zon-ecs-agent/ecs-agent-v1.14.0.tar.md5: dial tcp 52.216.16.51:443: i/o timeout
> 2017-02-17T12:17:44Z [INFO] post-stop
> 2017-02-17T12:17:44Z [INFO] Cleaning up the credentials endpoint setup for Amazon EC2 Container Service Agent

```

To fix this i have to go in and manually set start ecs

**Comment by nmeyerhans** [comment]
Hi @YerisAntonio. To be clear, if you manually `start ecs` on an instance after this happens, the new agent version is actually downloaded? Can you share ecs-init logs showing that behavior, for comparison?

What's surprising is that, if you're using ami-6bb2d67c then you must have already communicated to S3 in order to have updated to a version of ecs-init that knows about agent 1.14.0 in the first place, so we know the instance has connectivity. Although the yum updates are performed over tcp port 80, while the ecs-init agent update happens over port 443. Can you verify that outbound TCP connections on port 443 are allowed by your VPC ACLs, and that the inbound TCP port range matches the ephemeral port range used on your instances? (Obtained with `sysctl net.ipv4.ip_local_port_range`)

Ecs-init should probably be improved to be more robust against transient connectivity issues when downloading the agent. Additionally, it's worth it for us to consider whether we should fall back to an on-disk agent image if we can't download a newer one. I'm not convinced that that's desirable, though, as it may re-introduce security issues or other bugs that the new agent was intended to fix, and generally may lead to confusion about what agent versions are running on your instances.

**Comment by nmeyerhans** [comment]
I've opened https://github.com/aws/amazon-ecs-init/issues/83 against ecs-init, because we definitely should be retrying these failed downloads, regardless of their root cause.

**Comment by aaithal** [comment]
Hi @YerisAntonio I'm closing this issue as it's being tracked in https://github.com/aws/amazon-ecs-init/issues/83. Please feel free to reopen this issue/add additional comments.
