### ISSUE TITLE
Troubleshooting `docker run`

### ISSUE THREAD

**Issue by elgalu** [aws/amazon-ecs-agent#77]
Hi I'm trying to find out why `$(whoami)` fails when ecs-agent `docker run`s my containers, when I ssh into the instance and launch a container via the CLI it works fine but I don't find a way to `docker run` in the exact same or the exact params that ecs-agent is doing, probably because is done through the fsouza/go-dockerclient but then how can I debug this? is there a endpoint at the ECS Container Agent Introspection API that I can use? Or what would be the CLI equivalent of the API call?

**Comment by euank** [comment]
One way you can debug the exact parameters being used is to run the docker deamon with the `-D` option and look at the debug information printed about your calls.

You can also use `docker inspect` and look at the Config + HostConfig values to get a fairly faithful representation in how they were launched.

However, it sounds to me like what you're doing is `docker run $container $(whoami)` via the CLI, which is not expanded by Docker but by your shell (probably bash). What the docker CLI sees is `docker run $container username` since the shell expansion happens before the argument is passed to docker.
The ECS Agent does not put anything through a shell and so it will pass the literal string '$(whoami)' through to docker.

I think this might be a duplicate of #3.
I'm interested in hearing more about what your intended use-case here is, though. Are you trying to get a host username? Username within the container? User the ECS Agent is running as?

Best,
Euan

**Comment by elgalu** [comment]
I was trying to get 
> User the ECS Agent is running as

However I realized my issue was due to a silly error, made a mistake when specifying the ENTRYPOINT and saw the issue thanks to your `docker inspect` suggestion ;)
