### ISSUE TITLE
Mounting EBS Volumes requires ECS Agent and Docker restart

### ISSUE THREAD

**Issue by tsturzl** [aws/amazon-ecs-agent#799]
I spent most of today trying to get an EBS volume mounted on a docker container. I found in another ticket that I need to restart docker and thus ecs agent to get the volumes to mount. This seems like a bug to me. Once I did restart docker and the ecs agent I was able to mount the volume to my container by specifying it in my task and container definitions. Is there anyway to fix this issue?

**Comment by jhaynes** [comment]
Sorry for the frustration @tsturzl. While I cannot give a precise date, this will be fixed in our upcoming release.

**Comment by samuelkarp** [comment]
Closing this; we should have closed this a while ago.  Recent releases of the `docker` package for Amazon Linux (since 17.03.1, if my memory serves me correctly) no longer use a private mount namespace, so you no longer need to restart Docker when attaching and mounting EBS volumes in order to use those mountpoints in your task definitions.
