### ISSUE TITLE
Permission denied pulling images from quay.io.

### ISSUE THREAD

**Issue by optimality** [aws/amazon-ecs-agent#86]
I'm trying to troubleshoot some issues with the agent, but I can't get a shell in the container.  I can get a shell in other containers.

```bash
% docker run -it --entrypoint "/bin/bash" ubuntu
```

Works fine.  This doesn't:

```bash
% docker run -it --entrypoint "/bin/bash" amazon/amazon-ecs-agent
exec: "/bin/bash": stat /bin/bash: no such file or directory
FATA[0000] Error response from daemon: Cannot start container 87b432eab5ae7439fd1a0e4275b51b5e36fb40a7d230a8ebc7885683fd202c20: [8] System error: exec: "/bin/bash": stat /bin/bash: no such file or directory
```

Docker info:

```bash
% docker info
Containers: 3
Images: 46
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 8
Total Memory: 1.957 GiB
Name: boot2docker
ID: QD2S:VSPG:KS3T:L72V:UXPI:U3SN:M4C7:3BJT:5SN2:LI3P:W2RF:AMGL
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 17
System Time: Thu May 21 15:18:58 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: optimality
Registry: [https://index.docker.io/v1/]
```

**Comment by euank** [comment]
The agent's container, as built by default, only contains the agent as a statically linked binary. This allows the image to be very small and specialized, but yes it also means there's no `/bin/bash` or other extra data in the image. You can see how it's built [here](https://github.com/aws/amazon-ecs-agent/blob/158f6f79415caacf8219b470bb9ef74831073b1b/scripts/dockerfiles/Dockerfile.release#L16). If you're interested, there are several blog posts explaining this pattern, such as [these](http://blog.xebia.com/2014/07/04/create-the-smallest-possible-docker-container/) [two](https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07).

What are you trying to troubleshoot? I'd be happy to try and help figure out if there's a better approach.

**Comment by optimality** [comment]
Oh, I was looking at [Dockerfile.build](https://github.com/aws/amazon-ecs-agent/blob/158f6f79415caacf8219b470bb9ef74831073b1b/scripts/dockerfiles/Dockerfile.build), which uses golang as its base.  My bad.

I'm getting a 403/Permission Denied trying to pull an image from Quay.io.  I'm pretty sure the env variables are set correctly and that the ecs.config is correct, so I'm looking for other issues.

**Comment by euank** [comment]
The agent doesn't log very much around auth. The docker deamon, when launched with `--debug=true`, will print out some amount of auth information. Specifically, you should see a line similar to "Getting bearer token with ... for $user" I believe.

If the docker deamon isn't being given auth information, the best solution would probably be to add more debug output to the agent (such as [this](https://github.com/euank/amazon-ecs-agent/commit/4dbc859f94f4f67399e9a920d25ec3a7e3ea69b7) as a start to triage it).

If you're familiar with gdb, you could also attach that to the agent process from the host and add breakpoints around the auth-related functions or PullImage and step through it.

When you figure out what's wrong, I'd be interested in knowing to see if I can make sure it's easier to debug or fixed in the future.

If you have further questions I'd be happy to try and help more.

Good luck,
Euan

**Comment by optimality** [comment]
Actually, I'm just an idiot.  I had a typo in the image name.  Sorry, my bad.
