### ISSUE TITLE
Disparity between Cloudwatch's reported RAM utilization and docker stats

### ISSUE THREAD

**Issue by canha** [aws/amazon-ecs-agent#863]
I've got multiple examples of this I'm but picking a particular case where a service's task definition with 750MB is reporting, on average, 70% utilization on the following Cloudwatch's metric:
```
Namespace: AWS/ECS
Metric Name: MemoryUtilization
Dimensions: ServiceName and ClusterName
```

but if I inspect the container docker stats it's using 99%, almost 100%. Where does this disparity come from? How can I get cloudwatch's values to report correctly? I've never seen these MemoryUtilization metrics working as expected.

Any help on this issue is greatly appreciated.

Example task definition:
```
[
    {
        "cpu": 128,
        "essential": true,
        "image": "...",
        "memory": 750,
        "name": "...",
        "portMappings": [
            {
                "containerPort": ...,
                "hostPort": 0
            }
        ],
        "environment" : [...],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {...}
        }
    }
]
```

**Comment by nmeyerhans** [comment]
Hi @canha. With ecs agent version 1.14.0, released this past January, we made a change to the memory utilization metrics reporting to make it more accurately reflect the amount of memory in use by your application. Specifically, we changed the metric to exclude memory used by the linux page cache, since this is memory that can be reclaimed transparently by the kernel.

See issue #280 and PR #582 for background and please feel free to reopen this issue if you've got further questions or concerns.
