### ISSUE TITLE
Ensuring a task gets placed; memory_reservation=0 ?

### ISSUE THREAD

**Issue by cjbottaro** [aws/amazon-ecs-agent#876]
There are some tasks that I want to absolutely make sure get placed in the cluster, despite what the cluster resources are.  Would it be possible to create a task def with something like:
```
memory_reservation: 0
memory: 64
```
With the intent of ensuring the task gets scheduled no matter how much free memory is available on the container instance?

Thanks.

**Comment by adnxn** [comment]
> Would it be possible to create a task def with something like:
```
memory_reservation: 0
memory: 64
```
Setting `memory_reservation` and `memory` ensures that the lower `memory_reservation` would be used for scheduling the container and it would be killed if it exceeds the `memory` parameter. So, you would be able to pack more containers into an instance using this strategy. However, it also leads to very confusing behavior when there's contention because of said oversubscription.

> With the intent of ensuring the task gets scheduled no matter how much free memory is available on the container instance

Docker Config and ECS Task Definition both require non-zero integers to be set for this value so as to facilitate proper accounting of resources (Docker enforces a 4MB minimum for both `memory_reservation` and `memory`). Not doing so would result in ECS not being able to keep track of resources used on the instance and hence not being able to make effective scheduling decisions. Hence, we do require this value to be set to `>0`. 

A workaround could be setting the `memoryReservation` value to a small non-zero value (since 4MB is the minimum required by Docker) to maximize the opportunity for the scheduler to assign tasks to a specific instance. Unlike the `memory` parameter, setting the `memoryReservation` will not force the container to be killed if the memory usage exceeds the limit. It will let you schedule up to N tasks, such that N * memoryReservation is lesser than the available memory on the container instance.

For more information, please refer to [memory and memoryReservation sections of the task definition parameters page](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions) in the ECS docs.

**Comment by cjbottaro** [comment]
@adnxn Hmm, that response spurs more questions.  Does the ECS Agent kill tasks with containers that are maxing out their memory?  I know that Docker doesn't.

I ran a container that just appends random data to an array in an infinite loop.  I ran it with a memory limit.  According to `docker stats` it quickly hits 100% and then keeps running.

So then I made a watchdog container that looks for other containers maxing out their memory and kills them.  I need this watchdog to run on every ECS instance.  So my idea was to give it a placement constraint of unique host, desired count of 1000 (or something very high), then memory reservation of 0 (or I guess 4 is the lowest) to ensure that it gets scheduled.

> Unlike the memory parameter, setting the memoryReservation will not force the container to be killed if the memory usage exceeds the limit.

That statement confuses me since I have observed Docker to _not_ kill a container that exceeds its memory limit.  Is that something that ECS Agent does?

Thanks.

**Comment by adnxn** [comment]
Hey @cjbottaro, so just to clarify a few points.

> I have observed Docker to not kill a container that exceeds its memory limit

If we set a memory limit for a container in Docker, the kernel will kill the container process if that limit is exceeded and this behavior is also described in [Docker documentation](https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory). The task definition's `memory` parameter maps to Docker's `--memory=` flag.

> I ran a container that just appends random data to an array in an infinite loop. I ran it with a memory limit. According to docker stats it quickly hits 100% and then keeps running.

Which memory flag did you use exactly? Docker has a handful of options to limit a container's access to memory. I want to make sure we're on the same page.

>  I made a watchdog container that looks for other containers maxing out their memory and kills them. I need this watchdog to run on every ECS instance. So my idea was to give it a placement constraint of unique host, desired count of 1000 (or something very high), then memory reservation of 0 (or I guess 4 is the lowest) to ensure that it gets scheduled.

You should be able to cover this use case by specifying the `memory` parameter in the task definition. Containers that exceed your specified memory limit should be killed by the kernel since the limit was provided to Docker explicitly through the task definition.

> That statement confuses me 

So to clarify, the task definition's `memoryReservation` maps to docker's `--memory-reservation` flag and this is soft limit that does not guarantee that the container will not exceed the limit.

Thanks!
