### ISSUE TITLE
ecs-agent offline but ALB still routing request

### ISSUE THREAD

**Issue by CalvinWong-Reflektion** [aws/amazon-ecs-agent#890]
we we ran into this issue where the ecs-agent is offline but ALB still routing request. hence the request will not be process since theres no container instance running there.

what could be the cause of this?

what can we do in the future to gather more details of this issue if it ever arise again?

**Comment by petderek** [comment]
Hi @CalvinWong-Reflektion,

Sorry you are runnning into trouble with ALB and ECS. By design, ALB won't stop routing to a container instance when the agent is disconnected. This is because the agent may disconnect while containers in a Task are still active on the container instance.

Could you clarify a few questions:

* Are there any tasks running on the container instance?
* What health check settings are you using on your ALB?

**Comment by CalvinWong-Reflektion** [comment]
according to the jira ticket that was created. there werent any container instance.
unfortunately we havent seen this since (a while ago now). so i cant see it being reproduced.

health check settings -

Protocol | HTTP
-- | --
Path | /
Port | traffic port
Healthy threshold | 5
Unhealthy threshold | 2
Timeout | 5
Interval | 30
Success codes | 200

**Comment by petderek** [comment]
Thanks! I want to clarify a couple points:

* Agent will periodically disconnect and reconnect to our service as part of normal operation. A disconnected agent does not imply that tasks on a container instance are (or aren't) running.

* A disconnected agent will not affect ALB health checks. The health check should only be targeting your application container. [More information is available in our docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html).

It sounds like you haven't seen this problem in a while now (great!), but if you see it again I would consider validating the thresholds and interval of your health check.

**Comment by CalvinWong-Reflektion** [comment]
cool. thanks for clarifying!!! ya 🤞
