### ISSUE TITLE
ECS agent never starts

### ISSUE THREAD

**Issue by treaves** [aws/amazon-ecs-agent#905]
I am trying to use ECS with Jenkins.  Jenkins does create an instance in ECS, but, it never comes on-line.  There is a message in the ecstasy log file about "Error retrieving stats for container" and then it seems to shutdown.  After this time, there is then a message int he docker log that the agent does not exist.

I have attached the log files from running "ecs-logs-collector.sh".  As I am new to AWS, I'm sure I am leaving out details.  Please let me know if other information is needed.

Thanks.
[collect.zip (removed)]()
[Jenkins_Docker_log.txt (removed)]()

**Comment by jahkeup** [comment]
Hello @treaves! 

Thanks for providing your logs with your issue! 

As a precaution I have removed the links you've provided as they appear to contain hostnames and tokens used for Jenkins node registration. 

I looked over the logs and noted that the containers are starting but are rapidly exiting and thus transitions from RUNNING to STOPPED within 2 seconds of transitioning. I believe the issue lies with the command provided to start the jenkins-slave. The current Task has its command set as `jenkins-slave -url <jenkins_jnlp_url> <token> <name>`, I tried invoking this with a similar invocation and was unable to start the slave, however removing the `jenkins-slave` command at the beginning (ie: ` -url <jenkins_jnlp_url> <token> <name>`) allows the entrypoint to properly handle the flags and execute properly. Please try that and see if the containers are able to remain running.

**Comment by treaves** [comment]
Thank you for the response.

I didn't think there was any sensitive data it what I posted; but, I'm still fairly ignorant about this.  Working to overcome that.

When I look at my ECS area in the console, I see no Task definitions. So I'm guessing the Task is created by the Jenkins plugin.  So I'll try to (again) get them to look at it.

**Comment by richardpen** [comment]
@treaves Since we haven't heard from you for a long time, I'm closing this issue for now, feel free to reopen it if you experience the problem again.

Thanks,
Peng

**Comment by sachingupta771** [comment]
Hello Team,

I am also experiencing the same errors, with no logs and no help from the internet, Please help and share the steps you followed for debugging.
