### ISSUE TITLE
Log level on errors

### ISSUE THREAD

**Issue by s-maj** [aws/amazon-ecs-agent#949]
Hello, 

I am trying to parse logs from ECS Agent, mostly to spot errors like this:
```
2017-08-19T21:47:31Z [INFO] TaskHandler, Sending container change: ContainerChange: arn:aws:ecs:xx-zzzz-1:xxxxxxxxxxx:task/e6063a6d-f11d-45d5-833f-36dc316f239c zzz-yyyy-task -> STOPPED, Exit 0, , Reason CannotPullContainerError: Error: image  zzz-yyyy-task:dev-20135 not found, Known Sent: RUNNING
```
Is INFO log level on errors intentional?

**Comment by richardpen** [comment]
@s-maj Thanks for bring this up, initially this log level is intentional, it helps us understand whether the state change has been reported to our backend. 

While in the latest version [v1.14.4](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.4), we replaced this part with the batch state change API, so you will not see this log with the new agent.  Please upgrade to the latest version of agent to get rid of this.

I"m closing this for now, feel free to reopen it if you have further question.

Thanks,
Peng

**Comment by samuelkarp** [comment]
The ERROR log level is generally used to indicate things going wrong with the agent itself, or other unexpected behavior.  Containers that can't be pulled is actually expected behavior when something is preventing the image from being pulled (a typo in the image name, a failed network connection between Docker and the registry, failing authentication, etc) and doesn't indicate that something went wrong with the ECS agent.

**Comment by s-maj** [comment]
@samuelkarp @richardpen thanks for detailed explanation. The reason why I asked this question is that can't find an easy way to detect deployment failure in ECS. Currently, I am parsing ECS agent logs looking for certain phrases (like CannotPullContainerError) and trigger alerts if spotted.
